### ISSUE TITLE
在使用定时任务的情况下，shutdown.sh tomcat会报如下警告。

### ISSUE THREAD

**Issue by william-xian** [nutzam/nutz#1001]
12-Jan-2016 16:44:38.856 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [app] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
 com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:43)

**Comment by wendal** [comment]
其实呢,这是mysql的问题,当然,解法当然有

```
		try {
			Mirror.me(Class.forName("com.mysql.jdbc.AbandonedConnectionCleanupThread")).invoke(null, "shutdown");
		} catch (Throwable e) {
		}
```

参考nutzbook项目的源码

https://github.com/wendal/nutz-book-project/blob/master/src/main/java/net/wendal/nutzbook/MainSetup.java
