### ISSUE TITLE
自定义查询返回的内容为 null 的问题

### ISSUE THREAD

**Issue by jackxmcheng** [nutzam/nutz#1008]
近日，通过一个简单的自定义查询想想返回一个权限的名称字符串列表，由于前期没有数据，所以该查询实际上是查不到数据的，但是nutz的 Sql.setCallback(Sqls.callback.strList()) 返回的 List<String> 中包含了一条 null 的字符串？正常吗？还是我写的代码有问题？

	sql = dao().sqls().create("security.user_permissions");
	sql.params().set("user_id", principal.getId());
	sql.setCallback(Sqls.callback.strList());
	dao().execute(sql);
	
	List<String> permissions = sql.getList(String.class);
	if (null != permissions) {
		principal.permissions.addAll(permissions);
	}

**Comment by wendal** [comment]
跟nutz木有关系

```
public class QueryStringCallback implements SqlCallback {

    public Object invoke(Connection conn, ResultSet rs, Sql sql) throws SQLException {
        List<String> list = new LinkedList<String>();
        while (rs.next())
            list.add(rs.getString(1));
        return list;
    }

}
```
