### ISSUE TITLE
@one和@many怎么配置？

### ISSUE THREAD

**Issue by zbd0518** [nutzam/nutz#1013]
@Table("t_credentialstype")
public class Credentials {
    @Name
    private String id;

    @Column("parentid")
    private String parentId;

    @One(target = Credentials.class, field = "parentId")
    private Credentials credentialsType;

    @Many(target = Credentials.class, field = "parentId")
    private List<Credentials> children;

其中parentId能查询到数据，但是 credentialsType 和 children全是null

**Comment by wendal** [comment]
没执行fetchLinks

http://nutz.cn/yvr/t/vfvjalruosh7ura74cqlmahomn
