### ISSUE TITLE
Trans这个问题挺多，是否需要重写啊

### ISSUE THREAD

**Issue by ericktang** [nutzam/nutz#1020]
比如，Trans嵌套，程序中不小心多次commit，或者多次close，都会出现问题，主要原因是Trans程序逻辑只判断了count.get()>=0的情况，比如一旦程序中嵌套执行了两次close，_depose会把trans.set(null)，如果程序再次执行close，必然抛出，_commit也是，没有对count进行判断，上来就count.set(count.get() - 1);如果已经嵌套执行过close，这里肯定死翘翘，后面的Transaction tn = trans.get();肯定是null。

**Comment by zozoh** [comment]
如果是你手工的 commit / close 那么还是希望能配对吧
如果你懒得配对，用 Trans.exec 咯

当初的考虑是，如果容忍了 commit 和 close 不配对，会不会其实会掩盖了你自己代码逻辑里的隐患呢？

**Comment by ericktang** [comment]
举个例子看看：
public void doSomething(Dao dao){
    	try{
    		//开启Transaction
    		Trans.begin();
    		//做了很多操作数据库操作的事情，这里如果调用了任何 dao.execute(....)的话，excute中也判断是在Transaction中，
    		//那么里面也有一个完整的 _begin/commit/close，其中因为调用了close，就把Trans设置为null了，后面的即使打印Debug也会出错，
    		//因为里面调用了Trans.exec，这个代码是这样的：
    		/*
    		 public static void exec(int level, Atom... atoms) {
        		try {
            		_begain(level);
            		for (Atom atom : atoms)
                	atom.run();
            		_commit();
        		}
        		catch (Throwable e) {
            		_rollback(num);
            		throw Lang.wrapThrow(e);
        		}
        		finally {
            		_depose();
        		}
    		}
    		 */
    		
    		Trans.commit();
    	}catch(Exception e){
    		Trans.rollback();
    	}finally{
    		//这里肯定报错，因为 Trans.exec已经close了，
    		Trans.close();
    	}

**Comment by zozoh** [comment]
你真的能写出一段肯定会抛错的，并且是配对的 Trans 代码？
上面这段代码，是不会抛错的吧

**Comment by ericktang** [comment]
写了个代码参考一下哈！
`import java.util.Properties;

import org.nutz.dao.Dao;
import org.nutz.dao.Sqls;
import org.nutz.dao.sql.Sql;
import org.nutz.dao.util.DaoUp;
import org.nutz.trans.Trans;

public class TestDao {

	public static void main(String[] args) throws Exception {
		Properties props = new Properties();
		props.put("driverClassName", "org.h2.Driver");
		props.put("url", "jdbc:h2:z:/testdao");
		DaoUp.me().init(props);
		Dao dao = DaoUp.me().dao();
		System.out.println(dao.meta());

		if(!dao.exists("TESTDAO")){
			Sql sql = Sqls.create("CREATE TABLE TESTDAO(id int PRIMARY KEY, name varchar(20));");
			dao.execute(sql);
		}
		dao.clear("TESTDAO");
		
		testTrans(dao);
		DaoUp.me().close();
	}
	public static void testTrans(Dao dao) throws Exception{
		try{
			Trans.DEBUG = true;
			Trans.begin();
			for(int i=0;i<2;i++){
				Sql sql = Sqls.create("INSERT INTO TESTDAO (id,name) VALUES(@id,@name)");
		        sql.params().set("id", i+1).set("name", "haha"+i);
		        dao.execute(sql);
				//Trans.commit(); //放这里也会出错，就是说中间干点什么事情commit不行
			}
			//testTrans2(dao); 这里也会出错，比如这个是去写个日志什么的操作，如果是SQLite数据库也会错误，因为进入了Trans
			Trans.commit();
			testTrans2(dao); //这里如果
		}catch(Exception e){
			Trans.rollback();
		}finally{
			Trans.close();
		}
	}
	public static void testTrans2(Dao dao) throws Exception{
		try{
			Trans.DEBUG = true;
			Trans.begin();
			for(int i=10;i<12;i++){
				Sql sql = Sqls.create("INSERT INTO TESTDAO (id,name) VALUES(@id,@name)");
		        sql.params().set("id", i+1).set("name", "haha"+i);
		        dao.execute(sql);
			}
			Trans.commit();
		}catch(Exception e){
			Trans.rollback();
		}finally{
			Trans.close();
		}
	}
}
`

控制台打印记录如下：

`2016-2-22 9:57:28.50 WARN [main] !!You are using default SystemLog! Don't use it in Production environment!!
2016-2-22 9:57:28.78 INFO [main] Nutz is licensed under the Apache License, Version 2.0 .
Report bugs : https://github.com/nutzam/nutz/issues
2016-2-22 9:57:28.80 DEBUG [main] build SimpleteDataSource by props
2016-2-22 9:57:28.84 WARN [main] SimpleDataSource is use for Test/Attempt, NOT Using in Production environment!
2016-2-22 9:57:28.84 WARN [main] SimpleDataSource is NOT a Connection Pool, So it is slow but safe for debug/study
2016-2-22 9:57:28.97 DEBUG [main] NutDao[_selfId=0] init ...
2016-2-22 9:57:28.176 DEBUG [main] Using 94 castor for Castors
2016-2-22 9:57:28.183 INFO [main] Init file-pool by: C:\Users\Ericktang/.nutz/tmp/dao/ [2000]
2016-2-22 9:57:28.183 DEBUG [main] file-pool.home: 'C:\Users\Ericktang\.nutz\tmp\dao'
2016-2-22 9:57:28.184 INFO [main] file-pool.cursor: 0
2016-2-22 9:57:28.193 DEBUG [main] Jdbcs init complete
2016-2-22 9:57:28.193 INFO [main] Get Connection from DataSource for JdbcExpert, if I lock at here, check your database server and configure
2016-2-22 9:57:28.372 DEBUG [main] JDBC Driver --> 1.4.191 (2016-01-21)
2016-2-22 9:57:28.372 DEBUG [main] JDBC Name   --> H2 JDBC Driver
2016-2-22 9:57:28.373 DEBUG [main] JDBC URL    --> jdbc:h2:z:/testdao
2016-2-22 9:57:28.373 DEBUG [main] Database info --> H2:[H2 - 1.4.191 (2016-01-21)]
H2:[H2 - 1.4.191 (2016-01-21)]
2016-2-22 9:57:28.405 DEBUG [main] DELETE FROM TESTDAO 
2016-2-22 9:57:28.411 DEBUG [main] Start New Transaction id=0, level=2
2016-2-22 9:57:28.416 DEBUG [main] Attach Transaction    id=0, level=2
2016-2-22 9:57:28.432 DEBUG [main] INSERT INTO TESTDAO (id,name) VALUES(1,'haha0')
2016-2-22 9:57:28.434 DEBUG [main] Transaction delay Commit id=0, count=1
2016-2-22 9:57:28.434 DEBUG [main] Attach Transaction    id=0, level=2
2016-2-22 9:57:28.435 DEBUG [main] INSERT INTO TESTDAO (id,name) VALUES(2,'haha1')
2016-2-22 9:57:28.435 DEBUG [main] Transaction delay Commit id=0, count=1
2016-2-22 9:57:28.435 DEBUG [main] Transaction Commit id=0
2016-2-22 9:57:28.436 DEBUG [main] Attach Transaction    id=0, level=2
2016-2-22 9:57:28.436 DEBUG [main] Attach Transaction    id=0, level=2
2016-2-22 9:57:28.436 DEBUG [main] INSERT INTO TESTDAO (id,name) VALUES(11,'haha10')
2016-2-22 9:57:28.437 DEBUG [main] Transaction delay Commit id=0, count=1
2016-2-22 9:57:28.437 DEBUG [main] Attach Transaction    id=0, level=2
2016-2-22 9:57:28.437 DEBUG [main] INSERT INTO TESTDAO (id,name) VALUES(12,'haha11')
2016-2-22 9:57:28.438 DEBUG [main] Transaction delay Commit id=0, count=1
2016-2-22 9:57:28.438 DEBUG [main] Transaction Commit id=0
2016-2-22 9:57:28.438 DEBUG [main] Transaction depose id=0, count=0
Exception in thread "main" java.lang.NullPointerException
	at org.nutz.trans.Trans._depose(Trans.java:92)
	at org.nutz.trans.Trans.close(Trans.java:255)
	at TestDao.testTrans(TestDao.java:44)
	at TestDao.main(TestDao.java:25)
`

**Comment by ericktang** [comment]
2016-2-22 9:57:28.50 WARN [main] !!You are using default SystemLog! Don't use it in Production environment!!
2016-2-22 9:57:28.78 INFO [main] Nutz is licensed under the Apache License, Version 2.0 .
Report bugs : https://github.com/nutzam/nutz/issues
2016-2-22 9:57:28.80 DEBUG [main] build SimpleteDataSource by props
2016-2-22 9:57:28.84 WARN [main] SimpleDataSource is use for Test/Attempt, NOT Using in Production environment!
2016-2-22 9:57:28.84 WARN [main] SimpleDataSource is NOT a Connection Pool, So it is slow but safe for debug/study
2016-2-22 9:57:28.97 DEBUG [main] NutDao[_selfId=0] init ...
2016-2-22 9:57:28.176 DEBUG [main] Using 94 castor for Castors
2016-2-22 9:57:28.183 INFO [main] Init file-pool by: C:\Users\Ericktang/.nutz/tmp/dao/ [2000]
2016-2-22 9:57:28.183 DEBUG [main] file-pool.home: 'C:\Users\Ericktang\.nutz\tmp\dao'
2016-2-22 9:57:28.184 INFO [main] file-pool.cursor: 0
2016-2-22 9:57:28.193 DEBUG [main] Jdbcs init complete
2016-2-22 9:57:28.193 INFO [main] Get Connection from DataSource for JdbcExpert, if I lock at here, check your database server and configure
2016-2-22 9:57:28.372 DEBUG [main] JDBC Driver --> 1.4.191 (2016-01-21)
2016-2-22 9:57:28.372 DEBUG [main] JDBC Name   --> H2 JDBC Driver
2016-2-22 9:57:28.373 DEBUG [main] JDBC URL    --> jdbc:h2:z:/testdao
2016-2-22 9:57:28.373 DEBUG [main] Database info --> H2:[H2 - 1.4.191 (2016-01-21)]
H2:[H2 - 1.4.191 (2016-01-21)]
2016-2-22 9:57:28.405 DEBUG [main] DELETE FROM TESTDAO 
2016-2-22 9:57:28.411 DEBUG [main] Start New Transaction id=0, level=2
2016-2-22 9:57:28.416 DEBUG [main] Attach Transaction    id=0, level=2
2016-2-22 9:57:28.432 DEBUG [main] INSERT INTO TESTDAO (id,name) VALUES(1,'haha0')
2016-2-22 9:57:28.434 DEBUG [main] Transaction delay Commit id=0, count=1
2016-2-22 9:57:28.434 DEBUG [main] Attach Transaction    id=0, level=2
2016-2-22 9:57:28.435 DEBUG [main] INSERT INTO TESTDAO (id,name) VALUES(2,'haha1')
2016-2-22 9:57:28.435 DEBUG [main] Transaction delay Commit id=0, count=1
2016-2-22 9:57:28.435 DEBUG [main] Transaction Commit id=0
2016-2-22 9:57:28.436 DEBUG [main] Attach Transaction    id=0, level=2
2016-2-22 9:57:28.436 DEBUG [main] Attach Transaction    id=0, level=2
2016-2-22 9:57:28.436 DEBUG [main] INSERT INTO TESTDAO (id,name) VALUES(11,'haha10')
2016-2-22 9:57:28.437 DEBUG [main] Transaction delay Commit id=0, count=1
2016-2-22 9:57:28.437 DEBUG [main] Attach Transaction    id=0, level=2
2016-2-22 9:57:28.437 DEBUG [main] INSERT INTO TESTDAO (id,name) VALUES(12,'haha11')
2016-2-22 9:57:28.438 DEBUG [main] Transaction delay Commit id=0, count=1
2016-2-22 9:57:28.438 DEBUG [main] Transaction Commit id=0
2016-2-22 9:57:28.438 DEBUG [main] Transaction depose id=0, count=0
Exception in thread "main" java.lang.NullPointerException
	at org.nutz.trans.Trans._depose(Trans.java:92)
	at org.nutz.trans.Trans.close(Trans.java:255)
	at TestDao.testTrans(TestDao.java:44)
	at TestDao.main(TestDao.java:25)

**Comment by wendal** [comment]
先commit然后继续下一个事务... 醉了

**Comment by ericktang** [comment]
wendal，其实实际程序中，不是这么简单，实际使用中可能调用多个函数过程，每个过程既可以独立调用，也可能会被批量调用处理，肯定比这个复杂，我也是偶然才发现这个问题，^_^

**Comment by wendal** [comment]
额, 你弄个符合要求的代码来?? ^_^

**Comment by wendal** [comment]
如果新代码兼容老的写法,且能实现得更好,非常欢迎发pull req

**Comment by wendal** [comment]
如果不兼容, 倒是可以Trans2+NutDaoRunner2咯,事务就这两块

**Comment by wendal** [comment]
没下文了.
