### ISSUE TITLE
Map2Object Bigint 

### ISSUE THREAD

**Issue by francisoliverlee** [nutzam/nutz#1030]
在将Map转化为Object时， 我的一个对象属性是Bigint类型， 转化失败了。
错误代码：
 public Number cast(String src, Class<?> toType, String... args) {
        if(Strings.isBlank(src)) {
            return toType.isPrimitive()?Integer.valueOf(0):null;
        } else {
            try {
                return (Number)Mirror.me(toType).getWrapperClass().getConstructor(new Class[]{String.class}).newInstance(new Object[]{src});
            } catch (Exception var5) { //抛出异常
                throw new FailToCastObjectException(String.format("Fail to cast \'%s\' to <%s>", new Object[]{src, toType.getName()}), var5);
            }
        }
    }

异常信息：
e = {RuntimeException@2337} "java.lang.RuntimeException: Class 'java.math.BigInteger' should be a primitive class"
 detailMessage = "Class 'java.math.BigInteger' should be a primitive class"
 cause = {RuntimeException@2337} "java.lang.RuntimeException: Class 'java.math.BigInteger' should be a primitive class"
  detailMessage = "Class 'java.math.BigInteger' should be a primitive class"
  cause = {RuntimeException@2337} "java.lang.RuntimeException: Class 'java.math.BigInteger' should be a primitive class"
  stackTrace = {StackTraceElement[0]@2343} 
  suppressedExceptions = {Collections$UnmodifiableRandomAccessList@2344}  size = 0
 stackTrace = {StackTraceElement[0]@2343} 
 suppressedExceptions = {Collections$UnmodifiableRandomAccessList@2344}  size = 0

分析：
是不是转化时支持Java基础类型， 其余的类型暂时不支持。

希望：
可以支持常用的类型 进行 to Object

**Comment by wendal** [comment]
getWrapperClass方法的bug,得看看怎么改了
