### ISSUE TITLE
Lang.collection2map 和 Lang.array2map的问题

### ISSUE THREAD

**Issue by happyday517** [nutzam/nutz#1039]
```
List<Item> items = ...
Map<Long, Item> itemMap = Lang.collection2map(HashMap.class, items, "id");
```
这段代码用jdk8自带的javac编译会报错:
不兼容的类型: 不存在类型变量T的实例, 以使java.util.Map<?,?>与java.util.Map<java.lang.Long,Item>一致

**Comment by wendal** [comment]
```
mvn clean -Dmaven.test.skip=true package
```

刚刚测试了一下,没问题的呢

**Comment by happyday517** [comment]
是用jdk8自带的编译器吗?

**Comment by happyday517** [comment]
在Eclipse中代码是可以正常工作的 Eclipse用自己的编译器
用jkd自带的编译器才会报错

**Comment by wendal** [comment]
说说用啥命令编译的

**Comment by happyday517** [comment]
用maven编译的

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.5.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
          <encoding>UTF-8</encoding>
        </configuration>
      </plugin>

**Comment by happyday517** [comment]
换Eclipse的编译器就OK了

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.5.1</version>
        <configuration>
          <compilerId>eclipse</compilerId>
          <source>1.8</source>
          <target>1.8</target>
          <encoding>UTF-8</encoding>
        </configuration>
          <dependencies>
            <dependency>
              <groupId>org.codehaus.plexus</groupId>
              <artifactId>plexus-compiler-eclipse</artifactId>
              <version>2.7</version>
            </dependency>
          </dependencies>
      </plugin>

**Comment by wendal** [comment]
maven默认也就是javac编译

**Comment by happyday517** [comment]
是的
你用javac没有报错吗?
