### ISSUE TITLE
maplist 过滤涉及到数组的问题

### ISSUE THREAD

**Issue by jirongjun** [nutzam/nutz#1043]
以官方文档中“maplist 过滤”一节为例

```
String json = "{name:'nutz', age:12, address:[{area:1,name:'abc'}, {area:2,name:'123'}]}";
Object obj = Json.fromJson(json);

List<String> list = new ArrayList<String>();
list.add("age");
list.add("address[].area");
Object newobj = Mapl.excludeFilter(obj, list);
```

结果会是

`{name:'nutz', address:[{name:"abc"}, {name:"123"}]}`

如果这个list没有第二个add，结果会是

`{name:'nutz',address:[{area:1,name:"abc"},{area:2,name:"123"},{area:1,name:"abc"},{area:2,name:"123"}]}"`

貌似是重复了，而且address有多少个就会重复多少次。

**Comment by jirongjun** [comment]
如果第二个add的是`address[].`，就可以了。

**Comment by wendal** [comment]
@juqkai

**Comment by wendal** [comment]
@juqkai 还打算改吗?
