### ISSUE TITLE
ManyMany关联关系中需要关联多个列

### ISSUE THREAD

**Issue by xiciliu** [nutzam/nutz#1045]
3个表
Book{id,name,isbn}
Author{id,name}
BookAuthor{id,bookid,authorid,type} //type: 0, 作者; 1,译者

在Book类中创建
`               @ManyMany(from = "bookid", relation = "BookAuthor", target = Author.class, to = "authorid")
    private List<Author> authors;//此种情况，BookAuthor->type=0

```
@ManyMany(from = "bookid", relation = "BookAuthor", target = Author.class, to = "authorid")
private List<Author> translators;//此种情况，BookAuthor->type=1`
```

不能在ManyMany注解中指明type。
所以authors和translators的结果是一样的了。
即在表BookAuthor中，同一个bookid,还需要区分type列，才能找到目标authorid。

对于这个功能，是否考虑让我们更懒一点呢？

**Comment by ywjno** [comment]
其实应该要的是 where 条件

**Comment by xiciliu** [comment]
@ywjno  那有何办法吗？
