### ISSUE TITLE
建议增加Trans.clear方法

### ISSUE THREAD

**Issue by thineagle** [nutzam/nutz#1047]
在允许应用开发人员自由使用事物的前提下， 如果开发人员一旦忘记配对使用begin和commit， 回导致连接泄漏， 此时框架层无能为力， 建议增加trans.clear方法， 框架发现未配对使用的事物， 可以强制关闭连接并提醒开发人员。 参见https://nutz.cn/yvr/t/rjoki8javihdhr128bku936mge

**Comment by wendal** [comment]
已经在1.r.56中添加
