### ISSUE TITLE
NutDao支持数据库关键字作为字段名称

### ISSUE THREAD

**Issue by wendal** [nutzam/nutz#1048]
为Pojo映射时的字段名, 通过可配置的设置, 做修改

1. 强制全部字段名加包裹符号
2. 自动检测关键字,符号就加
3. 强制全部字段名大写

**Comment by GuoNing89** [comment]
为何 我这边不起作用？  加了   ·default·   插入，更新可以，但是读取  就获取不到值，不加  ··  读取可以但是 插入更新 都报错，

**Comment by wendal** [comment]
```
@Column(name="default", wrap=true)
private String XXX;
```

**Comment by wendal** [comment]
直接加·XX·是不行的
