### ISSUE TITLE
为多表join的自定义SQL提供一个内置的SqlCallback实现

### ISSUE THREAD

**Issue by wendal** [nutzam/nutz#1050]
1. 需要传入各表的Entity属性
2. 剩余字段(例如统计字段),保存在末尾的Record对象中

**Comment by wendal** [comment]
TODO 添加文档

**Comment by wendal** [comment]
操, Oracle不支持getTableName方法!!!!!

**Comment by shevawen** [comment]
看起来这个特性还没包含在某个版本里？

**Comment by wendal** [comment]
仅mysql支持的东西

**Comment by shevawen** [comment]
这个对自定义SQL有要求吧，比如两个 Entity 都有 id 字段，怎么转化？

**Comment by wendal** [comment]
oracle的话没办法的样子,只能通过别名as

**Comment by ywjno** [comment]
话说文档有了没啊

**Comment by wendal** [comment]
已经删除掉了, 用别名才能解决, 然而用别名的话, Record类已经提供了前缀->Entity/Pojo的方法

**Comment by shevawen** [comment]
那还是自己组装一下好了
