### ISSUE TITLE
优化Json性能

### ISSUE THREAD

**Issue by qinerg** [nutzam/nutz#1065]
尝试了几种Bean序列化的方式，并对比了几种Json序列化的性能，发现Nutz的Json性能提升空间还是蛮大的。
序列化有十个属性的对象，共序列化10000次，为公平起见每项测试开始前均先热身10次。结果如下：
GsonLen:346
GsonTime: Total: 265ms : [2016-06-04 18:45:10.462]=>[2016-06-04 18:45:10.727]
NutzJsonLen:340
NutzJsonTime: Total: 625ms : [2016-06-04 18:45:11.041]=>[2016-06-04 18:45:11.666]
HessianLen:383
HessianTime: Total: 94ms : [2016-06-04 18:45:11.713]=>[2016-06-04 18:45:11.807]
FastJsonLen:324
FastJsonTime: Total: 156ms : [2016-06-04 18:45:11.885]=>[2016-06-04 18:45:12.041]

**Comment by wendal** [comment]
先热身1w次然后测10w

**Comment by qinerg** [comment]
先热身1w次然后测10w的结果如下：
GsonLen:356
GsonTime: Total: 2231ms : [2016-06-04 23:11:41.816]=>[2016-06-04 23:11:44.047]
NutzJsonLen:343
NutzJsonTime: Total: 5008ms : [2016-06-04 23:11:44.999]=>[2016-06-04 23:11:50.007]
HessianLen:385
HessianTime: Total: 796ms : [2016-06-04 23:11:50.148]=>[2016-06-04 23:11:50.944]
FastJsonLen:327
FastJsonTime: Total: 374ms : [2016-06-04 23:11:51.179]=>[2016-06-04 23:11:51.553]

**Comment by wendal** [comment]
上代码吧,如果能提供pull req更好,哈哈

**Comment by qinerg** [comment]
附代码如下：

`package json;

import java.io.Serializable;
import java.util.Date;

import org.junit.Test;
import org.nutz.json.Json;
import org.nutz.json.JsonFormat;
import org.nutz.lang.Stopwatch;
import org.nutz.lang.random.R;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.serializer.SerializerFeature;
import com.google.gson.Gson;
import com.jarvis.cache.serializer.HessianSerializer;

public class JsonTest {

	private int hot = 1_0000;
	private int run = 10_0000;

	@Test
	public void nutzJsonLength() {
		User ext = getUser();
		String json = Json.toJson(ext, JsonFormat.compact());
		System.out.println("NutzJsonLen:" + json.length());
		for (int i = 0; i < hot; i++) {
			Json.toJson(ext);
		}

		Stopwatch sw = Stopwatch.begin();
		for (int i = 0; i < run; i++) {
			Json.toJson(ext, JsonFormat.compact());
		}
		sw.stop();
		System.out.println("NutzJsonTime: " + sw);
	}

	@Test
	public void hessian() throws Exception {
		User ext = getUser();
		HessianSerializer h = new HessianSerializer();
		byte[] s = h.serialize(ext);
		System.out.println("HessianLen:" + s.length);

		for (int i = 0; i < hot; i++) {
			h.serialize(ext);
		}

		Stopwatch sw = Stopwatch.begin();
		for (int i = 0; i < run; i++) {
			h.serialize(ext);
		}
		sw.stop();
		System.out.println("HessianTime: " + sw);
	}

	@Test
	public void gson() {
		User ext = getUser();
		Gson g = new Gson();
		String json = g.toJson(ext);
		System.out.println("GsonLen:" + json.length());

		for (int i = 0; i < hot; i++) {
			g.toJson(ext);
		}

		Stopwatch sw = Stopwatch.begin();
		for (int i = 0; i < run; i++) {
			g.toJson(ext);
		}
		sw.stop();
		System.out.println("GsonTime: " + sw);
	}

	@Test
	public void fastJson() {
		User ext = getUser();
		SerializerFeature feature = SerializerFeature.DisableCircularReferenceDetect;
		String json = JSON.toJSONString(ext, feature);
		System.out.println("FastJsonLen:" + json.length());

		for (int i = 0; i < hot; i++) {
			JSON.toJSONString(ext, feature);
		}

		Stopwatch sw = Stopwatch.begin();
		for (int i = 0; i < run; i++) {
			JSON.toJSONString(ext, feature);
		}
		sw.stop();
		System.out.println("FastJsonTime: " + sw);
	}

	private User getUser() {
		User ext = new User();
		ext._id = (long) R.random(10000, 1000000);
		ext.cardNum = "123131232198w983242142";
		ext.city = "lushi";
		ext.createTime = new Date();
		ext.fromType = 1;
		ext.headimg = "http://werqwrekqwjlkjqwerqwrq/cdasdfal";
		ext.homePage = "http://werqklwjrkqwenasdnfkjlashfa";
		ext.ip = "127.0.0.1";
		ext.province = "shanxi";
		ext.sex = 1;
		ext.sign = "欲带皇冠，必承其重";
		ext.updateTime = new Date();
		return ext;
	}

	public class User implements Serializable {
		private static final long serialVersionUID = 1L;

		public Long _id;
		public String real;
		public String sign;
		public Integer sex;
		public Integer fromType;
		public Integer pid;
		public Integer sid;
		public String headimg;
		public String talent;
		public String route;
		public String homePage;
		public String videoPath;
		public String intro;
		public String cardNum;
		public String province;
		public String city;
		public String starsign; // 星座
		public String ip;
		public Date createTime;
		public Date updateTime;
	}

}
`

Nutz 自带的 Json 非常方便，兼容性也比其它实现好。因为项目中大量采用了Nutz的Json做序列化方式，一时心血来潮做了下性能对比，发现了这个问题。
但 Json 的实现代码还没有深入研究，暂时还 pull 不了，呵呵。有机会一定尽力。
