### ISSUE TITLE
怎样才能使文件池中的文件能够动态分类管理呢？

### ISSUE THREAD

**Issue by wqmain** [nutzam/nutz#1067]
怎样做才能动态指定一个字符串变量作为homePath的子目录（比如由HttpServletRequest接收的参数），比如:${homePath}/news。也就是不同的文件类别想分类存储，比如新闻存在${homePath}/news目录下；政策存在${homePath}/policy目录下。
现在是在 ioc/upload.js文件中对文件池相关的 NutFilePool、UploadingContext、UploadAdaptor等做了声明，系统启动后直接注入到ioc容器中了，但是这样homePath也就直接确定了，上传的文件只能在这个目录下，而没办法分类存放。

**Comment by wendal** [comment]
这种呢, 继承UploadAdaptor, 传自定义的参数更好哦

PS: UploadAdaptor实例不可以在不同方法间共享

**Comment by wqmain** [comment]
好主意，我去试试

**Comment by wqmain** [comment]
就是想动态的分类创建子文件夹，然后文件分别上传到对应的子文件夹里，这样分类好管理

**Comment by wendal** [comment]
不过, 那是临时文件夹哦

**Comment by wqmain** [comment]
我是重新实现了FilePool，重写了Pools帮助类，目前文件的保存格式是{homePath}/yy/MM/dd/{文件名}
现在就是想不通要怎么根据request传过来的参数动态的存储在：{homePath}/{request接收的参数值}/yy/MM/dd/{文件名}

因为UploadAdapter要指定UploadingContext，UploadingContext要指定FilePool，这些都是在初始化时就确定了的，我的需求相当于要动态的变更FilePool的homePath，找不到入口哇，是我哪里想错了么？没有实现思路啊，兽总！

**Comment by wendal** [comment]
FastUploading类获取TempFile时并没有传参

所以, 只能选用ThreadLocal来传递了

**Comment by wqmain** [comment]
如果自己实现改动比较大的话，那我都不如在action中将获取到的TempFile对象重写到我想要的子路径下了，是不？这样实现反而更简单，只是这样就可惜了文件池的设计了，之前自定义FilePool、Pools等也都没啥意义了。
或者，能否在下一个版本支持annotation或request参数中自定义子目录呢？这样扩展性会更好吧？
我报个需求类的 issue，兽总在 1.r.57 版本中会实现不？^_^

**Comment by wendal** [comment]
Mvcs.getReq() 或 Mvcs.getActionContext() 应该能满足你

**Comment by wqmain** [comment]
恩，最终还是在自定义的FilePool中用 Mvcs.getReq() 接收子目录参数实现的，多谢！！！
