### ISSUE TITLE
自定义路由功能怎么实现

### ISSUE THREAD

**Issue by Wizzercn** [nutzam/nutz#1071]
比如通过一个配置文件，如：

"/sysadmin":"cn.wizzer.nutzwk.controllers.sys.LoginController.login"

路径--类方法

这样，除了类本身的 @At 映射，另外实现了自定义路由功能，

后台类可能是几层的路径 /private/sys/login ，而有时候要改变请求路径而不用改代码，这个在做前台的时候非常常用，改改配置文件就能实现。

给个实现思路或者框架本身提供支持？

**Comment by wendal** [comment]
你需要@LoadingBy注记, 覆盖原有的实现

org.nutz.mvc.impl.NutLoading.evalUrlMapping

等标准的@At处理完成后,读取该配置文件,继续插入映射添加. 或之前判断一下? any way

**Comment by Wizzercn** [comment]
具体实现需考虑动态加载，比如CMS系统的栏目自定义访问路径功能
比如配置 /news 然后可以注入系统在线生效

**Comment by zozoh** [comment]
为啥不用 
```
@At("/news/*")
public void someMethod(String path) {
     // 你想咋实现，随你
```
如果想保留原始 URL 的后缀，用
```
@At("/news/**")
public void someMethod(String path) {
     // 你想咋实现，随你
```

**Comment by Wizzercn** [comment]
没有前缀、没有限制条件，可以任意指向某个控制器方法。实际业务有这个需求。

**Comment by zozoh** [comment]
```
@At("/**")
public void someMethod(String path) {
     // 你想咋实现，随你
```

**Comment by Wizzercn** [comment]
https://github.com/Wizzercn/NodeWk/blob/master/config/routes.js 这样的

**Comment by zozoh** [comment]
```java
AtMap am = Mvcs.getAtMap();
```
这个只能读取，

你是希望开放 
```
ActionHandler.mapping 
```
对象的访问权限吧

**Comment by Wizzercn** [comment]
NutzWk 3.2.2 使用Filter 实现
