### ISSUE TITLE
@PrevUpdate  @NextUpdate

### ISSUE THREAD

**Issue by Wizzercn** [nutzam/nutz#1075]
@Prev
@Next
都是插入操作，希望提供修改、删除操作：
@PrevUpdate  
@NextUpdate
@PrevDelete 
@NextDelete

可以商量哈~

支持单条SQL、多条SQL、代码方法等

**Comment by wendal** [comment]
DaoInterceptor 已经可以解决这个问题.

**Comment by ywjno** [comment]
DaoInterceptor 相关的文档在哪？

**Comment by wendal** [comment]
@ywjno 已添加,请pull
