### ISSUE TITLE
@Prev  第一条记录 总是 null

### ISSUE THREAD

**Issue by Wizzercn** [nutzam/nutz#1082]
@Column
    @Comment("排序字段")
    @Prev(@SQL("SELECT MAX(IFNULL(location,0))+1 FROM wx_reply_news"))
    private Integer location;

第一条记录 总是 null

**Comment by Wizzercn** [comment]
Integer 类似是为了updateIgnoreNull 可以忽略空值

**Comment by wendal** [comment]
http://stackoverflow.com/questions/18013459/mysql-return-max-value-or-null-if-one-column-has-no-value

**Comment by Wizzercn** [comment]
SELECT IFNULL(MAX(location),0)+1
