### ISSUE TITLE
json转换问题

### ISSUE THREAD

**Issue by 15201230343** [nutzam/nutz#1087]
让json在转换时间问题上可以选择转换格式,可以把时间转换为时间戳
当前格式:
{"role":1,"startTime":"2016-07-12 14:14:18","endTime":"2016-07-12 14:14:18","random":"8246"}
想要的格式:
{"role":1,"startTime":1468304058114,"endTime":1468304058114,"random":"8246"}

**Comment by Wizzercn** [comment]
时间戳不是应该除以1000么，否则我还是要自己处理……@wendal

**Comment by wendal** [comment]
?到底是long还是double? 或者兼容2种?

timestamp_long --> long   1468304058114
timestamp_double --> double  1468304058.114

**Comment by 15201230343** [comment]
long

**Comment by jirongjun** [comment]
最后输出的是个字符串，不是应该是数值么？
