### ISSUE TITLE
org.nutz.dao.entity.Record的toEntity(Entity<T> en, String prefix) 结果不对

### ISSUE THREAD

**Issue by xing-kenny** [nutzam/nutz#1094]
org.nutz.dao.util.test_sql() 这个用例得到的结果是   

    ColumnName = id
    ColumnName = nm
    ColumnName = t_id
    u.getId() = 0
    u.getName() = null
    u.getTeamId() = 0
    t.getId() = 0
    t.getName() = null

就是说   
      
    String str = "select u.*,t.* from $user_table u INNER JOIN $team_table t ON u.t_id = t.id where u.nm=@name";

取得的Record 只有三个字段，且用 

     record.toEntity(dao.getEntity(SystemUser.class), "u."); 

这个方法获取不到正确的SystemUser 对象，用 
    
     record.toEntity(dao.getEntity(SystemUser.class)) 

可以得到

**Comment by wendal** [comment]
需要 xxx as a.xxx 才行

这个功能我当时是不是脑抽了...
