### ISSUE TITLE
有提供自动生成POJO的工具类么？

### ISSUE THREAD

**Issue by zicai1026** [nutzam/nutz#1103]
感觉可以提供一个工具类，自己写太繁琐了，而且容易出错

**Comment by wendal** [comment]
https://nutz.cn 分享区有

推荐做法是 Pojo 生成 表, 而不是反过来. ^_^

**Comment by ywjno** [comment]
其实也可以做，就是字段名五花八门要一一对应太累了

**Comment by zicai1026** [comment]
希望越来越好

**Comment by wendal** [comment]
另外, NutDao一直支持无Pojo方式操作数据库哦

**Comment by Wizzercn** [comment]
https://github.com/Wizzercn/NutzCodematic

NutzWk 的图形界面代码生成器，通过表生成POJO等类、页面，你可以只用POJO类，或下源码自行改造。

**Comment by zicai1026** [comment]
谢谢 @Wizzercn   我试试这个
