### ISSUE TITLE
1.r.57 IocBean初始化，存在并发安全性问题？

### ISSUE THREAD

**Issue by wqmain** [nutzam/nutz#1108]
首先我是从1.b.52直接升级到1.r.57版本出现问题的（注，又试过1.b.53版本没问题），描述如下：
Action中@Inject注入一个声明了@IocBean的Service，Action中有三个方法分别调用了该Service的业务方法，前台通过3个ajax分别且同时提交请求到后台Action这三个方法，第1个ajax请求，Service正常初始化，但第2、3个ajax请求，报NPE，控制台在方法中可以打印出来Service为null。代码结构类似：
`@IocBean
@At("/index")
public class IndexAction extends BaseAction {
    @Inject
    private IndexService indexService;

    @At("/m1")
    public void method_1() {
        indexService.m1(); //第1个到达的ajax请求，indexService正常初始化
    }

    @At("/m2")
    public void method_2() {
        indexService.m2(); //第2个到达的ajax请求，indexService为null，报NPE
    }

    @At("/m3")
    public void method_3() {
        indexService.m3(); //第3个到达的ajax请求，同样indexService为null，报NPE
    }
}`

**Comment by wendal** [comment]
@ansjsun 是不是之前那个修改的问题

**Comment by wendal** [comment]
可否给出请求时的日志, 更好的推测原因

**Comment by wendal** [comment]
1.r.57是根据name加锁, 仔细思考了一下, 不可行

1. 多个bean交叉获取lock的情况下,死锁
2. 创建op的过程加锁了,但创建对象的过程没有加锁

第一个问题无法解决,因为引用的bean无法直接推断, 按name解锁无法解决.
第二个问题, 将对象创建过程也置于锁之内可以解决

为了解决第一个问题, 必须还原全局锁

**Comment by wendal** [comment]
@ansjsun 有无更好的解决办法?

@wqmain 请测试1.r.56或在MainSetup.init方法内添加如下代码临时解决

```java
        for (String name : ioc.getNames()) {
            try {
                if (name.endsWith("Module") || name.endsWith("Action")) {
                    ioc.get(Object.class, name);
                }
            } catch (Throwable e) {
            }
        }
```

**Comment by wendal** [comment]
出错的过程是这样:

1. A线程进入NutIoc.get, op还不存在于context, 根据name得到的锁
2. A线程通过ObjectMaker生成ObjectProxy. 其中, 会把未完成的op对象放入上下文
3. B线程进入NutIoc.get, **op存在于context, 没有加锁**, 直接调用op.get, 得到未组装完成的对象
4 B线程获取对象, 但该对象尚未组装完成, 导致需要注入的属性为null, 触发NPE
5. A线程完成组装,此时对象完整, 执行操作是正常的.

**Comment by ansjsun** [comment]
不好意思..这个bug有点大了...ioc过程的确得全局锁..应该是 @wendal 改的上一个版本...是好的...当时考虑不完全...

**Comment by wqmain** [comment]
我是从1.b.52直接升级过去的，不用临时解决，暂不升级即可，另外1.b.53没有问题。
@wendal 需要我测试1.r.56吗？

**Comment by wqmain** [comment]
@wendal @ansjsun   1.b.52换成1.r.56 ，系统跑不起来，我之前提的 #1066 issue只在1.r.57中体现了，1.r.56版本中没有修复.......

**Comment by wendal** [comment]
@wqmain 麻烦你稍后试一下快照版,如果一切ok的话,我发布个1.r.57.r3

**Comment by wqmain** [comment]
@wendal 不麻烦，快照版本是这个么？http://downloads.nutzam.com/get/276c5ab230b919eff2a9288496b4c725

**Comment by wendal** [comment]
https://oss.sonatype.org/content/repositories/snapshots/org/nutz/nutz/1.r.58-SNAPSHOT/ 这里,最后一个jar

**Comment by wqmain** [comment]
@wendal 兽总，快照版本没有问题了。

**Comment by wendal** [comment]
@wqmain ok,我下午或晚上发布个1.r.57.r3
