### ISSUE TITLE
如果一个字段标注了@Prev且匹配当前数据,那么@Id应该设置为auto=false

### ISSUE THREAD

**Issue by wendal** [nutzam/nutz#1129]
```java
@Id
@Prev(@SQL("select xxx.nextval from dual", db=DB.ORACLE))
```

在Mysql运行时,应该@Id(auto=true)生效

在Oracle运行时,应该自动切换为@Id(auto=false)

**Comment by Wizzercn** [comment]
oracle本就不应该用sql实现自增长,而应该是用触发器+序列,oracle直接屏蔽掉,省的大并发数据量的时候慢,怪是nutz的问题.
