### ISSUE TITLE
关于JAVABEAN上面的@Column注解是否可以省略？

### ISSUE THREAD

**Issue by projack1** [nutzam/nutz#1131]
关于JAVABEAN上面的@Column注解是否可以省略？

由于我一个javabean有100甚至更多的字段，无论Integer，Double，Boolean和简单的String都必须写上@Column注解感觉好麻烦，能不能不写的时候就默认它有？

另外就是如果javabean的命名和数据库字段命名不一致的情况下也支持加上@Column注解修改。

**Comment by ming300** [comment]
写一个生成器,直接从数据库查询列名称,一次性生成javabean,更方便,也更省事

**Comment by ywjno** [comment]
可以考虑使用 Record 类了，连 bean 都可以不用写

**Comment by albinhdk** [comment]
我记得不需要都写@Column啊，只要实体类有@Table就行了吧
难道是我错觉？

**Comment by crskyp** [comment]
1、有必要写
2、如果代码量大，用代码生成器
