### ISSUE TITLE
NutIoc销毁对象的顺序应该可预测

### ISSUE THREAD

**Issue by wendal** [nutzam/nutz#1139]
当前的顺序,取决于HashMap的自然排序.

有一定概率会出现, 在某个bean的depose中使用NutDao,而NutDao及DataSource比它先销毁.

**Comment by wendal** [comment]
如果A依赖B, 那么 A应该被B先销毁.

严格的依赖关系不太可能推导出来,但基于从ioc取出的顺序, 反序得到depose的执行列表, 应该能满足大部分需求.

**Comment by wendal** [comment]
考虑这种情况:

A 依赖 B
C 依赖 B


先取出A    --   A
A依赖B      --  A,B
取出C       --   A,B,C

如果A,和C的depose均依赖C. 那么 无论反序还是顺序, 均无法做到B最后销毁.

**Comment by wendal** [comment]
然后, 根据现实使用的情况, Dao一般会在MainSetup中先获取一次, 所以存储的顺序是

```
$aop_XXX, NutDao, DataSource, DaoRunner, YvrModule
```

反序后

```
YvrModule, DaoRunner, DataSource, NutDao, $aop_XXX
```

虽然无法保证DataSoure在NutDao之后销毁,但应该会比Module和Service实例晚销毁.

//------------------------------------------------------------------------------------------

要是MainSetup.init中不获取Dao实例,就好变成

```
$aop_XXX, YvrModule, NutDao, DataSource, DaoRunner
```

反序之后

```
DaoRunner, DataSource, NutDao, YvrModule, $aop_XXX
```

**Comment by wendal** [comment]
所以呢, 这就引申出一个最佳实践的问题:

要么Setup.init中优先获取DataSource,JedisPool之类的底层资源

要么不要在depose中操作DataSource,JedisPool之类的底层资源

**Comment by wendal** [comment]
Ioc的对象取出过程

基本上是这样:

1. 用户代码/系统代码调用 ioc.get(A)
2. 生成A的实例, 放入ctx
3. 注入A的依赖项, 例如依赖B
4. ioc.get(B)
5. 生成B的实例, 放入ctx
6. A组装完成,触发create事件
7. 返回A实例,触发fetch事件

PS: 如果A是构造方法依赖B, 那么B会先放入ctx. 因为没有B,没法生成A的实例.

**Comment by fangoxyz** [comment]
ObjectProxy  增加一个优先级属性。优先级根据对象类型设置，销毁前对list根据优先级进行排序

Collections.sort(list, new Comparator<Object>(){   
          public int compare(Object e1, Object e2){   
        int v1 = Integer.parseInt(((Entry<String,ObjectProxy>)e1).getValue().getPY());   
        int v2 = Integer.parseInt(((Entry<String,ObjectProxy>)e2).getValue().getPY());   
        return v1-v2;   
           
    }   
});

**Comment by ywjno** [comment]
变成了跟 spring 那样的能制定加载顺序的了咩 （用 `@Order` 这个注解实现

**Comment by fangoxyz** [comment]
@ywjno 这个很科学，完美解决框架级和用户级的顺序
