### ISSUE TITLE
增加字段后，能否自动修改表

### ISSUE THREAD

**Issue by sunhai1988** [nutzam/nutz#1143]
1.在实际开发中，会经常遇到对表增加字段，如果只是增加java bean 属性，数据库也需要手动增加。
如果有
INFO  - Can not find @Column(token) in table   /view (user)  提示时，执行一句  ALTER TABLE

**Comment by Rekoe** [comment]
Daos.migration(dao, Mobile.class, true, true, false);
这个方法可以帮你解决你的问题

**Comment by sunhai1988** [comment]
嗯 谢谢！ 我看了 Daos.migration有很多个很方便的方法。可以是包路径
