### ISSUE TITLE
@ManyMany建议增加别名属性

### ISSUE THREAD

**Issue by TonyYule** [nutzam/nutz#1146]
@ManyMany建议增加别名属性 比如 多对多关系中两张主键都是ID 那么中间表应该取一个别名区分存入两张表的ID例如下面这种问题
    @ManyMany(target = App_product.class, relation = "app_prod_sale", from = "id", to = "id",key="id")
    private List<App_product> products;

**Comment by wendal** [comment]
from和to均支持       

```
中间表字段名:java属性名
```
