### ISSUE TITLE
现在的form只能支持GET与POST，可否通过隐藏input 来支持PUT\DELETE

### ISSUE THREAD

**Issue by enzozhong** [nutzam/nutz#1148]
nutz支持REST，可是只能js来实现，原生的form只能GET\POST，不知道是否可以约定一下添加
&lt;input name="__method" value="DELETE" />
然后再路由上到达@DELETE方法呢？

**Comment by wendal** [comment]
跟这个issue有点关系 #1121

**Comment by ywjno** [comment]
可以使用 https://github.com/Ifnot/RestfulizerJs 这个来实现这个功能，实际上，ruby on rails 也是用了类似的 js 来做这个处理的

**Comment by enzozhong** [comment]
这样约定一下，以后uri漂亮多了，最好在web.xml中也可以进行配置开关，默认这个特性为false，怕有些人_method有别的作用
虽说ajax可以完美胜任，还是得添加js代码

**Comment by enzozhong** [comment]
能先来一发不，恨不得现在就去改URL

**Comment by wendal** [comment]
已改为WhaleFilter实现
