### ISSUE TITLE
Daos.migration要支持Oracle和SqlServer的索引新增

### ISSUE THREAD

**Issue by wendal** [nutzam/nutz#1149]
当前实现下,启用索引自动添加的话,会抛异常

https://nutz.cn/yvr/t/pjil8oud60j58rtmkc56ss1vjr

**Comment by hzl7652** [comment]
上午试着写了一下，本来以为通过以下代码可以取得索引信息的
`                    indexRs = conn.getMetaData()
                                  .getIndexInfo(null,
                                                null,
                                                en.getTableName().toUpperCase(),
                                                false,
                                                false);
                    while (indexRs.next()) {
                        String index = indexRs.getString("INDEX_NAME");
                        _indexs.add(index);
                    }
`
但是测试 Oracle 时，与看文档时发现在当索引类型为jdbc规定的 tableIndexStatistic  时 indexRs 结果集中 INDEX_NAME 为空 看来通过 jdbc元数据取索引名称不满足
Oracle 使用 SQL 查询表的索引信息语句如下：
`SELECT * FROM user_indexes WHERE table_name='FACTORY_HEAD' 
`
别的数据库不知道了

**Comment by wendal** [comment]
嗯嗯,我先试试oracle怎么搞

**Comment by wendal** [comment]
SqlServer 似乎比较麻烦

https://msdn.microsoft.com/en-us/library/ms173760.aspx

http://stackoverflow.com/questions/1179134/how-to-get-the-index-name-from-indexid-in-sql-server-2005

**Comment by wendal** [comment]
pgsql也是挂

**Comment by tanqimin** [comment]
SqlServer 查询索引的方法：
`SELECT idx.name
FROM    sysindexes idx
JOIN    sysindexkeys idk ON idx.id = idk.id AND idx.indid = idk.indid 
JOIN    sysobjects o ON idk.id = o.id AND o.xtype = 'U'
WHERE   o.name = 'ERP_ORGANIZATION_TYPE'`
