### ISSUE TITLE
@PUT获取不到参数

### ISSUE THREAD

**Issue by enzozhong** [nutzam/nutz#1154]
**版本**
snapshot59

**配置**
ALLOW_HTTP_METHOD_OVERRIDE=true

**场景**
在fomr加入_method=put，可以正常的获取到参数
但是$.ajax,type=put,就无法获取参数

**问题由来**
当我把方法@PUT，换回@POST，$.ajax,type=post就可以正常工作了，所以考虑问题在@PUT上

**代码**
![20161022103007](https://cloud.githubusercontent.com/assets/993544/19616316/82371e24-9842-11e6-9fa8-d6ebd15cbf1d.png)

**备注**
aopToken检查req中的属性，发现req里面参数为{}，没有参数

**Comment by wendal** [comment]
不要截图!!!!!!

问题不在于@PUT, 检查ajax, type=put时的Content-Type值

**Comment by enzozhong** [comment]
Content-Type:application/x-www-form-urlencoded; charset=UTF-8
代码去哪里贴？

**Comment by wendal** [comment]
http://stackoverflow.com/questions/8032938/jquery-ajax-put-with-parameters

看来是web服务器不会解析body里面参数
