### ISSUE TITLE
提个Json参数需求

### ISSUE THREAD

**Issue by Wizzercn** [nutzam/nutz#1155]
1、POJO类可以定义Json字段：
    @Column
    @Comment("JSON")
    @ColDefine(type = ColType.JSON)
    private Json iaMjson;

数据库存的是大字段，如TEXT

2、页面直接传递字符串，后台获取Json参数：
    @Param("spec_values") Json spec_values

**Comment by ywjno** [comment]
你让数据库原生支持json类型的情何以堪

**Comment by wendal** [comment]
如果你写的 "Json" 类是一个正常的Pojo,那么, 一直都支持的. 已添加示例testcase
