### ISSUE TITLE
建议Mapl的excludeFilter和includeFilter加通配符支持

### ISSUE THREAD

**Issue by songofhawk** [nutzam/nutz#1165]
Mapl是一个非常好用的类, 可以把Json导入的数据直接缓存在内存中, 甚至不需要做类的Mapping, 就可以对数据做基本操作, 不过有时需要对数据做批量的精简处理, 而数据又是map类型的, 这时使用excludeFilter是自然的选择, 但由于path语法不支持通配符, 就只能自己遍历处理了...

例如, 原始数据为:
```
{"person1":{"name":"wang", "age":18 },"person2":{"name":"li", "age":20}), 
```
想把它转换为:
```
{"person1":{"name":"wang"},"person2":{"name":"li"})
```

希望能用这样的语法:

```
		List<String> list = new ArrayList<String>();
		list.add("*.age");
		return Mapl.excludeFilter(obj, list);`

```

**Comment by ywjno** [comment]
可以使用 java8 的 lambda 做这个处理

**Comment by wendal** [comment]
ant-like 匹配的实现, 一直没人写...

**Comment by wendal** [comment]
mapl这个库原本是@junkai 维护,但已经很久没见人了, 在没有后续维护者的情况下, 只能关闭.
