### ISSUE TITLE
自定义ActionFilter中接收不到 Request.create(“http://192.168.1.111/xxx”, METHOD.POST, params) 中的POST参数

### ISSUE THREAD

**Issue by wqmain** [nutzam/nutz#1181]
写单元测试类向服务端action发起请求，代码如下：
Map<String, Object> params = new HashMap<String, Object>();
params.put("t", "abcdefg");
Request request = Request.create(“http://192.168.1.111/xxx”, METHOD.POST, params);
PostSender sender = new PostSender(request);
Response resp = sender.send();
final String result = resp.getContent();

在自定义ActionFilter的match方法中，可以正常拦截这个URL，但 req.getParameter("t") 的结果为null
用Fiddler软件模拟了POST请求，则可以正常获取参数，估计是Request.create这处的问题，也有可能是我的写法不对？

兽总，你怎么看？

配置方面肯定没问题，MainModule上已加上注解：
@Filters({
	@By(type=TestFilter.class)
})

自定义ActionFilter部分代码如下：
@Override
public View match(ActionContext context) {
	HttpServletRequest req = context.getRequest();
	final String token = (String)req.getParameter("t");
	System.out.println(“t=” + t);
}

**Comment by wendal** [comment]
把header打印一下看看

**Comment by wqmain** [comment]
@wendal 

以下是自定义ActionFilter中打印的Header的所有内容：
accept-language : en-US,en,zh,zh-CN
accept-charset : ISO-8859-1,*,utf-8
accept-encoding : gzip,deflate
user-agent : Nutz.Robot
accept : text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;
cache-control : max-age=0
host : 192.168.1.111:8080
connection : keep-alive
content-type : application/x-www-form-urlencoded
content-length : 0

**Comment by wendal** [comment]
content-length : 0

**Comment by wqmain** [comment]
@wendal 

用Fiddler模拟POST请求就可以，URL后加参数 POST方式发送也可以，http://192.168.1.111/xxx?t=abcdefg
用Map作为参数调用Request.create就不行......

**Comment by wendal** [comment]
什么版本? 完整代码贴一下

**Comment by wqmain** [comment]
@wendal  
兽总，抱歉！  我自己写错了......  Close或Delete掉吧

**Comment by wendal** [comment]
哦
