### ISSUE TITLE
@Many 通过非主键关联查询数据

### ISSUE THREAD

**Issue by Wizzercn** [nutzam/nutz#1183]
两张表：
class A{
    String id
    String sku
    @Many(target = B.class, field = "sku", key = "sku")
    List<B> bList;
}

class B{
    String id
    String sku
}

需求：
可以通过 fetchLinks查询关联表，又不是@ManyMany关系，不需要中间表

 List<A> list = dao.query(A.class, cnd);
 dao.fetchLinks(list, "bList");

但执行的时候，sql语句还是通过A表的主键，去查B表，，不知道算需求还是bug……

ps：示例代码，不要纠结能否执行……

**Comment by wendal** [comment]
像是bug

**Comment by Wizzercn** [comment]
@wendal 额

**Comment by Wizzercn** [comment]
这要带到61的节奏..

**Comment by wendal** [comment]
其实是 #799 导致的问题
