### ISSUE TITLE
建议在NutMap类添加几个方法

### ISSUE THREAD

**Issue by mylike** [nutzam/nutz#1186]
在做微信消息转发到其它平台的时候感觉不方便，建议在NutMap类添加几个方法
toXml
toJson
loadXml
loadJson
toXmlString
toJsonString
loadXmlString
loadJsonString
望采纳

**Comment by ywjno** [comment]
直接用 [nutzwx](https://github.com/nutzam/nutzwx) 就好了

**Comment by mylike** [comment]
nutzwx转发消息在handle中 发送 无法直接获取原始信息 接收中无法直接转成Wxoutmsg 
再说这个需求 也会在其它地方需要 比如 在数据库中存xml字符串或json串 这样可以直接load进来

**Comment by ywjno** [comment]
不要把 nutmap 当成万能类啊，应该自己继承一个实现这些功能

**Comment by wendal** [comment]
应该是为WnInMsg和WnOutMsg添加一个raw属性, 存储原始数据

**Comment by wendal** [comment]
fixed in https://github.com/nutzam/nutzwx/commit/ebecc6c4425f4affd450866dc0e68fa0b6ba2e5b
