### ISSUE TITLE
提一个Record的大小写需求

### ISSUE THREAD

**Issue by wangsenhehe** [nutzam/nutz#1189]
为啥Record的里面的字段名称都是小写，这让我们和安卓对接的时候很费经，能不能解决一下这个问题。

**Comment by ywjno** [comment]
举个例子

**Comment by wendal** [comment]
想想

**Comment by wangsenhehe** [comment]
举个列子，使用多表查询返回的类型是Record，但是Record里面的字段名称全部都变成小写了，
我们和安卓对接接口的时候，安卓要求是驼峰，这就比较麻烦了：

**Comment by ywjno** [comment]
自己写一个Pojo.java如下
```java
@Column("this_is_a_pan")
private String thisIsAPan
```

得到 record 之后，用 `Json.toJson(record.toPojo(Pojo.class))`

以上代码请使用快照版本
