### ISSUE TITLE
模糊查询小坑

### ISSUE THREAD

**Issue by albinhdk** [nutzam/nutz#1202]
源码位置：Exps.class Line：110-112  Nutz版本1.59
re1 = like(name, values1.substring(1, values1.length() - 1));
re1.left(values1.substring(0, 1));
re1.right(values1.substring(values1.length() - 1, values1.length()));
如果模糊查询传入的关键字长度超过1，则不会用%包裹，导致模糊查询失败。

言下之意，如果自己加上%的话，是没问题的。

所以，文档至少需要一点点更新？

**Comment by zozoh** [comment]
超过 1 ？

**Comment by albinhdk** [comment]
String values1 = value.toString();
Like re1;
if(values1.length() == 1) {
   re1 = like(name, values1);
} else {
  re1 = like(name, values1.substring(1, values1.length() - 1));
  re1.left(values1.substring(0, 1));
  re1.right(values1.substring(values1.length() - 1, values1.length()));
}

这是比较完整的源代码：
如果不手动设置left和right，就包裹%。
