### ISSUE TITLE
腾讯云Mysql数据库被识别为DB2

### ISSUE THREAD

**Issue by kimz** [nutzam/nutz#1210]
腾讯云Mysql数据库实例dbName为mysql::nutz_jdbc::5.6.28-cdb20160902-log, JdbcExpertConfigFile里面的experts成员为无序map，有可能被db2.*正则匹配到导致出错

![mysql db2](https://cloud.githubusercontent.com/assets/974100/22617190/6a1ca99e-eaf9-11e6-8d62-f1e972aabcf0.png)

**Comment by Wizzercn** [comment]
没有吧

**Comment by wendal** [comment]
版本号是? 新版应该是有序的

**Comment by wendal** [comment]
找到原因了

**Comment by wendal** [comment]
老版本的解决办法:

1. 修改nutz_jdbc_expert.js 删除mysql之外的key
2. 在dao.js中的dao的fields 添加 expert : "mysql",
