### ISSUE TITLE
国际化匹配无文件夹的形式

### ISSUE THREAD

**Issue by albinhdk** [nutzam/nutz#1211]
目前Nutz的国际化，是约定了《文件夹+properties》的形式，但是比如Idea这样的IDE，它貌似只有放在一起的两个国际化文件，才能被其插件识别，所以希望能增加《一个文件夹+多个国际化文件》，只是按照xxx_en.properties或者xxx_cn.properties这种解析规则。

**Comment by Wizzercn** [comment]
不是很好的建议。我用的就是IDEA。
