### ISSUE TITLE
Module类没能继承父类的@At方法

### ISSUE THREAD

**Issue by wendal** [nutzam/nutz#1212]
```java
public class BaseAction {
   @At
   public void sayhi(){}
}

@At("/abc")
public class AbcAction extends BaseAction{}
```

关联提交: https://github.com/nutzam/nutz/commit/8dd7c16a60316e981b43a9aa3ab5e554e3956722

**Comment by happyday517** [comment]
这个feature感觉有问题，这样设计，子类只能无条件接受所有父类@At，感觉暴露了不必要的接口出去
而如果按改动之前的设计，要满足这样的要求，仅仅需要在子类中复写父类方法即可，像下面这样
``` java
public class BaseAction {
   @At
   public void sayhi(){
   // 这里可能有一些通用实现逻辑
   }

   @At
   public void saybye() {}
}

@At("/abc")
public class AbcAction extends BaseAction{
   @Override
   public void sayhi(){} // 子类复写即可，父类的@At在这里生效
   // 子类没有复写saybye 方法，所以 /abc/saybye 没有映射
}
```

需要暴露什么接口，还是由子类控制比较好，父类仅仅提供模板和一些通用实现即可

不知道大家怎样看？ @wendal @zozoh

**Comment by happyday517** [comment]
我看了下引发这个改动的相关 [帖子](https://nutz.cn/yvr/t/1s4url6cb4g6iojmg8e3varduj)
描述部分是错的，不是使用者描述错了，就是 @wendal 理解错了

1.b.53版本的Loadings源码长 [这样的](https://github.com/nutzam/nutz/blob/1.b.53/src/org/nutz/mvc/impl/Loadings.java)，
都是直接取当前method上的At注解，不可能有继承功能

希望能恢复上一个版本的实现逻辑

**Comment by zozoh** [comment]
同意 @happyday517  的建议
还是由子类控制好一点

我自己都是在父类直接提供 protected 的方法，子类调用
所以从来没遇到过这个问题 :P

是不是在社区里做个投票呢？

**Comment by ywjno** [comment]
感觉这只是同名方法，并没有功能上的用处

莫非写了Override之后，子类的改路由功能跟父类的代码一致而不用写方法体了么

**Comment by zozoh** [comment]
没懂

**Comment by ywjno** [comment]
```java
public class BaseAction {
   @At
   public void sayhi(){
   // 这里可能有一些通用实现逻辑
   }

   @At
   public void saybye() {}
}

@At("/abc")
public class AbcAction extends BaseAction{
}
```

这样写不就是要 `/sayhi` 跟 `/abc/sayhi` 是一样的功能么


```java
public class BaseAction {
   @At
   public void sayhi(){
   // 这里可能有一些通用实现逻辑
   }

   @At
   public void saybye() {}
}

@At("/abc")
public class AbcAction extends BaseAction{
   @Override
   public void sayhi(){}
}
```

这样写不就是 `/sayhi` 跟 `/abc/sayhi` 是要实现不同的功能，但是不想再AbcAction#sayhi方法上写 `@At` 注解

所以我完全没看懂他之后的那个做法是打算干什么

**Comment by happyday517** [comment]
举个栗子，一般的所谓企业级开发，一堆crud代码，可以简化成这样：
```java
// 父类
public class Base<T> {
  @Inject Dao dao;
  
  @GET
  @At("/?")
  protected T get(String str) {
      return dao.fetch(str);
  }

  @POST @At('/')
  protected void create(T obj) {
    dao.fastInsert(obj);
  }
  // 省略一些
}

// 子类
@At('/user')
public class UserAction extends Base<User> {

  @Override
   public User get(String str){
      return super.get(str)
   }
  
   // 子类需要什么，就复写什么，复写的会暴露在外
   // 父类相当于一个Restful模板，但具体暴露什么接口由子类决定
}

`

**Comment by ywjno** [comment]
你需要的是一个父类而不是模块，也就是说这个父类跟路由没关系

**Comment by happyday517** [comment]
有关系，父类的method上的`@At`都是生效的
只是父类class上没有`@At`，class级别的`@At`由子类决定

**Comment by happyday517** [comment]
这个功能初衷在[这里](https://github.com/nutzam/nutz/issues/1002)
#1212 修改后，打破了原本的初衷
子类必须全盘接受所有的父类`@At`

**Comment by ywjno** [comment]
所以我才在那个 issue 里面写“路由还要继承碉堡了”

**Comment by happyday517** [comment]
> 你需要的是一个父类而不是模块，也就是说这个父类跟 restful 没关系
> 你可以在父类里面写各种 rest 的操作，但是子类写了 @At 的才能成为入口函数，跟这个修改没什么关系

rest操作写父类里，路由的一部分也在父类里，因为RESTful的路由和操作基本都是固定的
唯一区别就是资源，而资源可以由子类定义

子类不是写了`@At`才能成为入口函数，子类是复写了父类rest方法的方法，才是入口函数
当然子类也有自己的入口函数，并非继承自父类的

**Comment by ywjno** [comment]
如果用了 `scanPackage = true` 方式来扫描的话，只要有类包括了一个以上的 入口函数 将被认为是模块类

所以 子类写了@At 的话他就是 `模块`，而不需要复写了父类rest方法的方法才成为 `模块`，除非你用的是单独指定类名的方式手写一堆类

**Comment by happyday517** [comment]
和scanPackage = true 无关
问题就是当子类继承父类时，什么规则会被映射为入口函数

我期望的是，只有当子类override的父类带At的，才会映射，路径是 /子类类At路径/父类At路径

不要像现在这样
子类只要继承了父类，父类的所有`@At`在子类的路由作用空间内都自动加了映射
···
public class BaseAction {
   @At
   public void sayhi(){}

   @At
   public void saybye()
}

@At("/abc")
public class AbcAction extends BaseAction{
  // 我想sayhi,saybye，ok没问题
}
@At("/def")
public class DefAction extends BaseAction{
   // 我不想sayhi  但无法禁止
}
···

像这样，所有继承了BaseAction的类，都会有一个sayhi的映射，且没有机制禁止这一行为

**Comment by zozoh** [comment]
不要在这里讨论了，这个问题已经关闭了，都在  #1337 里讨论吧
