### ISSUE TITLE
关于JsonView的一个Bug: nullAsEmtry参数无效

### ISSUE THREAD

**Issue by htgylzhq** [nutzam/nutz#1213]
BUG描述：`@Ok("json:{ignoreNull:false,nullAsEmtry:true}")` 这种写法，nullAsEmtry 参数无效。
原因：`org.nutz.json.JsonFormat#clone` 中缺少一行：`jf.nullAsEmtry = this.nullAsEmtry;`

**Comment by Rekoe** [comment]
fixed
