### ISSUE TITLE
Strings.isEmail()规则不完整

### ISSUE THREAD

**Issue by albinhdk** [nutzam/nutz#1215]
Strings.isEmail("admin1216@1..qq.c.om")

是true

看了源码：

 if (Strings.isBlank(account) || Strings.isBlank(host) || host.indexOf('.') < 0) throw ...

关键是host，必须是合法的url，只判断没有.的情况，没有考虑多个点挨在一起的情况。

**Comment by wendal** [comment]
得找个彪悍的正则表达式

**Comment by ywjno** [comment]
https://github.com/hibernate/hibernate-validator/blob/master/engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/hv/EmailValidator.java, 看下这个？

**Comment by wendal** [comment]
@ywjno 你来改一下?

**Comment by zozoh** [comment]
用这个？

`^[0-9a-zA-Z_.-]+@[0-9a-zA-Z_-]+[.][a-z]+$`

**Comment by howe** [comment]
用了个
^([a-zA-Z0-9]*[-_]?[a-zA-Z0-9]+)*@([a-zA-Z0-9]*[-_]?[a-zA-Z0-9]+)+[\\.][A-Za-z]{2,3}([\\.][A-Za-z]{2})?$

**Comment by ywjno** [comment]
找到这个 `(?:|\s)[-a-z0-9_.]+@(?:[-a-z0-9]+.)+[a-z]{2,6}(?:\s|$)`
