### ISSUE TITLE
and和or同时用,并且OR里面的有多个条件跟and里面的属于并且关系

### ISSUE THREAD

**Issue by strictnerd** [nutzam/nutz#1218]
例如：      
 Criteria cri = Cnd.cri();
       cri.where().andEquals("type", logType);
       cri.where().andLike("content", '%' + search + '%').orLike("name", '%'+search+'search');

其中类似于sql中的WHERE (name='wendal' OR name='zozoh') AND age<40

**Comment by wendal** [comment]
需要用到Cnd.exps

```java
cri.where().and(Cnd.exps("content", "like", '%' + search + '%').or("content", "like", '%'+search));
```

https://nutz.cn/yvr/t/ocpcopfm1mgooq6otb45ial0p6

另外,提问请到 https://nutz.cn . github issue主要用于报bug和提功能需求

**Comment by strictnerd** [comment]
好的，以后到论坛去提问题。
