### ISSUE TITLE
NutDao是否需要提供一个统计表数量的方法呢?

### ISSUE THREAD

**Issue by wendal** [nutzam/nutz#1219]
例如统计数据库里面有多少张表

**Comment by albinhdk** [comment]
有这么一种需求：
我通常判断某个核心表是否存在（dao.exist("tabName"))来判断是否是系统初始化，然后可以执行sql初始化数据。
但是如果项目数据敏感，有时候，也许是误操作，或者物理错误（停电），导致这个核心表丢失，那么初始化可能导致一些关键数据丢失。虽然这种几率很小，但并不表示没有。
所以，判断某个库里是否有表就显得很有必要了。

**Comment by Wizzercn** [comment]
@albinhdk dao.exists() 有方法啊

**Comment by Wizzercn** [comment]
Sqls.create("SELECT table_name FROM information_schema.TABLES WHERE table_name like 'sys_log_2%';")

自定义sql可以实现

**Comment by albinhdk** [comment]
对Mysql而言
SELECT count(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA='dataBaseName'
就可以了
完整代码如下：

> Sql tableNumSql = Sqls.create("SELECT count(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA='dataBaseName'");
> tableNumSql.setCallback(Sqls.callback.integer());
> dao.execute(tableNumSql);
> int tableNum = tableNumSql.getInt();

不过这和题目不冲突。
