### ISSUE TITLE
Avatar.createAvatar默认方法生成中文头像异常

### ISSUE THREAD

**Issue by howe** [nutzam/nutz#1222]
测试代码 

```java
ImageIO.write(Avatar.createAvatar("武佩文"), "JPEG", new File("d:/1.jpeg"));
```

![](http://p1.bpimg.com/567571/771330d42c845b8c.png)

英文测试无问题

**Comment by pangwu86** [comment]
@howe jpg格式的也修正了，会根据传入颜色自动设定图片类型

**Comment by howe** [comment]
@pangwu86 不传颜色跟类型 是不是默认PNG 传颜色默认成啥 哈哈

**Comment by pangwu86** [comment]
实际是按照传入的颜色做的判断, 带有alpha值的就是png，没有的就是jpg

1. Avatar.createAvatar("pw") 
默认传入的是 #FFF, #000 没有alpha，格式为jpg

2. Avatar.createAvatar("武佩文", 256, null, null, "微软雅黑", 0, 1)
默认传入 null， null，会被替换为默认值 #FFF, #000，所以也是jpg

3. Avatar.createAvatar("武佩文", 256, "rgba(255,0,0,0.3)", null, "微软雅黑", 0, 1)
因为文字颜色被设置为 rgba(255,0,0,0.3)， 带有alpha通道值了， 所以是png

**Comment by pangwu86** [comment]
jpg与png的最大区别也就是是否可以有透明度(alpha), 所以这里改成了根据颜色去判断

**Comment by howe** [comment]
666 可以去把 字体名字打个配置文件 等出r.61了 哈哈 妇女节快乐
