### ISSUE TITLE
Nutz增强的多表关联查询实现

### ISSUE THREAD

**Issue by aaronlu1985** [nutzam/nutz#1224]
- **场景：**在前端grid中需要显示关联表某些字段的数据，grid实现了分页并且关联表的字段可以作为查询条件
- **需求：**可以定义相关的方法实现上述场景的功能，包括query和count，在POJO中最好不要再有额外的属性定义开销，对POJO的关联对象属性进行封装，还要考虑下grid中关联对象中属性的查询条件的封装要求。
- **现状：**目前的query方法只能查询已知实体（Table或View），在POJO中定义的关联实体对象如果需要加载对象属性，可以通过fetchLink或queryWithLinks，但无论是查询效率还是整体实现场景需求都存在一定问题，但类似场景也是开发过程中经常碰到的。当然是可以定义视图去解决上述问题，但是如果是简单的一些关联查询还是不建议在数据库层面建立视图，如果在Table中定义了View也是了累赘，其实无论是fetch还是query都是查的视图，有的时候并不需要查视图。单独定义一个View也增加了代码的维护量。

**Comment by wendal** [comment]
额,为啥close了呢?
