### ISSUE TITLE
El表达式针对空值的处理

### ISSUE THREAD

**Issue by projack1** [nutzam/nutz#1229]
比如我有这么一个表达式：

String val ="小王今年user.age岁，他工作在user.company。";
假如company是空值，调用Lang.context(user)生成context后，就没有company属性了，那么调用El.val(context,val)的时候就会报异常

能否输出这样的结果：
小王今年28岁，他工作在null(或者空白字符)。

**Comment by wendal** [comment]
用双叹号解决

```java
"!!(obj.pet.name) == null"
```

**Comment by wendal** [comment]
是不是还得支持默认值呢... 还得想办法
