### ISSUE TITLE
@Fail支持自定义view需求

### ISSUE THREAD

**Issue by crskyp** [nutzam/nutz#1234]
要解决的需求：部分action抛出异常时，返回json字符串，用哪个方案好
1、添加自定义注解，有自定义注解的action返回json字符串，这时还需要自定义FailProcessor类
2、通过@Fail的value值解决，这时框架还需要做些，可能需要修改View和ViewMaker

**Comment by wendal** [comment]
en

**Comment by miniyuan** [comment]
没看懂，怎么解决的？

**Comment by wendal** [comment]
自定义View和ViewMaker就是了

**Comment by miniyuan** [comment]
回复的好快
主模块上@Views 怎么个格式，文档里没有找到？

**Comment by wendal** [comment]
看@Views的javadoc

**Comment by wendal** [comment]
答疑一般都在 nutz.cn , 这里是提需求/报bug的
