### ISSUE TITLE
dao.fetch/dao.query按字段取出的没有生效

### ISSUE THREAD

**Issue by wendal** [nutzam/nutz#1235]
```java
dao.fetch("t_pet", null, "id,name");
```

理应输出的SQL是

```sql
SELECT name,id FROM t_pet  LIMIT 0, 1 
```

实际输出的sql是

```sql
SELECT * FROM t_pet  LIMIT 0, 1 
```

**Comment by Wizzercn** [comment]
有的地方是 "id,name"  有的地方是正则，比如fetchLinks  是"^(a|b)$"

不知道dao的操作传值是否可以统一一下规范，另外文档上说明示例一下？

**Comment by wendal** [comment]
你来加一下注释?

**Comment by Wizzercn** [comment]
摸不清哪些地方传正则还是什么，我都搞不清楚，何况那些初学者了...

**Comment by zozoh** [comment]
一般来说，如果 fetch 的是 POJO，那么都会是正则，因为可以枚举 POJO 的映射字段来判断。
如果是 

```
Record fetch(String tableName, Condition cnd, String fields);
```

由于不知道表结构，所以只能是字段名，不过其实这个 `String fields` 改成 `String ... fields` 更合理
