### ISSUE TITLE
属性为BigDecimal时创建数据库表字段不正确的错误

### ISSUE THREAD

**Issue by ywjno** [nutzam/nutz#1237]
当我的entity的属性如下时
```
    /** 房价 */
    @Column
    @ColDefine(type = ColType.FLOAT, width = 9, precision = 0)
    private BigDecimal price;

    /** 面积 */
    @Column
    @ColDefine(type = ColType.FLOAT, width = 3, precision = 2)
    private BigDecimal area;
```
数据库中生成相关语句为
```
	`price` FLOAT NULL DEFAULT NULL,
	`area` DECIMAL(3,2) NULL DEFAULT NULL,
```

但是我的 `price` 字段却还是希望设置成 `DECIMAL(9,0)` 的类型。
如果想要生成这样的数据库字段的话还需要自己添加 `customType = "DECIMAL"`，感觉有点不太智能。

而这时候，如果 `area` 字段添加上 `customType = "DECIMAL"` 的话，生成语句变成了
```
	`area` DECIMAL(10,0) NULL DEFAULT NULL,
```
感觉在生成 `area` 字段的时候使用了上一个字段的信息，而且这 DECIMAL 的位数也不对啊

**Comment by wendal** [comment]
那你想怎么改...

**Comment by ywjno** [comment]
所以 BigDecimal 我都用 `customType = "DECIMAL(9,0)"`
