### ISSUE TITLE
适配参数不对

### ISSUE THREAD

**Issue by chinagz** [nutzam/nutz#1252]
@At("/?")
    @Ok("json")
    @GET
    public Object getUserInfo(String custPhone) {
        log.info("获取用户信息：" + custPhone);

        User user = userApiService.getUserInfoByPhone(custPhone);

        if (user == null) {
            log.info(custPhone + "用户信息：不存在");
            return Result.error(404, "对象不存在");
        } else {
            log.info("返回用户信息：" + user.toString());
            return Result.success("ok", user);
        }

    }

String url = "http://localhost:8080/jncti-api/open/api/users/218.25.185.47
custPhone 接收到的是　218.25.185

**Comment by ywjno** [comment]
看来最后的这东西当成是文件扩展名了，要不你用 get 方式提交？

**Comment by wendal** [comment]
末尾加个反斜杠就好了

**Comment by chinagz** [comment]
恩加个反斜杠就好使了
