### ISSUE TITLE
Daos.migration 在遇到 ManyMany 注解时生成的表不正确

### ISSUE THREAD

**Issue by ywjno** [nutzam/nutz#1254]
貌似 `ManyMany` 属性的话现会运行 `AbstractJdbcExpert` 类的 `createRelation` 方法，然后再执行 `Daos` 类的 `migration` 方法，这时候即使 POJO 里面写了 `@Id` 注解，也无法给该表生成主键

**Comment by wendal** [comment]
自己写个testcase提交一下看看

**Comment by ywjno** [comment]
提交了， 3d58757fed

**Comment by wendal** [comment]
我跑了一下,能pass啊

**Comment by ywjno** [comment]
是能 pass，你再看看logger输出的表定义，或者直接上数据库看表结构

**Comment by wendal** [comment]
我知道你说啥了,中间表

**Comment by ywjno** [comment]
是的，中间表生成不正确

**Comment by wendal** [comment]
办法就是先主动建中间表的pojo咯

**Comment by ywjno** [comment]
要是传入 target 的话会先根据那个 POJO 生成表么

**Comment by wendal** [comment]
先调用dao.create, 然后再调用Daos.createTableInPackage

**Comment by ywjno** [comment]
不能在 createRelation 方法里面进行处理么

**Comment by wendal** [comment]
我倒是想在createTableInPackage里面处理,排序一下
