### ISSUE TITLE
@Many的问题

### ISSUE THREAD

**Issue by benxincaomu** [nutzam/nutz#1255]
dao中缺少queryLink()方法，当最终返回结果为List<Master>时，需要在程序中遍历进行多次查询。

**Comment by wendal** [comment]
fetchLinks可以传List的

**Comment by benxincaomu** [comment]
fetchLinks只能提供一个对象的级联。一个Master有2只宠物，fetchLinks可以满足。但是如果有3个Master各有N只宠物，目前只能够手动循环去进行了

**Comment by ywjno** [comment]
这样不行么

```
List<Master> masterList = dao().query(Master.class);
dao().fetchLinks(masterList, "pets");
```

**Comment by benxincaomu** [comment]
@ywjno 
dao.fetch(advertisingList,"advertisingAttributes")
我这样的写的时候会有编译错误的。

**Comment by benxincaomu** [comment]
@ywjno 竟然可以这样。受教了

**Comment by Wizzercn** [comment]
话说nutzshop里，商品的分类、类型、规格等关联表，都是通过上上楼的方式，节省了N多代码量
