### ISSUE TITLE
Images工具类能否加上水印等功能？

### ISSUE THREAD

**Issue by Wizzercn** [nutzam/nutz#1262]
1、需求：给图片指定位置加上水印（文字或图片）的功能；
2、等比缩放的方法zoomScale，有没有考虑到长宽是奇数除不尽导致缩放图变形的问题？

**Comment by howe** [comment]
你应该at胖五

**Comment by Wizzercn** [comment]
@pangwu86

**Comment by pangwu86** [comment]
哦 me想想怎么实现

**Comment by pangwu86** [comment]
@Wizzercn 你说的问题2 就是1像素的问题吧 变形肉眼也基本看不出来吧

**Comment by pangwu86** [comment]
等待文档的更新 #1269

**Comment by Wizzercn** [comment]
@pangwu86 问题2，实际项目，特别是电商网站项目表现的很明显，看起来很别扭呢，你要是做过电商项目就知道了客户的眼睛容不得沙子..- -

**Comment by pangwu86** [comment]
@Wizzercn 发个图给me，把你调用的代码贴下 me测试下

**Comment by Wizzercn** [comment]
@pangwu86 是这样的，比如商城要求的图片尺寸是 300*500，然后生成缩略图、列表图，都是等比压缩，但客户的美工可能提供的是 450*500，等比压缩就变形了

**Comment by Wizzercn** [comment]
@pangwu86 水印图可以加图片水印，也可以加文字水印的

**Comment by pangwu86** [comment]
450x500 压缩到 300x500 ？ 这还叫等比压缩？ 明显分辨率不一样吧

**Comment by pangwu86** [comment]
加图片水印做好了 文字稍后再做

**Comment by Wizzercn** [comment]
@pangwu86 那增加个方法，非等比压缩，自动补充指定颜色的背景，变成目标尺寸？

**Comment by ywjno** [comment]
貌似现在 Images.zoomScale 就能满足你的要求啊

**Comment by pangwu86** [comment]
现在的接口就是通过制定颜色填充的

![image](https://cloud.githubusercontent.com/assets/326471/26483114/f56edce4-421d-11e7-91e9-ab4a664c036e.png)
