### ISSUE TITLE
Nutz 需要一个自动侦测运行效率机制

### ISSUE THREAD

**Issue by zozoh** [nutzam/nutz#1266]
需要在动作链里面插入监控入口函数入点出点的监控机制

1. 一条数据记录入口函数的入点和出点
2. 一个抽象接口保存数据记录
3. 动作链开始，就创建数据记录，进入入口函数前填充时间，离开后再填充时间
4. 数据记录实例应该与 Request 或者 ThreadLocal 关联

嗯，就这些

**Comment by wendal** [comment]
考虑放在nutzmore里面 ^_^
