### ISSUE TITLE
nutz 1.r.61 版本由于JarResourceLocation方法的内部实现导致在 jdk6 环境下启动报错（jdk7正常）

### ISSUE THREAD

**Issue by wqmain** [nutzam/nutz#1270]
tomcat启动时控制台报错如下：
严重: Exception starting filter nutz
java.lang.IncompatibleClassChangeError: Class sun.net.www.protocol.jar.URLJarFile does not implement the requested interface java.io.Closeable
	at org.nutz.lang.Streams.safeClose(Streams.java:392)
	at org.nutz.resource.impl.JarResourceLocation.<init>(JarResourceLocation.java:82)
	at org.nutz.resource.Scans.init(Scans.java:93)
	at org.nutz.mvc.config.AbstractNutConfig.<init>(AbstractNutConfig.java:43)
	at org.nutz.mvc.config.FilterNutConfig.<init>(FilterNutConfig.java:15)
	at org.nutz.mvc.NutFilter._init(NutFilter.java:89)
	at org.nutz.mvc.NutFilter.init(NutFilter.java:69)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:298)

1.r.58 版本就不会报错，于是比对了两个版本的代码，发现JarResourceLocation方法内部实现不同（1.r.58用的是ZipInputStream读取的jar文件，1.r.61用URLJarFile读取的，而从报错信息也能知道，URLJarFile确实没有实现java.io.Closeable接口，导致Streams.safeClose的时候抛异常），如下：
1.r.58的方法实现源码：
public JarResourceLocation(String jarPath) throws IOException {
        this.jarPath = ResourceLocation.getJarPath(jarPath);
        **ZipInputStream zis = null;**
        try {
            **zis = Scans.makeZipInputStream(jarPath);**
            ZipEntry ens = null;
            while (null != (ens = zis.getNextEntry())) {
                if (ens.isDirectory())
                    continue;
                names.add(ens.getName());
            }
        }
        catch (Throwable e) {
            throw Lang.wrapThrow(e);
        } finally {
            Streams.safeClose(zis);
        }
    }

1.r.61的方法实现源码：
public JarResourceLocation(URL url) throws IOException {
        JarURLConnection jarConn = null;
        **JarFile jf = null;**
        try {
            **this.uri = url.toURI();
            jarConn = (JarURLConnection) new URL(uriJarPrefix(url.toURI(), "!/")).openConnection();
            jf = jarConn.getJarFile();**
            Enumeration<JarEntry> ens = jf.entries();
            while (ens.hasMoreElements()) {
                JarEntry en = ens.nextElement();
                names.add(en.getName());
            }
        }
        catch (Throwable e) {
            e.printStackTrace();
        }
        finally {
            Streams.safeClose(jf);
        }
    }

**Comment by wendal** [comment]
换 1.r.61.r2

**Comment by wendal** [comment]
嗯嗯,分析得很到位, 问题在1.r.61.r2已经修复了

**Comment by wqmain** [comment]
兽总V5啊   原来在1个多月前就已修复了。。。
