### ISSUE TITLE
Images.zoomScale 不知道算不算bug的一个bug

### ISSUE THREAD

**Issue by Wizzercn** [nutzam/nutz#1274]
这一行正常：
Images.zoomScale("C:/test.jpg", "C:/test_s.jpg" , 120, 120, Color.GRAY);

这一行生成0KB文件：
Images.zoomScale("C:/test.jpg", "C:/test.jpg_s" , 120, 120, Color.GRAY);

**Comment by wendal** [comment]
检测不到目标文件的编码格式
