### ISSUE TITLE
Exps 的 inSql/inStr/inInt 等方法传入值为list 解析后 SQL 是有问题的。

### ISSUE THREAD

**Issue by 452552725** [nutzam/nutz#1281]
Exps.inSql("id", "select manage_user_id from manager_r_common where common_user_id in %s", list);

**Comment by wendal** [comment]
嗯嗯,等想想怎么改

**Comment by wendal** [comment]
等等, 你把期望生成的SQL, 完整贴一下, 感觉有点不对劲呢

**Comment by wendal** [comment]
https://nutz.cn/yvr/t/7iact605uoj83o2o1rpv39p5nj
