### ISSUE TITLE
自定义主键生成器异常

### ISSUE THREAD

**Issue by opendever** [nutzam/nutz#1284]
`@Id(auto=false)`    
`@Prev(els=@EL("ig(view.tableName)"))`   
`private Long id;`          

id为对象类型时丢失id

**Comment by wendal** [comment]
int不会丢吧??? Long才会吧?

**Comment by opendever** [comment]
@wendal 修改了

**Comment by wendal** [comment]
没有复现哦, 你用的是什么版本呢? 最新的代码没这个问题
