### ISSUE TITLE
需求：Json.fromJson 支持枚举无参构造函数

### ISSUE THREAD

**Issue by gaosi** [nutzam/nutz#1285]
```java
public enum EnumAttr {
	STRING
	protected String name;
	private DataType() {
	}
}
```
		
Json.fromJson(EnumAttr.class, str); 报错
Mirror.born(“String”);  创建枚举对象时报错

希望枚举类型可使用一下方式
EnumAttr.valueOf("STRING");

**Comment by wendal** [comment]
如果目标是个枚举, 为啥还要走Json.fromJson呢???

**Comment by gaosi** [comment]
在一个实体类中使用枚举，然后需要将实体转成 json 入库。
然后从数据库取出来转不回实体类对象

**Comment by wendal** [comment]
把相关代码贴出来看看

**Comment by wendal** [comment]
没发现问题呢, 可以转的

```java
Json.fromJson(METHOD.class, "'POST'");
```

**Comment by gaosi** [comment]
public enum DataType {

	INT,
	LONG,
	STRING;

	private DataType() {
		
	}

}

public class EventAttr implements Serializable {
	
	protected String name;
	protected DataType dataType;
	protected String alias;
	protected String schema;
	protected String model;
	protected String dictId;
	protected long oprType;
	protected int length;
	protected int sequence;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public DataType getDataType() {
		return dataType;
	}

	public void setDataType(DataType dataType) {
		this.dataType = dataType;
	}

	public String getAlias() {
		return alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	public String getSchema() {
		return schema;
	}

	public void setSchema(String schema) {
		this.schema = schema;
	}

	public String getModel() {
		return model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getDictId() {
		return dictId;
	}

	public void setDictId(String dictId) {
		this.dictId = dictId;
	}

	public long getOprType() {
		return oprType;
	}

	public void setOprType(long oprType) {
		this.oprType = oprType;
	}

	public int getLength() {
		return length;
	}

	public void setLength(int length) {
		this.length = length;
	}

	public int getSequence() {
		return sequence;
	}

	public void setSequence(int sequence) {
		this.sequence = sequence;
	}

	public static void main(String[] args) {
		String json = "{\"name\":\"ceventcategory\",\"dataType\":{\"name\":\"STRING\"},\"alias\":\"事件分类\",\"schema\":null,\"model\":\"event\",\"dictId\":\"event_eventtype\",\"oprType\":0,\"length\":50,\"sequence\":5}";
		EventAttr event = Json.fromJson(EventAttr.class, json);
		System.out.println(event);
	}
	
}

代码就是这样的，转不回对象了

**Comment by wendal** [comment]
```json
\"dataType\":{\"name\":\"STRING\"},
```

对应为

```java
dataType : {
    name : "STRING"
}
```

并非直接对应一个字符串...

**Comment by wendal** [comment]
看来是要注册一个Castor<Map, Enum>

**Comment by gaosi** [comment]
是的，我把DataType 的name 属性加上也转不回来

**Comment by wendal** [comment]
新建个类

```java
public class Map2Enum extends Castor<Map, Enum> {

    public Enum cast(Map src, Class<?> toType, String... args) throws FailToCastObjectException {
        try {
            return Enum.valueOf((Class<Enum>) toType, (String)src.get("name"));
        }
        catch (IllegalArgumentException e) {
            return null;
        }
    }
}
```

然后注册一下, 应该就可以转了,试试吧

```
Castors.me().addCastor(Map2Enum.class);
```
