### ISSUE TITLE
Record 插入TIMESTAMP 类型为Null Postgresql报错

### ISSUE THREAD

**Issue by nicobeyond** [nutzam/nutz#1286]
Record row = new Record();
row.set(".table","test");
row.set("createTime",new Timestamp(System.currentTimeMillis()));
row.set("updateTime",null);
dao.fastInsert(row);

Record 模式Null值，Nutz推测类型错误，放弃根据数据库类型验证导致PostgreSQL执行错误。
mysql和oracle未见异常。
另：PostgreSQL 采用Record模式插入String类型的值需要trim否则报错无法保存！

**Comment by wendal** [comment]
要不,把EntityHolder里面的Map->Entity的逻辑独立出来,做个MapEntityMaker

**Comment by wendal** [comment]
还得加文档
