### ISSUE TITLE
mysql生成表结构int类型*4

### ISSUE THREAD

**Issue by lufei1344** [nutzam/nutz#1287]
![qq 20170718112715](https://user-images.githubusercontent.com/1673338/28299490-221ab792-6bac-11e7-84a9-aa3249bf6916.png)
![qq 20170718112729](https://user-images.githubusercontent.com/1673338/28299491-223146f6-6bac-11e7-9faf-981183da6739.png)
int类型的宽度可以弄成统一的吗，mysql的为什么不直接用定义宽度。

**Comment by wendal** [comment]
... 不要截图...

mysql的int的"长度",纯粹就是"显示长度", 存储空间并不会根据"长度"的不同而有啥区别

如果很在意这个, 可以考虑加个配置项
