### ISSUE TITLE
NutMap中getList的问题

### ISSUE THREAD

**Issue by pangwu86** [nutzam/nutz#1301]
描述待写

**Comment by wendal** [comment]
额, 然后?

**Comment by zozoh** [comment]
啥问题？

**Comment by pangwu86** [comment]
楼上2位要不急，待me加个测试用例

**Comment by pangwu86** [comment]
测试用例 https://github.com/nutzam/nutz/commit/77f9d29383dc3e1424cf3cde80a47dd0ef441d91#diff-8d47267a595d4e7574f7502c747841ac

**Comment by pangwu86** [comment]
主要问题就是 List<T> getList(String key, final Class<T> eleType) 方法
放进去一个list，跟拿出来的list 内存里并不是同一个对象
