### ISSUE TITLE
Images.createAvatar 可否扩展成不限字数生成图片

### ISSUE THREAD

**Issue by wqmain** [nutzam/nutz#1303]
现在 Images.createAvatar 的适用场景是生成头像，可不可以扩展下由调用者传入字符的个数？因为有生成纯文字图片的场景，感谢！

**Comment by wendal** [comment]
这个得 @pangwu86 了

**Comment by ywjno** [comment]
生成很多文字的头像？

**Comment by zozoh** [comment]
是想给定一个文字，然后生成一个图片对吧。

把具体需求列一下

1. 你具体是在什么场景上要用
2. 你希望怎样调用

应该是创建一个新函数比较好

**Comment by wqmain** [comment]
@zozoh 对，就是想给定一串文字，然后生成一个图片。
1、说个简单点的场景：做一个临时的演示系统，比如一个后台管理系统，那header区域左侧一般是logo+系统名字吧，如果想用纯文字图片临时替代一下又不想找美工PS就需要这个API了。后期让美工设计后直接替换图片就可以了（省的前期CSS美化文字，后期又要换成图，需要改动HTML结构），这个应该是个人开发者的福音。
2、Images.createImage(图片整体宽度，图片整体高度，背景ARGB，文字内容，文字字体，文字大小，文字ARGB);
如果能再提供附加logo并且可调整logo背景透明度的功能就完美了，^_^

**Comment by pangwu86** [comment]
me改改看

**Comment by ywjno** [comment]
图片加文字还要依赖指定字体文件的，如果服务器没有会有问题

**Comment by pangwu86** [comment]
字体这个有个列表 会遍历尝试 都有没有就自己手动加上吧

**Comment by pangwu86** [comment]
这个可以关了吧， 已经有API了
