### ISSUE TITLE
MysqlJdbcExpert 类中，mysql 的 charset 的默认值要不要改成 utf8mb4

### ISSUE THREAD

**Issue by ywjno** [nutzam/nutz#1308]
即使 mysql 的 charset 设置成了 utf8，在实际应用中还是会有很多问题，要不干脆直接改成 utf8mb4 算了

**Comment by wendal** [comment]
但utf8字段不能跟uft8mb4字段进行对比,很是蛋疼

**Comment by ywjno** [comment]
真是个蛋疼的东西，关了。。
