### ISSUE TITLE
添加支持达梦数据库

### ISSUE THREAD

**Issue by Wizzercn** [nutzam/nutz#1309]
//加载JDBC驱动类
   Class.forName("dm.jdbc.driver.DmDriver");
   //创建数据库连接
   conn = DriverManager.getConnection("jdbc:dm://223.254.105.33:12345/test","SYSDBA","SYSDBA");

dbType 里没有dm这个类型

**Comment by Wizzercn** [comment]
![qq 20170829140217](https://user-images.githubusercontent.com/2408114/29806581-c0f26e96-8cc2-11e7-8cb7-bbcc74b0e8e6.png)

**Comment by wendal** [comment]
那是druid报错, 跟nutz么有关系

**Comment by wendal** [comment]
给druid报issue呗

**Comment by Wizzercn** [comment]
package org.nutz.dao.impl.jdbc.  不需要加个dm？

**Comment by wendal** [comment]
据说跟mysql一样的语法
