### ISSUE TITLE
NutzDao增加一个countByJoin接口

### ISSUE THREAD

**Issue by shawn-show** [nutzam/nutz#1313]
在关联查询需要分页的时候，有queryByJoin方法，但是没有countByJoin方法，考虑到cnd的复用，及查询条件中包换关联表的条件，所以强烈建议多写一个queryByJoin方法
现在我是这样解决的：
`
        List<SendEmailRecord> records = dao.queryByJoin(SendEmailRecord.class, "sysUser", cnd, pager);
        pager.setRecordCount(dao.queryByJoin(SendEmailRecord.class, "sysUser", cnd).size());
        QueryResult result = new QueryResult(records, pager);
`
数据量大了以后很卡

**Comment by wendal** [comment]
queryByJoin的总条数仅取决于主表的数量，count的时候还带join只会更慢.
