### ISSUE TITLE
欢迎提供skywalking plugin

### ISSUE THREAD

**Issue by wu-sheng** [nutzam/nutz#1324]
很高兴看到Nutz项目组在oschina上的留言，希望Nutz项目组能够贡献skywalking的RPC plugin，共建功能生态。

skywalking 3.2+插件开发手册：https://github.com/wu-sheng/sky-walking/wiki/Plugin-Development-Guide

期待你们的回复：）

**Comment by wendal** [comment]
我研究一下试试

**Comment by qinerg** [comment]
这个的确有点意思

**Comment by wendal** [comment]
开工搞呗,先把sky-walking搭起来

**Comment by wendal** [comment]
nutz mvc 和 nutz http的集成弄好了,准备写demo

https://github.com/nutzam/sky-walking/commit/64b6c9229204db7c021204cd6ee08b932d42843e

**Comment by wendal** [comment]
![image](https://user-images.githubusercontent.com/589819/30678304-d2119aa4-9ec3-11e7-86eb-da1e0fb3746f.png)

**Comment by Rekoe** [comment]
demo demo ....

**Comment by wendal** [comment]
@Rekoe 用的时候不需要程序做修改,只是加点启动参数

**Comment by Rekoe** [comment]
提交上来吧 俺也搞个看看效果

**Comment by wendal** [comment]
@Rekoe 我就是拿nutz.cn的代码测试的, 只需要在tomcat的启动参数里面加入. 就是需要点时间把sky-walking搭建起来.

```
-javaagent:C:/Users/wendal/workspace/git/github/sky-walking/packages/skywalking-agent.jar -DapplicationCode=nutzcn -Dservers=127.0.0.1:10800
```

**Comment by wu-sheng** [comment]
已完成。
