### ISSUE TITLE
Times下的格式转换存在并发问题

### ISSUE THREAD

**Issue by qinerg** [nutzam/nutz#1328]
Times中部分静态方法使用了静态的SimpleDateFormat类，而SimpleDateFormat非线程安全，在高并发下会因内部变量清空而导致报错。最近经常会碰到这个问题。
原因见 http://blog.csdn.net/farrell_zeng/article/details/54408616

**Comment by wendal** [comment]
哦, 需要clone一下,你自己改呗

**Comment by ywjno** [comment]
或者自己保证线程安全吧

**Comment by wendal** [comment]
来吧, push个修改来

**Comment by qinerg** [comment]
我的错我的错，仔细研读了一遍 Times 类，发现该 clone 都已经做啦，看来 zozoh 大神已经帮趟过这个坑了
