### ISSUE TITLE
dao.QueryResult 来个带查询条件的吧

### ISSUE THREAD

**Issue by howe** [nutzam/nutz#1331]
RT 
@wendal

**Comment by wendal** [comment]
没懂

**Comment by howe** [comment]
就是 加上 查询条件的对象
@Param("..") XXXQuery query
XXXQuery 里面就是各种查询条件
return new QueryResult(dao1.query(Order.class, cri, pager), pager， query);

**Comment by wendal** [comment]
哦,就是加个属性咯

**Comment by howe** [comment]
对的 看你的了
