### ISSUE TITLE
利用 `Record` 更新 Oracle，由于key都为小写导致更新不成功

### ISSUE THREAD

**Issue by gythialy** [nutzam/nutz#1335]
使用场景：
从 MySQL 中查询得到一个 `List<Record>`，然后通过这个  `List<Record>` 把查询到的记录插入到 Oracle 中，两边的表结构一直，但是由于 Oracle 会自动会把字段名转成大写，所以还是会有一点不太一样

问题：
表中的字段名称有 Oracle 的保留关键字，比如 `type`，正常的 SQL 语句应该用`""`逃逸，插入语句类似
```sql
INSERT INTO tb_test1(id,"TYPE") VALUES(140500,1) ;
```
由于 `Record` 中的字段名都是小写，会生成类似下面的语句
```sql
INSERT INTO tb_test1(id, type) VALUES(140500,1) ;
```
手动把 `type`改成 `"TYPE"`，生成
```sql
INSERT INTO tb_test1(id, "type") VALUES(140500,1) ;
```

但是 Oracle 的字段名称都是大写，导致更新不成功

是否有其他办法，不生成 POJO，实现此功能？

**Comment by wendal** [comment]
提问类的请使用 nutz.cn

https://nutz.cn/yvr/t/7j68qu5imeipprvmbe12agd3si
