### ISSUE TITLE
Module继承行为需要一个开关

### ISSUE THREAD

**Issue by happyday517** [nutzam/nutz#1337]
讨论见: [这里](https://nutz.cn/yvr/t/7lmhl5g4cehfkrh202m3ht983p)

**Comment by zozoh** [comment]
开关的默认选项是开，还是关呢？

**Comment by happyday517** [comment]
默认是关吧 ，另外这个开关要加在 `@At` 上吗？
有没有更合适的位置？

**Comment by ywjno** [comment]
为了兼容之前版本默认当然是开了，不然他升级之后路由莫名少了

**Comment by zozoh** [comment]
可以加载子类模块上，表示子类全盘接受父类的 @At

或者加在父模块上，的某个入口函数上，表示子类继承自己后，也要继承这个入口函数

推荐这个开关叫 `@ReuseAt`

**Comment by zozoh** [comment]
@ywjno  额，现在默认子类都是继承父类的 `@At` 的?

哦，果然:

```java
 for (Class<?> module : modules) {
            ActionInfo moduleInfo = Loadings.createInfo(module).mergeWith(mainInfo);
            for (Method method : module.getMethods()) {
                if (!Modifier.isPublic(method.getModifiers()) || method.isBridge())
                    continue;
                if (Mirror.getAnnotationDeep(method, At.class) == null)
                    continue;
                // 增加到映射中
                ActionInfo info = Loadings.createInfo(method).mergeWith(moduleInfo);
                info.setViewMakers(makers);
                mapping.add(maker, info, config);
                atMethods++;
            }

            // 记录pathMap
            if (null != moduleInfo.getPathMap()) {
                for (Entry<String, String> en : moduleInfo.getPathMap().entrySet()) {
                    config.getAtMap().add(en.getKey(), en.getValue());
                }
            }
        }
```

我一直以为默认是不扫描父类的 -_-!

**Comment by ywjno** [comment]
我怎么觉得要是用 java8 的话应该这个父类应该改成 interface，然后在接口中定义默认方法，子类继承

**Comment by zozoh** [comment]
但是不能强制要求使用者这么写吧

**Comment by happyday517** [comment]
父类主要起配置作用  你还是没明白啊 @ywjno 
通用逻辑当然也可以写在父类里，如果子类不那么特殊的话，调用super就ok了
否则，当然也允许子类自己实现逻辑

**Comment by happyday517** [comment]
关键点不是说子类调用父类的方法

**Comment by ywjno** [comment]
是你没理解文档

按照[文档](https://nutzam.com/core/mvc/modules.html)里面写的，有类包括了一个以上的 入口函数 将被认为是 模块类，跟他继承哪个父类没关系

**Comment by zozoh** [comment]
如果你不想让父类成为模块，你给父类标识 `abstract` 关键字咯

@happyday517  的动机，我想是，省掉

```java
@At
public String xxx(){
     return super.xxx();
}
```

这段代码吧

不过，原来实现的时候，判断一个类是不是模块类，就是看里面有没有方法带 `@At`
而，取得方法表，用的是 `Class.getMethods()` 就是把父类的方法表一并都看了

现在如果要实现 @happyday517  的诉求的话，需要判断清楚，这个方法是子类还是父类的
如果是子类的就和现在一样，如果是父类的，就得看开关了

当然开关还是 @ywjno  说的，默认应该是打开，才能保持向下兼容

**Comment by happyday517** [comment]
因为现在`@At`有继承机制
所以子类方法无需自己声明`@At`
复写父类有`@At`的方法，也可以被识别为 入口函数
和文档并不冲突，另外这项功能如果官方认可的话，应该补充到文档里

**Comment by ywjno** [comment]
是跟文档不冲突，但是父类上面写了 `@At` 注解的，并且用 `scanPackage = true` 方式的话，父类的那些方法也都是入口函数了，

那么，你按照你说的只是想成为配置的话，这些父类的 `@At` 方法算不算入口函数呢

**Comment by zozoh** [comment]
@happyday517  ， 我想 @ywjno  的意思是

如果你要在子类复写：

```java
@override
public String xxx(){
     return super.xxx();
}
```

根不在子类里复写，之际声明:

```java
@At
public String xxx(){
     return super.xxx();
}
```

对用户没有差别

**Comment by ywjno** [comment]
对，是没差别，如果他 override 写子类的各自实现的话，他应该用的是接口

**Comment by happyday517** [comment]
父类可以不写 `@At`  还是以RESTful的一个模块设计来举例
```
// 父类没有@At
public class Restful<T> {
  
    @GET
    @At("/?")
    protected T restGet(String str) {}

    @POST
    @At("/")
    @AdaptBy(type = JsonAdaptor.class)
    protected Msg restCreate(T obj) {}

    @PUT
    @At("/")
    @AdaptBy(type = JsonAdaptor.class)
    protected Msg restUpdate(T obj) {}

    @DELETE
    @At("/?")
    protected Msg restDelete(String str) {}

}

// 子类
@At('/user')
public UserAction extends Restful<User> {
    // 如果子类需要restGet 路径 /user 必须用Get方式 因为父类规定了这些
    @Override
    public User restGet(String str) {}
    
    //  需要 restCreate   路径 /user 必须用Post方式 因为父类规定了这些，且Adaptor = JsonAdaptor
    @Override
    public Msg restCreate(User obj) {}

    //  另外几个不需要就不加
}
```

**Comment by ywjno** [comment]
你父类不写 `@At` 的话，`@GET` 即使写了也没用的

**Comment by ywjno** [comment]
表面上看是模块的继承造成的入口函数对外暴露的问题，其实应该算是个想要个入口函数模板功能吧

**Comment by happyday517** [comment]
morning 各位
昨天讨论扯远了，讨论到了场景上
昨天晚上测试了下，表现形式如下：
```
// Nutz Version : 1.r.62 
public abstract class Base {
    @At public void sayhi() {}
    @At public void saybye() {}
}

@At("/my")
public class MyModule extends Base {}
// 入口函数：
//  '/my/sayhi'  >> Base.sayhi(...)       
//  '/my/saybye' >> Base.saybye(...)
//  子类无条件增加所有父类入口函数映射

// ---------------分割线-----------------------

// Nutz Version : 1.r.60

public abstract class Base {
    @At public void sayhi() {}
    @At public void saybye() {}
}

@At("/my")
public class MyModule extends Base {}

// 没有任何入口函数

public abstract class Base {
    @At public void sayhi() {}
    @At public void saybye() {}
}

@At("/my")
public class MyModule extends Base {
    @Override
    public void sayhi() {
        super.sayhi();
    }
}

//  入口函数：
//  '/my/sayhi'  >> (MyModule.java:10).sayhi
//  仅有sayhi，saybye子类没有复写，所以没有映射入口函数，这样控制权交给了子类

```

1.r.60中如果要实现1.r.62的效果，子类override所有父类方法即可，用IDE的话就是点两下鼠标的事

**Comment by ywjno** [comment]
看来还得改回去

**Comment by happyday517** [comment]
我也觉得是改回去合适，想了下昨天 zozoh 的建议

> 可以加载子类模块上，表示子类全盘接受父类的 @at
> 或者加在父模块上，的某个入口函数上，表示子类继承自己后，也要继承这个入口函数
> 推荐这个开关叫 @ReuseAt

这样设计，如果用户使用了1.r.62的继承方式，升级版本后，得在所有子类上加`@ReuseAt`，或者在父类所有入口函数上加`@ReuseAt`，才能保证路由和升级之前一致。
没有向下兼容，而且增加了配置概念，不如改回去

**Comment by zozoh** [comment]
最后，看看 @wendal 的意见咯

**Comment by wendal** [comment]
我来了

**Comment by wendal** [comment]
我还是没搞明白, 如果父类的@At方法不是用于映射的, 那它存在的意义是什么???

**Comment by wendal** [comment]
继承的意义是获取超类的大部分逻辑(方法),然后修改部分逻辑(方法)

所以,常态应该是: 超类提供的@At方法, 子类在大部分情况下应该是接受的.

反证: 如果大部分子类都不需要超类的@At方法, 那这个超类里面@At存在的意义==0

继承同一个超类的子类, 应该是映射不同前缀,但业务逻辑类似的Module类:

```
/user/add
/user/delete
/role/add
/role/delete
```

然后有个特别子类不需要某个公共的@At实现, 希望禁用掉该方法的映射

```
/log/add
/log/delete 不允许存在.
```

所以,我觉得给出一个方案(扩展或新增注解),让子类明确表述需要禁用(or启用?)的入口方法

**Comment by zozoh** [comment]
感觉好像把路由弄复杂了有。@happyday517 继续

**Comment by happyday517** [comment]
@wendal 理解的对，和我的思路一样
问题就在于如何设计这个功能
我前面讲的是我认为最简单的实现方式，子类通过Override父类方法，来表述需要**启用**哪些入口方法
没有Override的，就是禁用的
顶多在这个基础上再加一个类注解，标注在子类上，表示接收所有父类入口方法，无论有没有Override

而现有的默认继承所有父类入口方法的方式，需要添加一个禁用规则的话，使用起来会很别扭。
大概也就下面两种形式
```java
// 一种是在父类入口方法上，标识哪些子类禁用
public abstract class Base {
    @At
    @Off({SubA.class,SubB.class})
    public void sayhi() {}
    @At
    @Off({SubC.class})
    public void saybye() {}
}

// 另一种是在子类上，通过Override方法，然后throw Lang.noImplement() 或者 加注解，表示禁用
@At("/my")
public class MyModule extends Base {
    @Override
    @Off // 表示禁用
    public void sayhi() {}
}
```
无论上面哪种方式，用起来都很别扭

**Comment by wendal** [comment]
这样如何?

```
@IocBean
@At
@ReuseAt(exclude="sayhi|delete|remove")
public class MyModule extends Base {
}
```

**Comment by ywjno** [comment]
果然还是用黑白名单来实现了

**Comment by wendal** [comment]
@ywjno 这点很有wendal风格吧,哈哈

**Comment by ywjno** [comment]
这还好吧，我做过的框架 rubu on rails 就用的文件来进行路由管理

**Comment by happyday517** [comment]
```java
@At(exclude="sayhi|delete|remove")
@IocBean
public class MyModule extends Base {
}
```
这样更简便一些
已经默认全部继承了，那@ReuseAt也没必要了吧？

不过我还是喜欢我的那种风格，通过Override来控制

**Comment by happyday517** [comment]
等等，考虑到多态问题
我还是强烈建议Override方式精确控制

否则父类这样
```java
    @GET
    @At("/?")
    protected T get(String str) {}

    @GET
    @At("/?")
    protected T get(id id) {}
```
正则表达式没法区分

**Comment by wendal** [comment]
@Override注解是拿不到的

**Comment by happyday517** [comment]
拿 override 干嘛

**Comment by wendal** [comment]
你的意见是, 如果我要继承父类的@At, 就必须override父类对应的方法,对吧?

**Comment by happyday517** [comment]
是的
在此基础上，可以增加一个注解`@ReuseAt`，标识在子类上
表示接收所有父类入口方法，无论有没有Override
满足接收全部入口函数的需求

**Comment by wendal** [comment]
恩,待我想想哦

**Comment by zozoh** [comment]
@happyday517  这个思路 @ywjno 的反驳是：

如果你要在子类复写：

```
@override
public String xxx(){
     return super.xxx();
}
```

根不在子类里复写，直接声明:

```
@At
public String xxx(){
     return super.xxx();
}
```

对用户没有差别

另外，现在映射方式，是不支持多态的吧

**Comment by happyday517** [comment]
```java
@At // 重点是这里，父类可能有 @At @Ok @POST @AdaptBy 等等配置，不想让每个子类都再写一遍
public String xxx(){
     return super.xxx();  // 重点不在这里
}
```
现在映射方式，是没有特殊判断多态
但结合`@Get` `@Post`等使用的话，实际上是有多态效果的

**Comment by happyday517** [comment]
父类的功能有两部分
1. 逻辑(方法)
2. Mvc配置，包括`@At @Ok @Fail @POST @GET @AdaptBy`等

@ywjno 以为我需要的只是父类的逻辑，实际我两样都要，这个讨论已经跑远了

**Comment by zozoh** [comment]
所以用 @wendal  的 `exclude` 有什么不好？

**Comment by happyday517** [comment]
没有多态
比如父类
```java
    @GET
    @At("/?")
    protected T get(String str) {}

    @GET
    @At("/?")
    protected T get(int id) {}
```

`exclude="get" `  只能两个都exclude了，而用override的方式就不存在这个问题

**Comment by zozoh** [comment]
现在 Nutz 路由支持 下面这种写法?

```java
    @GET
    @At("/?")
    public T get(String str) {}

    @GET
    @At("/?")
    public T get(int id) {}
```

**Comment by happyday517** [comment]
子类可以选择启用哪一个get

**Comment by wendal** [comment]
这是不合理的写法

**Comment by happyday517** [comment]
是的，这是一个极端例子
但即便如此，override的方案也依然能搞的定

**Comment by happyday517** [comment]
两位大神，exclude真的不是一个好设计，想想看吧，你有很多子类
override方式明确告诉你，哪些方法是入口函数，足够简单
exclude你得翻看父类，如果很不幸，父类又继承了其他类
你得一层层去翻看才能最终确定，到底暴露了哪些入口函数

其他多态、Restful模板什么的，统统先不要考虑，仅仅讨论，如何设计一个合理的入口函数继承机制

我认为override更清晰，exclude在复杂继承关系里，不容易看出到底暴露了哪些
并且，exclude无法解决同名方法的问题，当然你可以要求用户不要使用多态
但这样真的好吗 🙂

**Comment by happyday517** [comment]
如果真的需要全部继承，在override的机制前提下，稍微扩展一下就能实现

**Comment by zozoh** [comment]
这个不是一个实现问题，这个是个设计问题：

除了考虑 100% 的情况，我们还需要考虑，在 80% 的场景下，怎么写最简洁。

大多数场景下，如果继承一个父类，通常是要继承它的 `@At`，偶尔有一两个 `@At` 需要关闭，也是小场景，在这种小场景下，能工作就好了。

设计的问题，还需要考虑的是风格： Nutz 的风格基本是“少点代码总比多点代码要好”

这里 @happyday517  提出的问题，父类有 `@At`，还需要查看方法名，然后在子类写 `@AtReuse` 去掉，不方便。 由于这个场景使用的并不频繁，所以更倾向于遵守 Nutz 的风格。即，`少点代码总比多点要好`

**Comment by happyday517** [comment]
NoNoNo
不是 `父类有 @At，还需要查看方法名，然后在子类写 @AtReuse 去掉，不方便`这个不方便
是当你的系统用这种机制建立起来后
重构，或交叉review时
你有N多个Action，清楚的知道某个Action暴露了哪些方法，不方便
需要脑补，所有父类的`@At`方法并集减掉exclude的

并且，不觉得这样会有安全隐患吗？尤其是一些删除数据的操作，被子类无条件继承

**Comment by ywjno** [comment]
不能删除数据库操作的父类单独弄一个好了

**Comment by zozoh** [comment]
@happyday517  如果需要很复杂路由设定的那种，为啥父类需要暴露出 `@At`，仅仅提供一个 protected 的方法，让子类调用不就好了吗？

你主要的考虑是为了让子类省的写 `@GET  @POST  @AdaptBy` 之类的注解吧？

**Comment by happyday517** [comment]
这样更好，做一个更底层的配置项，可以让用户自行扩展

Modules 里增加一项 EntryMethodDeterminer(入口方法判断器)
```java

public interface EntryMethodDeterminer {
    // 判断是否入口方法
    boolean isEntryMethod(Class<?> module,Method method);
}

// org.nutz.mvc.annotation.Modules
// 内置一个默认实现，兼容现有行为
Class<?> entryMethodDeterminer() default NutEntryMethodDeterminer.class;

// 默认实现
public class NutEntryMethodDeterminer implements EntryMethodDeterminer {
    @Override
    public boolean isEntryMethod(Class<?> module, Method method) {
        if (!Modifier.isPublic(method.getModifiers()) || method.isBridge())
            return false;
        if (Mirror.getAnnotationDeep(method, At.class) == null)
            return false;
        return true;
    }
}

```
最后改造下 `NutLoading`，加载EntryMethodDeterminer

这样可以吗？

**Comment by wendal** [comment]
最后是终极大招... #1340
