### ISSUE TITLE
实现生成验证码图片

### ISSUE THREAD

**Issue by pangwu86** [nutzam/nutz#1339]
- [x] 自动选颜色，字体，大小 
- [x] 旋转文字
- [x] 干扰线
- [x] 图片扭曲

**Comment by zozoh** [comment]
厉害了啊

**Comment by pangwu86** [comment]
```java
// 生成6位随机数字验证码
Images.createCaptcha(R.captchaNumber(6));

// 生成6位随意数字，字符验证码
Images.createCaptcha(R.captchaChar(6));
```

**Comment by wendal** [comment]
厉害了

**Comment by pangwu86** [comment]
扭曲还没实现，还有问题

**Comment by pangwu86** [comment]
图片扭曲：http://nutzam.com/core/img/overview.html#ndoc-6
生成验证码：http://nutzam.com/core/img/advanced.html#ndoc-5

**Comment by wendal** [comment]
666

**Comment by wendal** [comment]
我有一个邪恶的想法, 用tensorflow去识别生成的验证码...

**Comment by ywjno** [comment]
你说的可是这个？ [[Python爬虫] 「暴力」破解猫眼电影票房数据的反爬虫机制](https://jizhi.im/blog/post/maoyan-anti-crawler)

**Comment by wendal** [comment]
https://github.com/JackonYang/captcha-tensorflow

**Comment by ywjno** [comment]
这厉害了

**Comment by pangwu86** [comment]
数字+字母比较容易吧，上一堆中文估计就比较难了 或者是算术题那种，结果并不是显示的内容

**Comment by wendal** [comment]
话说, nutzcn的验证码可以换成这个了
