### ISSUE TITLE
想写一个partition查询,Cnd写不出来

### ISSUE THREAD

**Issue by wendal** [nutzam/nutz#1342]
我被问住了...

```sql
select * from pets partition(test_2017)
```

注意,木有where,而且不能加where --> 这个坑有点大...

**Comment by wendal** [comment]
憋了半天,写出一个搓脚的方案

```java
            dao.query(Pet.class, new SimpleCriteria("partition(分区名)") {
                @Override
                public void joinSql(Entity<?> en, StringBuilder sb) {
                    sb.append("partition(分区名)");
                }
            });
```

**Comment by wendal** [comment]
修改方案: 扩展SimpleCriteria,支持任意SQL字符串的插入

**Comment by ywjno** [comment]
我第一个想出来的解决方法是用动态表名 `@Table("test partition(test_${year})")`

**Comment by ywjno** [comment]
感觉 SimpleCriteria 是拿来拼接 where 条件的啊，不合适

**Comment by wendal** [comment]
@ywjno 额,单独开个类来干这个事??

**Comment by ywjno** [comment]
这。。。要不再观察观察需求吧，感觉好多人不会用这东西

**Comment by ywjno** [comment]
而且那个 `sb.append(anything)` ，如果 anything 是 `Robert'); DROP TABLE STUDENTS; --` 之类的话，没问题么

**Comment by wendal** [comment]
这跟`Sqls.create(anything)` 一个道理吧?
