### ISSUE TITLE
Nutz的 dao.count() 方法针对PostgreSQL 能不能不走事务

### ISSUE THREAD

**Issue by guanml** [nutzam/nutz#1353]
Nutz的 dao.count() 方法针对PostgreSQL 能不能不走事务，我用nutz往pgxl 集群里读取统计数据的时候，报出savepoint 异常，因为pgxl 不支持savepoint 保存事务点。

**Comment by wendal** [comment]
在dao.js中的dao fields中加入

```
autoTransLevel : 0
```

**Comment by guanml** [comment]
@wendal  在dao.js中修改的方法不行，我根据你在群里的提示 用下面的代码搞定了。
`    SimpleDataSource ds = new SimpleDataSource();
            ds.setDriverClassName("org.postgresql.Driver");
            ds.setJdbcUrl("jdbc:postgresql://192.168.1.46:5432/osm");
            ds.setUsername("postgres");
            ds.setPassword("123456");
            NutDao dao = new NutDao(ds);
            dao.setRunner(new NutDaoRunner() {
                public void run(final DataSource dataSource, final ConnCallback callback) {
                    Connection conn = null;
                    // 开始一个连接
                    try {
                        conn = dataSource.getConnection();
                        // 开始循环运行
                        callback.invoke(conn);
                        // 完成提交
                        if (!conn.getAutoCommit()) {
                            conn.commit();
                        }
                    } // 异常回滚
                    catch (Exception e) {
                        try {
                            if (conn != null) // 高并发时,从数据库连接池获取连接就已经抛错误,所以conn可能为null的
                            {
                                conn.rollback();
                            }
                        } catch (Exception e1) {
                        }// TODO 简单记录一下?
                        if (e instanceof DaoException) {
                            throw (DaoException) e;
                        }
                        throw new DaoException(e);
                    } // 保证释放资源
                    finally {
                        if (null != conn) {
                            // 关闭链接
                            try {
                                conn.close();
                            } catch (SQLException closeE) {
                                closeE.printStackTrace();
                            }
                        }
                    }
                }
            });
            System.out.println(dao.count("pg_class"));
`

**Comment by wendal** [comment]
版本问题，你的版本低
