### ISSUE TITLE
Mapl不支持"."转义和连续的index路径

### ISSUE THREAD

**Issue by maxixi** [nutzam/nutz#1355]
如题，某些时候我们还是需要在Map中放置带有“.”的key，如{“MY.NAME”:"XX"}，但是在Mapl中“.”作为路径分隔符了并且没有相应的转义符支持将其变为普通字符，建议加入转义符（如“!”,"\"等等）对特殊字符（包括“.”、“[”和"]"）赋予需要时的转义能力，方便我们使用这些关键字符作为key。
       另外，连续的index访问在Mapl中并不支持，如“[0][1][2].name”，仅仅是将前后中括号中的“0[1]2”进行了数字转换导致报错。实际应用场景中应该有这种数据结构的访问需求，因此希望改进。

**Comment by wendal** [comment]
额,有道理

**Comment by wendal** [comment]
想想解析过程是怎么写的...

**Comment by maxixi** [comment]
有点困难，我试着写了一下，能解决"."的转义问题，但是对于“[]”的转义感觉有点困难-_-!
转义点号的大致做法是（假定‘?’为转义符）：
设立一个List存储普通段落，如key=“??.NAME?.PREFIX.FIRST”, value = "m",那么表现在map中的真正含义是
```javascript
{
    "?": {
            "NAME.PREFIX": {
                    "FIRST": "m"
             }
      }
}
```
那么用正则表达式捕获(~\S)，将意思为普通字符的“.”和普通字符存储在一起，不是普通字符的“.”则舍弃，上面的Key转换一下存储在List即为["?", "NAME.PRIFIX", "FIRST"]，现在按照List中的顺序以层次组装Map即可

**Comment by zozoh** [comment]
这种情况，不用 Mapl，直接 Map get 其实比较好吧

**Comment by maxixi** [comment]
get固然可以解决问题，若是层次较深，Mapl正是利刃。再谈put，使用原生方法有5层估计都会疯掉吧。我的意思是Mapl满足了一小撮人的需求，带来了钜惠，但是从更深的层次上来说，不能转义一些关键的符号（"."、"[]"）和进行连续的[index]访问，使用上会稍显局限

**Comment by zozoh** [comment]
那么我提议这样的语法：

```
’A.B‘.xyz
```

其中单引号 `'A.B'` 括起来的 部分表示一个完整的键值不能再被分隔

**Comment by wendal** [comment]
嗯, 扩展一下Mapl里面的路径解析算法

**Comment by maxixi** [comment]
可能是强迫症吧，如同大多数程序猿，要么不做，要么做好。我认为任何符号均有其用途，就相当于Java中的反斜杠<code>"\\"</code>，作为转义符的它仍然有被用到的时候(<code>"\\\\"</code>)，但是我在这里能得到回复已经不胜感激了，可见作者们对于Nutz的用心，致敬！(￣▽￣)~*

**Comment by zozoh** [comment]
这个是一个设计上的偏好的，我通常做设计遵循 90% 情况下最优，剩下 10% 可用即可。

我认为 `'A.B'.xyz` 看起来比 `A?.B.xyz` 更好看，呵呵，没办法，美工出身，有点强迫症
所以，从我看来， `'A.B'.xyz` 似乎比 `A?.B.xyz` 是更优的设计方案。虽然 `A??.B.xyz` 这样的写法，应该可以转义一切字符，但是看起来总觉得不好看。

不过我还可以把语法扩展一下，

可以支持

```
`A.B'.xyz    # 单引号语法
"A.B".xyz    # 双引号语法

这样如果你的键里面有单引号，你可以用双引号，
反过来也一样

`A"B`.xyz
"A'B".xyz
```

不过如果你的键里又有单引号，又有双引号，额，好吧见了鬼了。这种情况就属于 10% 的 10% 的 10% 了吧，那就用 Map 自己 get 好了

这样，既在 99% 的情况下保持了语法的简明（从我主观上来说的优美），而且还。。。好吧，主要就是为了保持语法的简明 ^_^!

你们看呢？

**Comment by pangwu86** [comment]
key里面有单引号和双引号太反人类了吧，命名规则是哪个老师教的，拖出去枪毙得了

**Comment by wendal** [comment]
MaplTest里面有这样的testcase

```java
    @Test
    public void cellTestSpecialKey() {
        Object dest = Json.fromJson("{'a.b':'AB', x : [{'c.d':'CD'},{'e.f':'EF'}]}");

        assertEquals("AB", Mapl.cell(dest, "'a.b'"));
        assertEquals("CD", Mapl.cell(dest, "x[0].'c.d'"));
        assertEquals("CD", Mapl.cell(dest, "x.0.'c.d'"));
        assertEquals("EF", Mapl.cell(dest, "x[1].'e.f'"));
        assertEquals("EF", Mapl.cell(dest, "x.1.'e.f'"));

    }
```

**Comment by wendal** [comment]
嗯? 木有动静了?

**Comment by maxixi** [comment]
虽然有点反人类，但我认为只要是符号那么必然有其用途。人们常用逗号、点号、减号、下划线作为分隔符但没有谁硬性规定，形如“What's your name”这种语句仍然很常用，令人意外的是居然使用了单引号作为分隔符。至于美学，只要设定的转义符号不是太夸张相信还是可以被接受，相当于java中的```\```，在java中写正则表达式双重甚至多重转义（n个```\```）也少见有人吐槽，况且Mapl本身特殊字符就很少，因为这些很少量的特殊字符便废掉一个有用的字符```'```，鄙人认为欠佳。根据zozoh大神的说法，论语法简明，对比我的提议和zozoh的想法，我得出的结论是

> 在都不使用转义符的情况下，差异为0；在都使用转义符的情况下，zozoh的法子更简明，但若是加上使用概率，后者的优势或者是前者的劣势可忽略不计，即便要计，前者永久损失了一个字符，后者理论上不损失。当然我需要尊重作者和大多数用户的意见，只是说这两者必然有所取舍，如果是我，我会舍弃既有标准（java和大多数高级语言的转义符）之外的东西
另外，有关多重index（形如a[1][2][3].name）的建议可以考虑吗？

**Comment by wendal** [comment]
我觉得还是先把 "连续的index路径" 做一下吧

**Comment by wendal** [comment]
需要改这个方法 

org.nutz.mapl.impl.MaplRebuild.inject(Object, int)

**Comment by zozoh** [comment]
@juqkai  看一下？

**Comment by zozoh** [comment]
@maxixi  我发现我说的语法 

```
`A.B'.xyz    # 单引号语法
"A.B".xyz    # 双引号语法

这样如果你的键里面有单引号，你可以用双引号，
反过来也一样

`A"B`.xyz
"A'B".xyz
```

现在本来就是支持的 ^_^!

**Comment by maxixi** [comment]
嗯，了解了，我应该多看看源码的，谢谢！(•̀ᴗ•́)
