### ISSUE TITLE
dao的delete对分库分表的支持

### ISSUE THREAD

**Issue by tiankongkm** [nutzam/nutz#1358]
单机版根据主键删除没有任何问题，但是目前项目用到了分库分表，crud都需要带上分片建去做路由，所以只有通过自定义sql来实现删除了。

**Comment by wendal** [comment]
分片的SQL是怎样的? 贴来看看

**Comment by tiankongkm** [comment]
delete app_short_vedio where user_id=12345 and short_vedio_id=56789
类似这种 user_id是分片建 ，short_vedio_id 是主键   框架根据user_id路由到具体的vedio表。

我的想法是这样写
shardingDao.delete(vedio.class,cnd.where(...));
但是我现在只能自定义sql了。

**Comment by tiankongkm** [comment]
我用的分库分表框架是sharding-jdbc

**Comment by wendal** [comment]
不需要自定义SQL呢, 应该用clear方法

```java
shardingDao.clear(Vedio.class,Cnd.where(...));
```

**Comment by tiankongkm** [comment]
奥奥，多谢。
