### ISSUE TITLE
请问，考虑增加类似lazy-init的配置吗？

### ISSUE THREAD

**Issue by shi-yuan** [nutzam/nutz#1359]
```js
var ioc = {
    friend: {
        type: 'nutz.demo.ioc.book.Pet',
        fields: {
            name: 'XiaoHei'
        },

        // 请问考虑提供这样的配置吗，项目启动就实例化
        "lazy-init": false
        // 请问考虑提供这样的配置吗，项目启动就实例化
    }
}
```

**Comment by ywjno** [comment]
单例类？

**Comment by shi-yuan** [comment]
单例类，app启动就实例化

**Comment by ywjno** [comment]
那就直接写单例类就好了，这跟 ioc 有什么联系么

**Comment by happyday517** [comment]
Setup里，调用下`ioc.get(xxx)`即可实例化

**Comment by shi-yuan** [comment]
MainSetup.init确实可以做，ioc.js里能提供的话，那就更好了

**Comment by wendal** [comment]
先开着吧，只是还没想好怎么搞

**Comment by zozoh** [comment]
@shi-yuan  为什么 Ioc 里提供这个功能会更好？

**Comment by shi-yuan** [comment]
个人原因吧，我们这边，目前不方便在MainSetup.init里做这个，但是有需要启动的时候实例化，所以有这个需求的

**Comment by shi-yuan** [comment]
加这样一个配置项，可能是个鸡肋，还是想想其他的实现方式吧

**Comment by zozoh** [comment]
主要是担心这个口子一开，配置文件里，人们不太好找到底哪些是容器初始化时需要创建的 Bean。
虽然增强了功能，但可能是给大家挖的一个小坑

建议你要实现这个方法，可以在 MainSetup 里面读取一个配置文件，每行是一个 Bean 的名字，然后循环 Ioc.get 一下，这样，初始化的时候，就很容易用配置文件来指定哪些 Bean 需要初始化了。代码10行左右基本就搞定了，而且看起来还更清楚

**Comment by shi-yuan** [comment]
已实现，谢谢！
