### ISSUE TITLE
Cnd类为啥没有克隆方法呢? 

### ISSUE THREAD

**Issue by TopCoderMyDream** [nutzam/nutz#1366]
前段时间我需要在一个Cnd的实例基础上,更换添加若干且不同条件,这时候我需要保留当前Cnd对象,但是好像没有很好的解决办法
https://nutz.cn/yvr/t/r20l6tqfj6j2eqsvnnq2pgjds7
https://nutz.cn/yvr/t/ocn5em547ags1rb06pfbdjp4fi
社区提问后发现可以Cnd cnd2 = Cnd.where(cnd.where());这样来做,但是这样复制的只有where,其他的没有复制,不是根本的克隆对象,还有就是通过序列化来实现,但是好像序列化反序列化会比较消耗性能,所以想请问下Cnd类为啥不提供一个clone呢?

**Comment by ywjno** [comment]
不知道 cnd.getCri 里面有没有保存的条件

**Comment by wendal** [comment]
因为懒吧, 一般没这种需要

**Comment by TopCoderMyDream** [comment]
有呀,昨天我一个同事也需要了....可否加上嘛...

**Comment by ywjno** [comment]
或者你保存个 SqlExpression 对象，通过改变里面的值实现不同条件

**Comment by wendal** [comment]
你可以clone代码,然后尝试加一下嘛

**Comment by TopCoderMyDream** [comment]
我用序列化的方式加上去,各位有没有什么意见....
