### ISSUE TITLE
关于@Filters的使用方法

### ISSUE THREAD

**Issue by Rekoe** [nutzam/nutz#137]
下载了官方的cms DEMO 看了下 后台的权限管理功能只写好了数据结构 没有真正的实现权限控制，现在比较懵，不晓得怎么去实现这个权限控制，看了下官方help里的那个例子 太简单的，还真没明白具体个咋搞发，希望老大把这个功能的demo 完善一下！ 一直关注此帖！

**Comment by wendal** [comment]
3年了

**Comment by zozoh** [comment]
值得纪念

**Comment by Rekoe** [comment]
值得拥有

**Comment by wendal** [comment]
值得路过

**Comment by elkan1788** [comment]
期待能有个**shiro**的接口开放，官方出品赞一个**+1**！

**Comment by wendal** [comment]
已经提供shiro插件, 这个issue可以关掉了
