### ISSUE TITLE
EL表达式小问题反馈

### ISSUE THREAD

**Issue by zozoh** [nutzam/nutz#1372]
来自  `oscarjiang(姜凡) <oscarjiang@tencent.com>`:

尊敬的EL开发者，你们好！

    首先还是要非常感谢你们开源的EL表达式引擎。
你们的代码架构非常的优美。非常值得我们拜读和学习。
在引入到我们的项目中以后，一直以来也运转的非常好。
不过我们最近发现一个小问题。想跟你们反馈一下。
我们发现'&&'和'||'计算时，在要做类型强转时，会有点问题。
举例说明：
计算表达式："0 || 1"，本来的结果应该是true的，但是返回的却是false。
"&&"的计算也有同样的BUG。
通过翻阅EL的源码我们发现，左值做完类型强转以后，就直接返回了。没有考虑右值的情况。
对应的代码如下：

![catchf569](https://user-images.githubusercontent.com/174909/34341042-42620c20-e9ca-11e7-93a6-ccecf795ecc6.jpg)

我们这边会针对这个BUG自行修改一下。
但是觉得还是有必要知会一下你们这个问题。
请知悉。
谢谢。

**Comment by wendal** [comment]
他方便发个pull request吗？

**Comment by zozoh** [comment]
他应该有 github 账号吧，你在邮件里回一下问问。他们可能比较习惯用邮件方式追踪任务

**Comment by wendal** [comment]
额，电脑已关机 ，哈哈😄

**Comment by zozoh** [comment]
哦哦，我问吧
