### ISSUE TITLE
queryByJoin要进行分页查询的时候dao.count没有关联查询的方法，queryByJoin也没有去重的方式

### ISSUE THREAD

**Issue by jeasonsilver** [nutzam/nutz#1387]
queryByJoin要进行分页查询的时候dao.count没有关联查询的方法，queryByJoin也没有去重的方式（依据某个字段去重）

**Comment by jeasonsilver** [comment]
queryByJoin要进行分页查询的时候dao.count没有关联查询的方法，queryByJoin也没有去重的方式（依据某个字段去重）

**Comment by wendal** [comment]
嗯, 先用自定义SQL吧, 感觉实现起来还有点麻烦的样子...

**Comment by jeasonsilver** [comment]
太影响nutz实用效果啦，关联查询一般项目都会遇到的…^_^

**Comment by wendal** [comment]
明天想想怎么fix一下
