### ISSUE TITLE
Http Response 应该设计为immutable

### ISSUE THREAD

**Issue by lihongjie0209** [nutzam/nutz#1397]
首先是生产代码中遇到的问题:

```java
public class HttpTest {

        // this is ok
	@Test
	public void HttpResponse() throws Exception {
		Response response = Http.get("https://nutz.cn/yvr/list");
		String content = response.getContent();
		String content1 = response.getContent();

	}
        // java.lang.RuntimeException: java.io.IOException: Stream closed
	@Test
	public void HttpResponseGetContentWithCharSet() throws Exception {
		Response response = Http.get("https://nutz.cn/yvr/list");
		String content = response.getContent(StandardCharsets.UTF_8.name());
		String content1 = response.getContent(StandardCharsets.UTF_8.name());
	}
}


```

然后是这个接口存在的问题:
1. 根据CQS原则, Query不应该修改对象的内部状态, 但是带参数的`getContent`却把流给关闭了.
2. 从接口来看, `getContent()` 应该是 `getContent(chartsetname)` 使用一个默认的Charset, 但却不是.

最后希望可以:
1.  `getContent()` 和`getContent(chartsetname)` 表现应该是一致的
2.  `getContent()` 和 `getContent(chartsetname)` 不应该引起副作用
3.  response 对象中还有其他有副作用的函数希望修改一下

**Comment by lihongjie0209** [comment]
@wendal @zozoh

**Comment by wendal** [comment]
1. done
2. done
3. getStream() 和 getReader() 没法做到吧,除非缓存到文件

**Comment by lihongjie0209** [comment]
@wendal  调用前复制一份

**Comment by wendal** [comment]
怎么复制一个流对象? 给点示例代码看看?

**Comment by ywjno** [comment]
response 里面的内容不是只要触碰了一次之后就没法再获取到了么

**Comment by pangwu86** [comment]
get两次是什么需求？难道不是该自己缓存？

**Comment by lihongjie0209** [comment]
@pangwu86 作为一个查询函数, 调用多少次都不应该有问题

**Comment by lihongjie0209** [comment]
@wendal https://stackoverflow.com/questions/9501237/read-stream-twice

**Comment by wendal** [comment]
那是缓存到内存的，会死人的

**Comment by ywjno** [comment]
你说的是 http 协议的 get 方法吧

**Comment by lihongjie0209** [comment]
@wendal 好吧

**Comment by lihongjie0209** [comment]
@ywjno 我说的是有返回值的方法应该尽量没有副作用

**Comment by pangwu86** [comment]
查询？那是个io接口 一般来说io都是读一次就关闭的  需要多次使用就自己缓存

**Comment by lihongjie0209** [comment]
@wendal Java8中的buffer应该可以满足需求

**Comment by lihongjie0209** [comment]
@wendal 
问题在于可以调用`getContent()`多次, 因为Response缓存了String,
但是却不可以调用`getStream`多次, 因为流会被关闭
这就造成了不一致性, 可以参考 https://github.com/square/okhttp/issues/1240#issuecomment-329197762 

统一只能调用一次

**Comment by ywjno** [comment]
nutz是要支持jdk6的，那个buffer没法用

**Comment by lihongjie0209** [comment]
@ywjno 嗯, 这些都是实现的具体细节, 主要的想法还是保证了接口的一致性

> 问题在于可以调用getContent()多次, 因为Response缓存了String,
但是却不可以调用getStream多次, 因为流会被关闭
这就造成了不一致性, 可以参考 square/okhttp#1240 (comment)

> 统一只能调用一次
