### ISSUE TITLE
DaoUpTest注释写错了吧

### ISSUE THREAD

**Issue by shawn-show** [nutzam/nutz#1400]
// 移除前11个任务的引用
        for (int i = 0; i < 11; i++) {
            rootTeam.getJobs().remove(0);
        }
        dao.deleteLinks(rootTeam, null); // deleteLinks的特点就是当前对象引用的关联对象才会删除哦
        
        // 重新fetchLinks, 就剩下11个job了
        dao.fetchLinks(rootTeam, null);
        assertEquals(11, rootTeam.getJobs().size());
这个功能是保留前是一个，而不是移除前十一个吧

**Comment by wendal** [comment]
移除在java中的引用, 所以deleteLinks的时候就不会删除它们

**Comment by wendal** [comment]
done
