### ISSUE TITLE
org.nutz.lang.Stopwatch 秒表意见

### ISSUE THREAD

**Issue by Mr-GaoSai** [nutzam/nutz#1405]
public StopTag tag(String name) {
        if (tags == null)
            tags = new ArrayList<Stopwatch.StopTag>();
        lastTag = new StopTag(name, System.currentTimeMillis(), lastTag);
        tags.add(lastTag);
        return lastTag;
    }

tags是arraylist，此时如果只有一个tag，每次arraylist开辟默认10个的空间。再有我们没有随机访问tags的需求，所以这个改成linklist性能会好一些。拙见

**Comment by wendal** [comment]
好的,没毛病
