### ISSUE TITLE
请教 OpenAPI 中使用 Shiro 用户登录和鉴权问题?

### ISSUE THREAD

**Issue by hsxiaoma** [nutzam/nutz#1406]
## OpenAPI  应用场景

1. 根据 appid + appSecret 访问公开的接口数据
2. 用户登录并根据权限操作相关的接口

## 测试

- http://127.0.0.1:8080/open/api/token/get  正常
- http://127.0.0.1:8080/open/api/sys/login/doLogin 正常
- http://127.0.0.1:8080/open/api/sys/user/65e49a47971c4c3191c3cee78b09679e 异常

## 问题?

1. 参照 `NutzShop` 实现 `Shiro` 用户登录 经测试没有问题
2. 但当访问标有 ` @RequiresPermissions("sys.manager.user.add")` 的方法时, `NutShiroProcessor.java` 报
 `whenUnauthenticated` 登录失效 异常错误，也就意味着 第 1 步的登录无效。且返回的错误并不是 ajax 形式。

```
[DEBUG] 2018-03-22 23:56:12,060 cn.wizzer.app.web.commons.processor.NutShiroProcessor.whenException(NutShiroProcessor.java:60) - whenException >>>
[DEBUG] 2018-03-22 23:56:12,060 cn.wizzer.app.web.commons.processor.NutShiroProcessor.whenException(NutShiroProcessor.java:62) - whenException >>> null
[DEBUG] 2018-03-22 23:56:12,061 cn.wizzer.app.web.commons.processor.NutShiroProcessor.whenUnauthenticated(NutShiroProcessor.java:77) - whenUnauthenticated >>>
[DEBUG] 2018-03-22 23:56:12,062 cn.wizzer.app.web.commons.processor.NutShiroProcessor.whenUnauthenticated(NutShiroProcessor.java:78) - isAjax >>> false
[DEBUG] 2018-03-22 23:56:12,071 cn.wizzer.app.web.commons.processor.LogTimeProcessor.process(LogTimeProcessor.java:26) - [GET ]URI=/open/api/sys/user/65e49a47971c4c3191c3cee78b09679e 150ms
[DEBUG] 2018-03-22 23:56:12,084 org.nutz.mvc.impl.UrlMappingImpl.get(UrlMappingImpl.java:110) - Search mapping for [GET] path=/platform/login : NOT Action match
```

## 解决的思路

- 用户正确登录后，参照 `开放API` 的实现思路，使用 `用户ID + ...` 创建一个供登录用户使用的 `token` 
- 后端根据 `token` 如何通过  `Shiro`  鉴权？自己没有头绪

请高手帮助解决!

**Comment by Rekoe** [comment]
第三方登陆  参考 
https://github.com/Rekoe/nb_cms/blob/master/rest/src/main/java/com/rekoe/module/LoginModule.java
和shiro绑定需要调用 关键代码
```
Subject subject = SecurityUtils.getSubject();
		subject.login(new OAuthToken(openid, user.getId(), user.isLocked(), openid, request.getRemoteHost()));
		
```

**Comment by Rekoe** [comment]
另外问题可以去 社区问
nutz.cn
