### ISSUE TITLE
NutDao.fastInsert字段解析不全 

### ISSUE THREAD

**Issue by maxixi** [nutzam/nutz#1425]
如题，fastInsert传入List<Map<String, Object>>,当List中第一个Map里缺少某个字段时，导致插入到数据库中的所有记录都缺少那个字段。
如有张数据表结构为 Name CHAR(10) NULL, Age INT NULL
这个时候插入ArrayList： [{"Name": "name"}, {"Name": "name2", "Age": 15}]则会导致两条数据在数据库中均没有Age字段，调换两个Map的顺序则不会出现这个问题。
Nutz貌似是检测第一个Map的结构来决定插入到数据库的字段，某些情况下我们希望字段是可选的，我们在实际编码中也不会去留意字段（要不然我何不使用JavaBean），即，Nutz应该自动识别整个List<Map<String, Object>>中存在的字段，将没有的字段自动置为null，而不是一定要人工将没有值的字段置为null。请考虑修改或者或者提供fastInsert方法的重载方法fastInsert(T obj, boolean detectAllColumns)，虽然我们也可以自己将List<Map<String, Object>>中的所有Map补全字段，但是我们不想那样做，因为我们想忘了这个需要额外注意的地方，安心地写代码，然后代码按照我们的预期运行。

**Comment by wendal** [comment]
检测List里面map长度最大的那个, ok吗?

**Comment by maxixi** [comment]
目前我们是收集全部字段的，虽然有点浪费性能。最长的map不一定是全字段，如若这样做了导致插入不该出现的字段，那么用户自己应该对他传入的错误数据负责。

**Comment by wendal** [comment]
done

**Comment by ywjno** [comment]
这样的话还不如直接 insert 表全字段了
