### ISSUE TITLE
Sockets.localListen 方法无法持续工作。

### ISSUE THREAD

**Issue by albinhdk** [nutzam/nutz#1430]
我期望这个简单的Socket服务器，能响应不同的请求，并返回需要的数据。
但是事实上，目前只能接收到客户端（Sockets.send方法）发来的数据，但是如果使用socketContext.writeLine是无法返回数据的，必须抛出一个SocketException异常。

简单的说，希望有更优雅的方式处理这样的问题。

谢谢

**Comment by wendal** [comment]
已添加SocketContext.closeConn()方法
