### ISSUE TITLE
MultiLineProperties中线程安全问题

### ISSUE THREAD

**Issue by lihongjie0209** [nutzam/nutz#1433]
https://github.com/nutzam/nutz/blob/91a089b3e599ab1abc893d0ce6fde9b69135bcb5/src/org/nutz/lang/util/MultiLineProperties.java#L112-L118

读写共享可变量应该都要同步, 上述代码可能在一个线程拿到锁调用clear方法时另一个线程调用contain方法.

> 参考文献: <Java并发编程实战> 3.1.1 失效的数据

**Comment by wendal** [comment]
clear方法极少调用, 我觉得不必考虑吧...

**Comment by lihongjie0209** [comment]
@wendal 不只是clear  这只是一个例子, MultiLineProperties.java汇总所有的写操作都上锁, 但是读操作不上锁,

**Comment by wendal** [comment]
你觉得应该怎么改比较合适呢? maps属性换个线程安全的?

**Comment by lihongjie0209** [comment]
我也是刚看书的时候发现的, 按照<Java并发编程实战>的说法, 所有针对共享可变量的操作都要上锁.

**Comment by lihongjie0209** [comment]
@wendal 参考JDK的Properties实现, 我觉得可以使用线程安全的map.

**Comment by wendal** [comment]
ConcurrentHashMap ?

**Comment by lihongjie0209** [comment]
@wendal 嗯
> refer: https://stackoverflow.com/questions/1792023/thread-safe-map-for-java

**Comment by wendal** [comment]
那就换一下咯

**Comment by wendal** [comment]
然后去掉全部的同步, 来个pr?

**Comment by wendal** [comment]
主要代码格式化跟原版的一样...

**Comment by lihongjie0209** [comment]
@wendal 好像build失败了

**Comment by lihongjie0209** [comment]
@wendal load 操作是一个复合操作, 无法用concurrentMap来保证线程安全, 其他的同步可以取消
