### ISSUE TITLE
SimpleBlob类getBytes存在Stream未关闭问题

### ISSUE THREAD

**Issue by freefoxcm** [nutzam/nutz#1435]
SimpleBlob类的getBytes方法，使用了getBinaryStream创建了一个FileInputStream，但是readBytes后并没有将该Stream close掉。导致临时blob文件一直在处于打开状态，生产环境下导致too many open file异常。

**Comment by wendal** [comment]
啊啊啊啊啊啊啊啊啊啊啊啊啊啊,这就改

**Comment by wendal** [comment]
已修正

**Comment by freefoxcm** [comment]
OK




| |
陆俊
|
|
邮箱：lujuncm@163.com
|

签名由 网易邮箱大师 定制

在2018年08月13日 23:16，Wendal Chen 写道：

已修正
