### ISSUE TITLE
nutzDao bug

### ISSUE THREAD

**Issue by tomgor** [nutzam/nutz#1436]
分页查询的条件不能用Date类型，只能用字符串，呵呵。否则
Caused by: java.sql.SQLDataException: ORA-01861: 文字与格式字符串不匹配

**Comment by wendal** [comment]
给出完整可重现的代码和日志

**Comment by wendal** [comment]
没有后续了?

**Comment by tomgor** [comment]
等不及了，我老老实实用了字符串拼接，我用了最新的Dao，看了源码，你们在得到coutsql的时候，使用了Sql.toString,然后一切参数都是string

**Comment by wendal** [comment]
自定义sql? Daos.queryCount 可以传Sql对象了的

**Comment by tomgor** [comment]
自己来回复下吧：
    那个源码是我公司自己人封装了的垃圾，不是nutzDao的，哎。
    冤枉你了
