### ISSUE TITLE
Daos.migration对索引的处理

### ISSUE THREAD

**Issue by chenchi2038** [nutzam/nutz#1437]
在开发时发现`@TableIndexes`注解没有效果，查看nutz的源码发现`Daos.migration`里直接硬编码忽略了检查索引，有什么特别的原因么？
源码位置：
[https://github.com/nutzam/nutz/commit/5d455c9b3ea3c60d8be4376d6d23a0499bd2bc11#diff-ba45bfb6f6fe9f5993a962778dc7aadc](https://github.com/nutzam/nutz/commit/5d455c9b3ea3c60d8be4376d6d23a0499bd2bc11#diff-ba45bfb6f6fe9f5993a962778dc7aadc)

**Comment by wendal** [comment]
fixed
