### ISSUE TITLE
mvc @ Ok能不能加一点注解 方便使用

### ISSUE THREAD

**Issue by HaimmingYu** [nutzam/nutz#1447]
查看源码 org.nutz.mvc.annotation 注解 Ok 能不能写一些 使用方法 注释  
比如
@Ok("json:full")
返回所有字段
@Ok("json")
返回有值字段
 @Ok("json:{locked:'password|createAt|salt',ignoreNull:true}") // 忽略password和createAt属性,忽略空属性的json输出
方便使用

**Comment by wendal** [comment]
来个pull request试试?

**Comment by HaimmingYu** [comment]
原来如此

**Comment by wendal** [comment]
额, 老早以前配好的

**Comment by wendal** [comment]
fixed by @HaimmingYu
