### ISSUE TITLE
NestExps 里有手误代码？

### ISSUE THREAD

**Issue by wqmain** [nutzam/nutz#1453]
org.nutz.dao.util.cri.NestExps类的第28行代码出现了EXITSTS，SQL中不是 EXISTS吗？
是兽总手误了。。。还是我太浅鄙了？  -_-!

`/**
 * 逻辑基本与{@link Exps}类似,当传入Cnd.where()最后一个条件传入Nesting参数时会调用此类方法来构造sql条件.
 */
public class NestExps {
	public static NestingExpression eq(String name, Nesting val) {
		return new NestingExpression(name, "=", val);
	}

	public static NestingExpression notEq(String name, Nesting val) {
		return new NestingExpression(name, "<>", val);
	}

	public static NestingExpression like(String name, Nesting value) {
		return new NestingExpression(name, "LIKE", value);
	}

	public static NestingExpression inSql(String name, Nesting value) {
		return new NestingExpression(name, "IN", value);
	}

	public static NestingExpression exitsts(Nesting value) {
		return new NestingExpression(null, "EXITSTS", value);
	}

	public static NestingExpression otherSymbol(String name, String op, Nesting value) {
		return new NestingExpression(name, op, value);
	}`

**Comment by wqmain** [comment]
该类中的 create 方法也一样

`public static SqlExpression create(String name, String op, Nesting value) {
		op = Strings.trim(op.toUpperCase());
		if (value == null) {
			throw Lang.makeThrow("nesting sql can not be null'");
		} else if ("LIKE".equals(op) || "NOT LIKE".equals(op)) {
			return like(name, value).setNot(op.startsWith("NOT"));
		} else if ("=".equals(op)) {
			return eq(name, value);
		} else if ("!=".equals(op) || "<>".equals(op)) {
			return notEq(name, value);
		} else if ("IN".equals(op) || "NOT IN".equals(op)) {
			return inSql(name, value).setNot(op.startsWith("NOT"));
		} else if ("EXITSTS".equals(op) || "NOT EXITSTS".equals(op)) {
			// TODO op为EXITSTS的情况下,name!=null or name.length!=0 是否需要报错?
			return exitsts(value).setNot(op.startsWith("NOT"));
		}
		return otherSymbol(name, op, value);
	}`

**Comment by wqmain** [comment]
该类中的create方法也一样
`public static SqlExpression create(String name, String op, Nesting value) {
		op = Strings.trim(op.toUpperCase());
		if (value == null) {
			throw Lang.makeThrow("nesting sql can not be null'");
		} else if ("LIKE".equals(op) || "NOT LIKE".equals(op)) {
			return like(name, value).setNot(op.startsWith("NOT"));
		} else if ("=".equals(op)) {
			return eq(name, value);
		} else if ("!=".equals(op) || "<>".equals(op)) {
			return notEq(name, value);
		} else if ("IN".equals(op) || "NOT IN".equals(op)) {
			return inSql(name, value).setNot(op.startsWith("NOT"));
		} else if ("EXITSTS".equals(op) || "NOT EXITSTS".equals(op)) {
			// TODO op为EXITSTS的情况下,name!=null or name.length!=0 是否需要报错?
			return exitsts(value).setNot(op.startsWith("NOT"));
		}
		return otherSymbol(name, op, value);
	}`

**Comment by wendal** [comment]
噢, 来个pull request不?

**Comment by wqmain** [comment]
好哇，我是直接pull就可以吗？ 还是兽总需要给我开权限呢？

**Comment by TopCoderMyDream** [comment]
@wqmain  先fork到你到仓库，提交到你到仓库再从github发起pr

**Comment by TopCoderMyDream** [comment]
将修改提交到你自己的仓库再发PullRequest

**Comment by wendal** [comment]
貌似解决了 @TopCoderMyDream
