### ISSUE TITLE
集成slf4j的日志插件

### ISSUE THREAD

**Issue by qinerg** [nutzam/nutz#1458]
随着技术栈的不断升级，目前第三方的jar均已使用slf4j来进行日志输出，使用nutz时还需要加入log4j-1.2-api进行桥接，已稍感不便。
建议直接集成slf4j的插件，可与log4j插件并存，当未检测到slf4j存在时，则仍然切换至log4j去。岂不更好？

**Comment by lihongjie0209** [comment]
观望中

**Comment by wendal** [comment]
https://github.com/nutzam/nutzboot/tree/dev/nutzboot-core/src/main/java/org/nutz/log/impl

就是把这2个类放进来... 到底要不要放呢... 好纠结...

**Comment by Wizzercn** [comment]
向下兼容就好，放了不影响老项目的话……

**Comment by wendal** [comment]
嗯, 不是编译nutz源码的话, 对老项目没影响

**Comment by wendal** [comment]
那我们就加上吧? 各位还有什么补充吗?

**Comment by Wizzercn** [comment]
木

**Comment by wendal** [comment]
done

**Comment by qinerg** [comment]
赞！！！
