### ISSUE TITLE
Sql可不可以控制querytimeout

### ISSUE THREAD

**Issue by sillyfeng** [nutzam/nutz#1469]
如题，我们用的是1.r.60版本。 有些大的查询，需要设置一下超时时长。但是没有找到sql里有类似设置timeout的api。不知道有没有这样的实现限制。

**Comment by Wizzercn** [comment]
这个是数据库配置项~~

**Comment by sillyfeng** [comment]
@Wizzercn 百度好像说这个不能 配置在连接串上。可以在查询的时候设置在 statement上，老铁有类似配置吗？

**Comment by wendal** [comment]
哪款连接池,druid吗?

**Comment by wendal** [comment]
druid的话, 有queryTimeout属性

**Comment by sillyfeng** [comment]
@wendal 赞，昨天没有及时看，我们用的连接池是weblogic自带的。这样控制在statement上很灵活了。感谢！！
