### ISSUE TITLE
Math.max(20,-20)用过个方法在El.eval中解析时，程序报空指针异常。

### ISSUE THREAD

**Issue by DavidZky** [nutzam/nutz#1476]
Math.max(20,-20)用过个方法在El.eval中解析时，程序报空指针异常。 xception in thread "main" java.lang.NullPointerException at org.nutz.el.opt.object.AccessOpt.run(AccessOpt.java:53) at org.nutz.el.opt.object.MethodOpt.calculate(MethodOpt.java:45) at org.nutz.el.opt.object.InvokeMethodOpt.calculate(InvokeMethodOpt.java:22) at org.nutz.el.opt.object.AccessOpt.fetchVar(AccessOpt.java:80) at org.nutz.el.opt.object.AccessOpt.run(AccessOpt.java:50) at org.nutz.el.opt.object.MethodOpt.calculate(MethodOpt.java:45) at org.nutz.el.opt.object.InvokeMethodOpt.calculate(InvokeMethodOpt.java:22) at org.nutz.el.opt.AbstractOpt.calculateItem(AbstractOpt.java:49) at org.nutz.el.opt.object.MethodOpt.fetchParam(MethodOpt.java:68) at org.nutz.el.opt.object.MethodOpt.calculate(MethodOpt.java:45) at org.nutz.el.opt.object.InvokeMethodOpt.calculate(InvokeMethodOpt.java:22) at org.nutz.el.arithmetic.RPN.calculate(RPN.java:55) at org.nutz.el.arithmetic.RPN.calculate(RPN.java:46) at org.nutz.el.El.eval(El.java:45) at com.Test.calc(Test.java:217) at com.Test.main(Test.java:55)

**Comment by zozoh** [comment]
@juqkai 有空看看不

**Comment by wendal** [comment]
我看一眼吧

**Comment by wendal** [comment]
Math并不是内置对象, 要用 `max(20,-20)`
