### ISSUE TITLE
Record.toPojo时属性大小写不同赋值为空

### ISSUE THREAD

**Issue by belialofking** [nutzam/nutz#1479]
public <T> T toPojo(Class<T> type) {
        return Lang.map2Object(this.map, type);
    }
由于调用时传入的参数为this.map,导致属性中有大写字母时不能赋上对应的值.
原因是this.map类型为LinkedHashMap,判断key时区分大小写
应该改为
public <T> T toPojo(Class<T> type) {
        return Lang.map2Object(this, type);
    }
Record会自动将key转换为小写,这样可以将对应的属值取到

**Comment by wendal** [comment]
merged
