### ISSUE TITLE
Json输出字段加解密

### ISSUE THREAD

**Issue by howe** [nutzam/nutz#1492]
求个输出加解密，例如 @JsonField(encode="md5") @JsonField(decode="base64") @wendal

**Comment by Wizzercn** [comment]
和出入库字段加解密需求类似，也来个？

**Comment by zozoh** [comment]
@howe  为啥不直接设置一下呢？ MD5 这种东东是非对称的，加密了就不能解了

**Comment by howe** [comment]
@zozoh 本来就是展示时是加密的 类似我有些ID 就不能显示数字

**Comment by happyday517** [comment]
写个自定义的getter，加`@JsonField`就ok了
或者直接上`@ToJson`

**Comment by wendal** [comment]
不是非对称,是不可逆

**Comment by howe** [comment]
一般这种都是展示用的

**Comment by zozoh** [comment]
@howe  主要是站的角度不同。从使用者角度，当然是有需要的功能，框架直接就有，省了很多事。
但是从框架维护者的角度，需要思考的膨胀问题。如果一个不是非常普遍的需求，框架针对做了修改，那么同等级别的需求（场景不普遍但是五花八门）框架要不要改？如果改了，那么就会不可遏制的膨胀。其后果很可能导致“笨重”。 因为涉及到“破窗原理”，即，这都改了，那那什么什么为啥不支持一下？

针对这个需求，说特别特殊也不是，说特别普遍也不是，正好是一个比较灰色的地带。通常，业务程序员在自己的帮助函数库（一个项目总要自己写点业务的帮助函数的）上加一个帮助方法就是，譬如：

```java
public Object encodeObject(Object in, String[] fields) {
   // 这里针对字段 fields 做加密
}
```

也不用多少行就能解决问题，而 Nutz 的 `Mirror` 等帮助类就是能帮你比较轻便高效的完成这种操作

所以作为框架的维护者会比较小心这种灰色地带的需求场景，如果接受了这种场景，就会导致框架的边界扩大，这个通常是我们比较警惕的。我想，我们最好在观望一下这个 Issue 看看有没有更多的人对此 `+1` 如果人多了，说明这个场景其实挺普遍，支持它是很划算的事情，如果不是，我想提供在 `demo` 库提供个帮助函数的示例应该是个更好的选择。 ^_^

**Comment by howe** [comment]
@zozoh 那有人提issue时 教人咋处理蛮好的 直接加到nutz.cn论坛里
