### ISSUE TITLE
AbstractPathView.createContext中添加扩展点

### ISSUE THREAD

**Issue by juqkai** [nutzam/nutz#1503]
在进行模板渲染时除了会使用到现在定义到的属性与变量，还有可能使用一些公共的变量。
比如一些工具类，配置信息什么的。

现在这个方法中缺乏这方面的支持，要注入额外的数据比较麻烦

**Comment by wendal** [comment]
公共变量? beetl?? 注入到beetl的全局变量map就好了

**Comment by juqkai** [comment]
用的是thymeleaf， 

在 [nutz-plugins-multiview 多视图插件](https://github.com/nutzam/nutzmore/tree/master/nutz-plugins-multiview#未来规划) 的未来规划中有提到这个功能。

使用beetl的全局变量注入算是beetl的功能，而nutz是缺少这个扩展点的，对没有全局变量的模板不友好。

**Comment by wendal** [comment]
有实现思路不?
