### ISSUE TITLE
Store of non serializable object into HttpSession

### ISSUE THREAD

**Issue by TomYule** [nutzam/nutz#1515]
https://github.com/nutzam/nutz/blob/master/src/org/nutz/mvc/ioc/SessionIocContext.java
Store of non serializable object into HttpSession
This code seems to be storing a non-serializable object into an HttpSession. If this session is passivated or migrated, an error will result.
```
    public boolean save(String scope, String name, ObjectProxy obj) {
        if (null != scope && "session".equals(scope)) {
            session.setAttribute(name, obj);
            return true;
        }
        return false;
    }
```

**Comment by wendal** [comment]
其实... 这个是废弃的功能... 不过ObjectProxy加个序列化也是没问题的

**Comment by wendal** [comment]
看了看, 感觉做不了... 不管了
