### ISSUE TITLE
Possible double check of field

### ISSUE THREAD

**Issue by TomYule** [nutzam/nutz#1517]
https://github.com/nutzam/nutz/blob/master/src/org/nutz/mvc/ioc/WebFilterProxy.java
https://github.com/nutzam/nutz/blob/master/src/org/nutz/mvc/impl/processor/MethodInvokeProcessor.java
https://github.com/nutzam/nutz/blob/master/src/org/nutz/mvc/impl/session/AbstractSessionProvider.java

This method may contain an instance of double-checked locking.  This idiom is not correct according to the semantics of the Java memory model.  For more information, see the web page http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html

**Comment by wendal** [comment]
double check 没问题的
