### ISSUE TITLE
Incorrect lazy initialization of static field

### ISSUE THREAD

**Issue by TomYule** [nutzam/nutz#1518]
https://github.com/nutzam/nutz/blob/master/src/org/nutz/http/Sender.java
```
    public static ExecutorService setup(ExecutorService es) {
        if (Sender.es != null) {
            shutdown();
        }
        if (es == null) {
            //创建线程池
            es = Executors.newScheduledThreadPool(64);
        }
        Sender.es = es;
        return es;
    }
```
```
        if (Sender.es != null) {
            shutdown();
        }
```
This method contains an unsynchronized lazy initialization of a non-volatile static field. Because the compiler or processor may reorder instructions, threads are not guaranteed to see a completely initialized object, if the method can be called by multiple threads. You can make the field volatile to correct the problem. For more information, see the [Java Memory Model web site.](http://www.cs.umd.edu/~pugh/java/memoryModel/)

**Comment by wendal** [comment]
用法问题, 这个方法只应调用一次
