### ISSUE TITLE
macOS + mysql 8.0.15 数据库初始化错误

### ISSUE THREAD

**Issue by thincamel** [nutzam/nutz#1529]
日志：
2019-10-17 14:59:09.407 DEBUG org.nutz.dao.impl.sql.run.NutDaoExecutor Line:103 - SQLException
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'grouping BOOLEAN COMMENT '枚举分组',
mark VARCHAR(128) COMMENT '描述',

grouping中包含mysql保留字 group，需要用`grouping`

**Comment by thincamel** [comment]
类似还有 表sys_data_fields中  `system` BOOLEAN DEFAULT 0 COMMENT '是否系统字段'

system也需要用反单引号括起来

**Comment by Wizzercn** [comment]
用保留字，是bug？

**Comment by thincamel** [comment]
> 用保留字，是bug？

我本机的环境看：macOS Catalina 10.15.1 + mysql 8.0.15  运行初始化时，只要有类似保留字的都报错，在对应建立的本地数据库中这些表也未创建成功。

**Comment by Wizzercn** [comment]
@thincamel Daos.CHECK_COLUMN_NAME_KEYWORD

**Comment by wendal** [comment]
同上
