### ISSUE TITLE
Scans类扫描springboot打包那JAR包时,会有扫描不到的情况

### ISSUE THREAD

**Issue by belialofking** [nutzam/nutz#1533]

**Comment by wendal** [comment]
https://github.com/nutzam/nutzmore/blob/master/nutz-integration-spring/src/main/java/org/nutz/integration/spring/SpringResourceLoaction.java

**Comment by belialofking** [comment]
你理解错了,我不想NUTZ和SPRING一起用,我只是想用spring-boot-maven-plugin打包,用这个插件打出来的包执行时,用Scans扫描会找不到类.
jar:file:/Users/target/NutzTest-1.0-SNAPSHOT.jar!/BOOT-INF/classes!/
有一部分类会在这个下面,
Scans中的具体代码还没太看明白,可能是下面的代码导致,
return ResourceLocation.jar(str.substring(0, str.lastIndexOf("jar!") + 3));
也可能是JarResourceLocation类里

**Comment by wendal** [comment]
是否一起用, 都可以的. 加入那个类就可以了
