### ISSUE TITLE
ThreadLocal listenerH的作用

### ISSUE THREAD

**Issue by ahxm** [nutzam/nutz#1540]
if (listenerH.get() != null) {
                                op = maker.make(ing, iobj);
                            }
                            else {
                                try {
                                    listenerH.set(Boolean.TRUE);
                                    op = maker.make(ing, iobj);
                                }
                                finally {
                                    listenerH.remove();
                                }
                            }

请问这段代码 ThreadLocal listenerH的使用起什么作用？如果去掉ThreadLocal listenerH会有什么结果？

**Comment by wendal** [comment]
标识符, 循环依赖的时候起作用

**Comment by wendal** [comment]
你要是想深究一下, 下载源码, 把TestAll跑起来, 然后试试修改,看看有没有testcase不通过
