### ISSUE TITLE
使用PATCH方式请求Gitea时，Gitea日志显示为POST请求，无法进入PATCH请求处理

### ISSUE THREAD

**Issue by jacky-2014-sn** [nutzam/nutz#1546]
使用PATCH方式请求Gitea时，Gitea日志显示为POST请求，无法进入PATCH请求处理

从Sender.java源码看，PATCH的处理确实是一个POST

conn.setRequestProperty("X-HTTP-Method-Override", "PATCH");
conn.setRequestMethod("POST");

现在的PATCH请求是否需要进行conn.setRequestMethod("PATCH");处理

**Comment by jacky-2014-sn** [comment]
从Sender.java源码看，PATCH的处理确实是一个POST

**Comment by wendal** [comment]
用 request.setMethodString("PATCH")就肯定行
