### ISSUE TITLE
建议nutz dao cnd引入新重载函数

### ISSUE THREAD

**Issue by hanjieliao** [nutzam/nutz#1555]
大佬， 提个建议。 我们 nutz dao 是否可以考虑加入，新的重载函数，cnd更好用一些
举个例子，我们cnd是这样查询的

> Cnd cnd = Cnd.where("server_id", "=", serverId);
> cnd.and("order_time", "=", orderTime);
>  return getByCnd(cnd);

mybatis-plus是这样查询的
> QueryWrapper<OrderDetail> queryWrapper = new QueryWrapper<>();
> queryWrapper.lambda().eq(OrderDetail::getServerId, serverId);
> queryWrapper.lambda().eq(OrderDetail::getOrderTime, orderTime);
> OrderDetail orderDetail = getOne(queryWrapper);

引入lamda以后，字段名变了，用到这个字段的代码都会红叉警告，好像方便点。 当然好像也有弊端，我感觉这种lamda的方式条件多了，看起来不太直观，像下面这种
> //SELECT * FROM order_detail WHERE start_time <= @1 AND (end_time >= @1 OR end_time is null)
>  QueryWrapper<OrderDetail> queryWrapper = new QueryWrapper<>();
> queryWrapper.lambda().le(OrderDetail::getStartTime, localDateTime);
> queryWrapper.and(q -> q.lambda().ge(OrderDetail::getEndTime, localDateTime).or().isNull(OrderDetail::getEndTime));
> List<OrderDetail> list = list(queryWrapper);

所以就是提个建议哈

**Comment by wendal** [comment]
想想怎么实现, 这语法还不熟...

**Comment by realoldroot** [comment]
看起来不错的样子:flushed:

**Comment by Kerbores** [comment]
lamdaQuery 是个好想法，硬编码的不管是数据库字段还是类属性都没有编译检查，用上这个就有编译检查了

**Comment by lihongjie0209** [comment]
@Kerbores 直接使用@FieldNameConstants 就可以了

**Comment by chengyuxing** [comment]
`@Test
    public void FConditionTest() throws Exception {
        FCondition<User> f = FCondition.<User>builder().where(FFilter.eq(User::getName, "cyx"))
                .and(FFilter.eq(User::getPassword, "123456"), FFilter.eq(User::getName, "admin"))
                .or(FFilter.like(User::getName, "%admin"))
                .orderBy(User::getAge);

        System.out.println(f.getArgs());
        System.out.println(f.toString());
    }`
实现了下，实际上感觉不太好用

**Comment by Kerbores** [comment]
> @Kerbores 直接使用@FieldNameConstants 就可以了

不错,如果项目在用lombok的话

**Comment by Kerbores** [comment]
> ```
> @Test
>     public void FConditionTest() throws Exception {
>         FCondition<User> f = FCondition.<User>builder().where(FFilter.eq(User::getName, "cyx"))
>                 .and(FFilter.eq(User::getPassword, "123456"), FFilter.eq(User::getName, "admin"))
>                 .or(FFilter.like(User::getName, "%admin"))
>                 .orderBy(User::getAge);
> 
>         System.out.println(f.getArgs());
>         System.out.println(f.toString());
>     }
> ```
> 
> 实现了下，实际上感觉不太好用

pr到feature/lamda-query分支看看
