### ISSUE TITLE
需求: 事务异常回滚 希望可以通过注释 实现

### ISSUE THREAD

**Issue by TomYule** [nutzam/nutz#1558]
如题spring 下面 事务 可以酱紫定义 就可以用
`  @Transactional(rollbackFor=Exception.class)`
nutz 加入事务之前的样子
```
    /**
     * 更新角色
     *
     * @param data
     * @return
     */
    @Override
    public int update(Role data) {
        List<String> ids = new ArrayList<>();
        if (data != null && data.getMenuIds() != null) {
            if (Strings.isNotBlank(data.getMenuIds())) {
                ids = Arrays.asList(data.getMenuIds().split(","));
            }
            //清除已有关系
            Role tmpData = this.fetch(data.getId());
            this.fetchLinks(tmpData, "menus");
            dao().clearLinks(tmpData, "menus");
        }
        if (ids != null && ids.size() > 0) {
            Criteria cri = Cnd.cri();
            cri.where().andInStrList("id", ids);
            List<Menu> menuList = menuService.query(cri);
            data.setMenus(menuList);
        }
        int count = dao().update(data);
        dao().insertRelation(data, "menus");
        return count;
    }
```

加入后

    /**
     * 更新角色
     *
     * @param data
     * @return
     */
    @Override
    public int update(Role data) {
        final int[] count = {0};
        // Begin transaction
        Trans.exec(new Atom() {
            @Override
            public void run() {
                List<String> ids = new ArrayList<>();
                if (data != null && data.getMenuIds() != null) {
                    if (Strings.isNotBlank(data.getMenuIds())) {
                        ids = Arrays.asList(data.getMenuIds().split(","));
                    }
                    //清除已有关系
                    Role tmpData = fetch(data.getId());
                    fetchLinks(tmpData, "menus");
                    dao().clearLinks(tmpData, "menus");
                }
                if (ids != null && ids.size() > 0) {
                    Criteria cri = Cnd.cri();
                    cri.where().andInStrList("id", ids);
                    List<Menu> menuList = menuService.query(cri);
                    data.setMenus(menuList);
                }
                count[0] = dao().update(data);
                dao().insertRelation(data, "menus");
            }
        });
        // End transaction
        return count[0];
    }

**Comment by wendal** [comment]
http://nutzam.com/core/aop/aop_trans.html 差不多效果吧
