### ISSUE TITLE
查出来的tinyint字段被转成了bool值

### ISSUE THREAD

**Issue by Younsion** [nutzam/nutz#1573]
查出来的：
![image](https://user-images.githubusercontent.com/26084893/108987267-0be79900-76ce-11eb-920d-4c3ea1dd893d.png)

数据库中的类型：
![image](https://user-images.githubusercontent.com/26084893/108987345-215cc300-76ce-11eb-806d-283041e50604.png)

版本：1.r.65

**Comment by wendal** [comment]
正常操作

**Comment by wendal** [comment]
你想强制类型的话, 走Pojo类嘛

**Comment by Younsion** [comment]
我原本是不想建pojo才用这个的😂
我现在的解决方法是在查询的时候转换对应的类型为int，给后来者一个参考。如下：
![image](https://user-images.githubusercontent.com/26084893/109096494-98d73480-7758-11eb-899b-dac1474c6c13.png)
