### ISSUE TITLE
【建议】新增：Record转T类型方法

### ISSUE THREAD

**Issue by lmm1990** [nutzam/nutz#1574]
临时解决办法：
自己写了个util

使用方法：
Entity<UserInfo> entity = NutzEntityUtil.getEntity(UserInfo.class);
Record result = userService.get(id,"id,nickName");
UserInfo userInfo = entity.getObject(result);

附件：
[NutzEntityUtil.java.txt](https://github.com/nutzam/nutz/files/6040581/NutzEntityUtil.java.txt)

**Comment by threefish** [comment]
` Lang.map2Object(record, UserInfo.class);`
就可以了

**Comment by lmm1990** [comment]
好的，多谢
