### ISSUE TITLE
dao生成SQL有误

### ISSUE THREAD

**Issue by enzozhong** [nutzam/nutz#1584]
代码
var_cnd = Cnd.where ( "stockInfoId" , "=" , stockInfoId ).and ( "trade_date" , "=" , _trade_date );
var object = dao.fetch ( tableNameFMACross , cnd , "id,stockInfoId,trade_date" );

备注
stockInfoId                  long
_trade_date                 date
tableNameFMACross  string，

日志
显示生成的SQL 为
"SELECT id,stockInfoId,trade_date FROM tableNameFMACross  WHERE stockInfoId=1 ORDER BY trade_date ASC   LIMIT 0, 1 "

应该生成 WHERE stockInfoId=1 AND trade_date = '_trade_date ‘  LIMIT 0, 1 "
实际生成 WHERE stockInfoId=1 ORDER BY trade_date ASC   LIMIT 0, 1 "

**Comment by threefish** [comment]
我觉得是你自己使用错误，代码行1变量是 '_cnd' 代码行 使用时却变成了 'cnd' 了。

**Comment by enzozhong** [comment]
> 我觉得是你自己使用错误，代码行1变量是 '_cnd' 在代码行2使用时却变成了 'cnd' 了。

好眼力
