### ISSUE TITLE
事务文档完善

### ISSUE THREAD

**Issue by flymichael** [nutzam/nutz#167]
Nutz针对事务方面的文档需要加强，困扰来源于Wandal的博客文档与官方文档对于细节描述的差异。官方文档写到只要代码被原子包装，来自于对多个数据源的操作可保持事务完整，但在Wandal的博客中指出，需要采用XA驱动才能保持分布式数据源的事务同步，前置不仅仅是使用原子包裹操作代码。这方面文档需要加强，否则对严格要求事务的系统会产生严重后果。

**Comment by wendal** [comment]
已经写了
