### ISSUE TITLE
Nutz.Mvc 支持的特殊参数类型增加Cnd类型

### ISSUE THREAD

**Issue by btboys** [nutzam/nutz#177]
Nutz.Mvc 支持的特殊参数类型增加Cnd类型，并且最好是传过来的cnd是根据特殊标识的req参数，自动拼装好的cnd对象。这样可以方便简单多字段的查询吧····

**Comment by wendal** [comment]
如果Cnd有个from(Map m)方法的话就行咯,但没啥用
