### ISSUE TITLE
$condition 方式实际执行不是 PreparedStatement  方式吗?

### ISSUE THREAD

**Issue by ming300** [nutzam/nutz#219]
String sqltxt = "SELECT  id FROM pf_dict $condition";

SimpleCriteria cri = Cnd.cri();
cri.where().and("TYPE", "=", "CATALOG");
Sql sql = Sqls.create(sqltxt);
sql.setCondition(cri);

nutDao.execute(sql);

发现这种方式执行的查询不是吧查询条件按 ?进行拼凑的,而是直接拼凑的一个完整sql,请证实,

实际执行的sql:
SELECT  id FROM pf_dict where TYPE='CATALOG';

期望的sql

SELECT  id FROM pf_dict where TYPE=?;

我印象中,以前的版本是正常的.

SimpleCriteria cri = Cnd.cri();
和Cnd.Where()方式一样

**Comment by wendal** [comment]
好吧,无法解决...
