### ISSUE TITLE
@InjectName职责不清楚

### ISSUE THREAD

**Issue by juqkai** [nutzam/nutz#242]
@InjectName 注解职责不清楚. 在MVC与IOC中是两个不同的意义.

在MVC中, 它指代, 如果下次再取这个Module的时候, 根据InjectName.value从IOC中取.

而在IOC中, 因为并不存在说下次取这个对象时根据什么来取的说法, 所以, 它的职责被赋予了, 保存当前对象到IOC容器时, 可以使用InjectName.value来做KEY进行保存.

这里面形成了两个完全不同的职责, 而且还是完全相反的两个职责, 一个是取时的key, 一个却是存时的key.

所以, 建议, 去掉, IOC中InjectName的职责. 

或者. 如果在IOC中使用InjectName, 那么, 接口默认取某个KEY的实现做为默认实现.

如:
{{{<java>

@InjectName("a2")
interface A{}

@IocBean
class A1 implements A{}

@IocBean
class A2 implements A{}

@IocBean
class B {
    @Inject
    A a;
}

}}}

在B类中, A的inject注解上没有写明是使用那个实现, 但是在A接口中使用了InjectName, 那么, 可以认为默认使用A2类的实现.

**Comment by wendal** [comment]
这就这样了
