### ISSUE TITLE
从文件池中获取/删除一个文件,为什么要我指定后缀名呢

### ISSUE THREAD

**Issue by conanca** [nutzam/nutz#282]
File f = pool.removeFile(239, ".png");
File f = pool.getFile(239, ".png"); 

这样个方法用的时候，需要指定后缀名，用起来很别扭啊。

有没有办法改一下，去掉后缀名这个参数。

记得一年前跟兽提过，后来没再管，最近又碰到这个问题了，如果不需要指定后缀名，对我来说功能实现起来简便许多

**Comment by wendal** [comment]
无法fix的东西
