### ISSUE TITLE
SqlExpressionGroup的andInBySql不是转化为PreparedStatement的执行方式？

### ISSUE THREAD

**Issue by eyougo** [nutzam/nutz#340]
Criteria cri = Cnd.cri();
cri.where().andInBySql("application_id","select root from application where user_id=?", new int[]{2});

andInBySql(String name, String subSql, Object... args)
我原以为args和subSql搭配是为了使用PreparedStatement，但实际输出却不是，
查源码一看，在SqlRange里只是
public SqlRange(String name, String fmt, Object... args) {
        super(name);
        this.not = false;
        this.sql = String.format(fmt, args);
    }
用了String.format方法格式化语句参数而已。
我觉得对于Dao层框架来说，比格式化参数更重要的是使用PreparedStatement来使用参数，毕竟让使用者自己去String.format一下可以，但不用PreparedStatement的话效率确实受到影响。
因此我希望改成实际执行为PreparedStatement……

**Comment by wendal** [comment]
1.b.53 自定义Sql开始支持多个Cnd, 所以这种问题就自然解决啦
