### ISSUE TITLE
关于多对多更新的问题

### ISSUE THREAD

**Issue by windsummer** [nutzam/nutz#393]
以文档中的Master和Pet为例，目前一对多更新操作提供同时更新 pet 和 master以及仅仅更新 pets这两个方法，但是如果想要更新master并且同时更新与pet之间的关联有关系似乎只能通过：
1.先更新master; 
2.清除与pet之间的关联关系 ; 
3.重新建立与master与pet之间的关联关系。
步骤有点繁琐，是否可以提供一个这样的功能呢？

**Comment by wendal** [comment]
@zozoh 怎么看?
