### ISSUE TITLE
多重子模块的功能

### ISSUE THREAD

**Issue by kyo19** [nutzam/nutz#412]
MainModule-->A模块-->A模块的子模块1->A模块的子模块1的具体模块X
![ ](https://f.cloud.github.com/assets/922092/230880/617b5da8-86da-11e2-8e9c-648e4f92d041.jpg)

像这样，icommunity是主模块，其它是这个项目 的子功能模块

主功能模块的url是“http://localhost/"
想对应该的子模块：“http://localhost/uic/xxxx",http://localhost/app/xxxxx

但Nutz目前版本没办法对子模块的URL进行一个统一的配置，必须在当对子模块 中的每个Controller类的前面加一个At("/uic")或是At("/app")，希望能在子模块中增加一个SubModule，只要在这个配置一个命名空间，然后这个模块的所有URL都带有这个前缀

如
@SubMod("/uic")
public class SubIcomm extends SubModule{.........}

然后所有这个模块的Url都是  http://localhost/{submodule_name}/xxxx/xxxx

**Comment by wendal** [comment]
已经没人提了
