### ISSUE TITLE
MVC不支持request.include

### ISSUE THREAD

**Issue by juqkai** [nutzam/nutz#431]
内部的如果使用include跳转:
request.getRequestDispatcher(strPath).include(wrappedRequest, wrappedResponse);

因为request中的URI还是之前的, 但却多了requestDispatcherPath属性, 而NUTMVC好象没有对它进行处理, 所以就会导致还是处理原始的URI, 从而导致循环调用.

另外要使用INCLUDE需要添加:

    <filter-mapping>
		<filter-name>nutz</filter-name>
		<url-pattern>/*</url-pattern>
		<dispatcher>REQUEST</dispatcher>
		<dispatcher>FORWARD</dispatcher>
		<dispatcher>INCLUDE</dispatcher>
	</filter-mapping>

**Comment by lAndRaxeE** [comment]
遇到同样的问题和需求，不明白为什么这个issue直接关闭，而没有任何说明？

**Comment by wendal** [comment]
因为没有后续讨论, 太久了,所以关掉了

@lAndRaxeE 描述下你的场景??

**Comment by lAndRaxeE** [comment]
当时在忙项目，一直没再会来关注。具体的场景已经记不太清楚了，大概就是：
页面上需要include一个页面，而这个页面不是死的，需要 一定的逻辑，所以是include的一个controller入口，结果就死循环了。

我再回忆回忆，如果能想起来再补充吧
@wendal
