### ISSUE TITLE
能否像SpringMVC一样配置视图

### ISSUE THREAD

**Issue by denghuafeng** [nutzam/nutz#439]
Spring mvc
@Controller
@RequestMapping("/test/")
public class Test {
@RequestMapping("/insert")
public String insert(){
	
}
}
Spring根据这个请求的地址来寻找 默认配置的视图的扩展名相对应的文件，比如默认视图是freemarker,扩展名是htm,则能找到
/test/insert.htm

Nutz能这样吗？
@At("/test")
public class Test {
@At
public String insert(){
	
}
}
能通过配置文件，找到/test/insert.htm？
这种@Ok("jsp:test.insert")，这个“jsp:”始终觉得是硬编码，即使是这样
@At("/test")
public class Test {
@At
@Ok("jsp")
public String insert(){
	
}
}
“jsp”写在代码就是硬编码，通过配置文件形式来配置，方面切换视图维护。

**Comment by wendal** [comment]
类似@Ok("re")
