### ISSUE TITLE
mvc-ioc session 级别获取对象在同一session下总是新生成对象。

### ISSUE THREAD

**Issue by zouooh** [nutzam/nutz#485]
1.dao : {
		type : "org.nutz.dao.impl.NutDao",
		args : [ {
			refer : "dataSource"
		} ]
	},
2.@IocBy(type=JsonIocProvider.class, args={"dbConfig.js"})
3.Dao  dao = Mvcs.getIoc().get(null, "dao");
刷新页面：
![qq20130705191919](https://f.cloud.github.com/assets/4947781/753322/11d5d82a-e565-11e2-8464-33c78e6108ce.jpg)
![qq20130705191927](https://f.cloud.github.com/assets/4947781/753329/39873c38-e565-11e2-9c5c-cc17c683896f.jpg).

个人猜测：ioc生成对象后没有保存。 
谢谢。

**Comment by wendal** [comment]
别用session scope
