### ISSUE TITLE
Files.appendWrite编码问题

### ISSUE THREAD

**Issue by juqkai** [nutzam/nutz#486]
当使用Files.appendWrite(file, text)输出到文件时, 会导致生成的文件编码是操作系统默认的编码. 如果直接调用Files.read会导致乱码问题. 因为read默认是使用UTF-8的.

之所以会导致输出文件编码是操作系统编码, 是因为Streams.appendWriteAndClose中使用的是FileWriter

**Comment by wendal** [comment]
传入一个合适writer就可以了吧?
