### ISSUE TITLE
Nutz Uploader 文件池文件覆盖问题

### ISSUE THREAD

**Issue by aaronlu1985** [nutzam/nutz#535]
如果在多个Module中配置相同的上传路径，如下
@AdaptBy(type = UploadAdaptor.class, args = { "${app.root}/WEB-INF/tmp" })
会出现${app.root}/WEB-INF/tmp文件夹下文件被覆盖的问题

但是如果使用ioc配置方式的话，此问题不会存在

**Comment by wendal** [comment]
恩,是的, 只能ioc解决
