### ISSUE TITLE
sqlserver 添加韩语(Unicode)失败

### ISSUE THREAD

**Issue by zhuer0632** [nutzam/nutz#537]
在 Microsoft SQL Server 中, 以下数据类型支持 Unicode 数据：
nchar, nvarchar, ntext
使用SQL语句操作的时候应该注意以下问题：
原查询语句
Select * From TABLENAME Where field1 like '%xxx%'
使用 Unicode 数据类型的, 应该为:
Select * From TABLENAME Where field1 like N'%xxx%'
插入数据也一样
INSERT INTO TABLENAME(Detail) VALUES('슈퍼주니어')
修改为
INSERT INTO TABLENAME(Detail) VALUES(N'슈퍼주니어')
不然韩文插入到数据库, 就会变成问号问号-_-

**Comment by wendal** [comment]
关了吧
