### ISSUE TITLE
需求：增加新的Callback注入任意类型bean的对应属性

### ISSUE THREAD

**Issue by wxs123456** [nutzam/nutz#541]
应用场景：
A表有2两个字段，A1，A2，
映射后的实体类是也只有这两个属性，
现在我有个SQL语句
select A1,A2,(select count(*) from B where b.a1=a.a1) A3
FROM A;

为了得到计算列，我在实体类里添加属性A3，不加@column，，

通过
Sql sql = Sqls.create(sbsql.toString());
sql.setCallback(Sqls.callback.entities());
sql.setEntity(dao.getEntity(A.class));
dao.execute(sql);
List ls=sql.getList(A.class);
无法取到A3的值，
如果声明了@column，则可以取到。

**Comment by wendal** [comment]
新版的Record支持带前缀的toEntity操作了

**Comment by wendal** [comment]
回调也是
