### ISSUE TITLE
文档:5.9.1. 为什么需要复合加载器这节的一个小小的疑问

### ISSUE THREAD

**Issue by vincentwong109** [nutzam/nutz#569]
看了一遍文档，写的很风趣，佩服写文档童鞋,
对比了三个版本的文档，在5.9.1为什么需要复合加载器这一节倒数第二段：[但是 Nutz 这个小框架开发的初中并不是希望锻炼你]这边的"初中"应该是初衷吧？
GTE : 大于等于 (GreatThanEquale)  其中的Equale是Equal ，还是这个特色的？

**Comment by wendal** [comment]
这个早fix了
