### ISSUE TITLE
为Nutz的MVC增加模块化支持

### ISSUE THREAD

**Issue by netstarry** [nutzam/nutz#57]
之所以提出模块化，是由于WEB应用开发中遇到的以下问题：
1.Jar Hell
2.WEB工程庞大
3.希望功能模块之间开发可以独立，然后自由组合

因此希望创建一种这样的WEB应用程序：
1.在WEB应用中配置所需模块和模块的部署URL
2.模块所需的所有资源均部署在一个统一位置（包括URL映射配置）
3.不同模块之间避免Jar Hell问题

这样的WEB应用程序，WEB服务器上完全无须部署业务逻辑，只需要一个MVC框架和一个模块配置文件，只要更改模块配置文件，即可实现功能变更。

Nutz已经提供了完善的MVC功能，我的一个项目实现了模块化所需的一些支持，将两者结合即可实现模块化的WEB应用开发，不知Nutz的各位开发者是否有兴趣在Nutz MVC中加入模块化WEB应用这个功能？

**Comment by wendal** [comment]
毛,关掉吧

**Comment by zozoh** [comment]
从这个故事中我们可以看到： 解决一个问题最好的方法就是：不解决它
