### ISSUE TITLE
nutz的dao支持对生成sql的表名和字段名加上反单引号``么？

### ISSUE THREAD

**Issue by chenboxiang** [nutzam/nutz#574]
因为有时候表名和字段名会是mysql的关键字，想问下是否支持对sql的表名和字段名都加上反单引号？如果没有的话，想问下如何扩展比较好？

**Comment by wendal** [comment]
结果就没有时间咯, 也没人提了

**Comment by uohzoaix** [comment]
稍微hack一下就可以，在pojo定义时为字段加上单引号，比如@Column(value = "`current_date`")，然后改下NutMappingField类的injectValue方法：
`public void injectValue(Object obj, Record rec, String prefix) {
        try {
            Object val = rec.get((prefix == null ? columnName : prefix + columnName)**.replaceAll("`", "")**);
            this.setValue(obj, val);
        } catch (Exception e) {
            if (log.isTraceEnabled()) {
                log.tracef("columnName=" + columnName, e);
            }
        }
    }`

`public void injectValue(Object obj, ResultSet rs, String prefix) {
        try {
            this.setValue(obj, adaptor.get(rs, (prefix == null ? columnName : prefix + columnName)**.replaceAll("`", "")**));
        } catch (SQLException e) {
            if (log.isTraceEnabled()) {
                log.tracef("columnName=" + columnName, e);
            }
        }
    }`

**Comment by wendal** [comment]
@uohzoaix 新版有Column(wrap=true) 了, 你给的方法也不错
