### ISSUE TITLE
UploadAdaptor适配异常时，不能获取参数值

### ISSUE THREAD

**Issue by Wizzercn** [nutzam/nutz#590]
上传文件时，经常需要附带的传递其他参数，
如果UploadAdaptor异常（比如文件类型不支持），那么debug输出为null，或者出现debug信息有值但获取不到的情况。

这样在实际应用中，就无法通过传递的参数值，判断给出对应的错误提示了。

不知道可需要fix？

**Comment by wendal** [comment]
算了, 不fix了

原因是:
1. 如果对应的参数在该文件数据之后, 怎么都没法取
2. 如果是req/resp等对象, 通过Mvcs也能取
