### ISSUE TITLE
Cnd.wrap构造sql语句有问题

### ISSUE THREAD

**Issue by lplion** [nutzam/nutz#602]
问题产生的条件：
sql定义在.sqls文件中,目的是使用Cnd 构造不定条件下的sql语句
我用Cnd.wrap的目的是想让sql的条件通过其他文件来控制，比如在sqls文件里加上两个条件/*cnd1*/,/*cnd2*/,这样做主要是用于按各种查询条件（比如时间，所属公司等）来生成各种报表，我只需在前台做好判断，然后告诉后台我要用到哪些条件就好了,这样的话就不用再去写大量的java文件了

发生问题的调用代码：
.sqls文件
/*
这是一个用于测试的sql文本
*/
/* query */
select * from organ $condition
/* cnd1 */
id > @id
/*cnd 2*/
name = @name

java调用
//这个Map p是request.getParameterMap()来的
public void customSql(Map p,String filePath) throws NamingException{
		this.sqlFPath = filePath;
		Context ctx = new InitialContext();
		DataSource ds = (DataSource)ctx.lookup("java:comp/env/jdbc/tysx");
		this.dao = new NutDao(ds,new FileSqlManager(sqlFPath));
		String sqlText =  dao.sqls().get(((String[])p.get("_action"))[0]);

		sql = Sqls.create(sqlText);
                //这里参数_cnds值是“cnd1” 或者 “cnd2” 后面可能是cnd1+cnd2+...,如果能实现Cnd.wrap(cnd1).and(cnd2)这样最好了
		if(p.get("id") != null)
                  sql.setCondition(Cnd.wrap(dao.sqls().get("_cnds")));
		for (Object key : p.keySet()) {
			this.sql.params().set(key.toString(), p.get(key));		
		}
		System.out.println(sql);
                ...
	}

问题的详细说明：
1.使用Cnd.wrap() 最后生成的sql语句缺少WHERE
2.sql.params().set 不能替换这种sql.setCondition添加的条件语句中的占位符

相关日志：
- Get Connection from DataSource for JdbcExpert
select * from organ id > @id

**Comment by xwqiang** [comment]
有同样的需求，希望能改善下

**Comment by wendal** [comment]
用Cnd.where(new Static(.....)) 是不是比Cnd.wrap(....)好?

**Comment by wendal** [comment]
1. 缺少WHERE应该不改了,因为破坏兼容性了
2. 1.b.53的自定义SQL支持N个Cnd了,
