### ISSUE TITLE
dao有对relation的insert update 为毛没delete

### ISSUE THREAD

**Issue by jirongjun** [nutzam/nutz#604]
同样的 cri里有andInIntArray 没有not or的

这两个ISSUE在多对多的操作中运用还是比较常见的。
比如A关联B，可能界面上需要显示已经关联的(fetcLinks)， 未关联的(目前只能包装SQL)。
然后加关联(insertRelation)，去关联(没有delteRelation)。
而且，Dao都设定了PK值一般为string long，为什么在cri里却是int？

**Comment by wendal** [comment]
dao.clearLinks
