### ISSUE TITLE
sqls执行查询结果集为空

### ISSUE THREAD

**Issue by 373492364** [nutzam/nutz#613]
(select title,questionCategory_id,contentResume,id from question where questionCategory_id = ? limit 3)
 union all 
(select title,questionCategory_id,contentResume,id from question where questionCategory_id = ? limit 3)
sql执行这种sql时结果集为空，我自己开启connection的话就可以查询的到

**Comment by wendal** [comment]
这个已经支持了 1.b.52的时候, 有sql.forceExecQuery
