### ISSUE TITLE
Nutz 是否可以考虑支持空间类型数据，比如PostGIS，BeyonDB等。

### ISSUE THREAD

**Issue by guanml** [nutzam/nutz#614]
LBS 现在越来越流行，空间数据的orm支持目前只看到 hibernate spatial有支持，nutz是否也考虑一下支持空间数据。在pojo 里是否可以支持类似这种注解
@Geometry(db="postgis" type=“wkt” srs="4326")  //采用postgis的方言来处理
@Geometry(db="beyondb" type=“wkb” srs="900913")  //采用BeyonDB的方言来处理
@Geometry(db="oracle" type=“wkb” srs="1954")  //采用oracle的方言来处理
public String location;

其中 db可以是不同的数据库，type有两种：1、wkt (Well-known text 文本格式)  2、wkb (Well-known binary 二进制格式)。

使用这些注解后，希望能够 生成类似如下sql：
select id,name, st_astext(location) as location from place;  //针对 wkt格式
select id,name, st_asbinary(location) as location from place;  //针对wkb格式

insert into place(id,name,location) values ('1','test', st_geomfromtext('point(123.612 50.124)',4326));
insert into place(id,name,location) values ('1','test', st_geomfrombinary(byte[],900913));
insert into place(id,name,location) values ('1','test', st_geomfrombinary(byte[],1954));

**Comment by wendal** [comment]
关了

**Comment by flymanhi** [comment]
真的不考虑支持吗？

**Comment by wendal** [comment]
@flymanhi 若您提供一个pull req,我们很欢迎地进行review

**Comment by wendal** [comment]
另外, @ColDefine支持自定义适配器了哦

**Comment by ywjno** [comment]
如果是创建表的话没问题，他是想要适配器

**Comment by flymanhi** [comment]
@wendal @ywjno 感谢回复，完美解决问题！我会尽最大努力为Nutz贡献一份力量，再次感谢！
