### ISSUE TITLE
测试用例org.nutz.dao.test.normal.QueryTest.fetch_record错误

### ISSUE THREAD

**Issue by hzl7652** [nutzam/nutz#656]
org.nutz.dao.test.normal.QueryTest.fetch_record
在oracle进行测试时
 assertEquals(6, re.getColumnCount()); 这个报错
实际为 7 多了 ROWNUM RN 列

查询sql
SELECT * FROM (SELECT T.*, ROWNUM RN FROM ( SELECT * FROM t_pet  WHERE name='pet3') T WHERE ROWNUM <= 1) WHERE RN > 0

**Comment by wendal** [comment]
恩
