### ISSUE TITLE
关于model中使用@default注解以后，自动建表的异常。

### ISSUE THREAD

**Issue by jacking124** [nutzam/nutz#665]
环境window 数据库是oracle10g
如model中的一个属性
        @Column("is_locked")
	@Default("1")
	@ColDefine(type = ColType.BOOLEAN)
	private Boolean						locked;
在这样情况下 创建表会出现异常如Log日志：http://nutz.cn/5k

**Comment by wendal** [comment]
还打算fix不

**Comment by wendal** [comment]
新版我testAll能全过的
