### ISSUE TITLE
Cnd中添加orderBy(String name, String dir)方法

### ISSUE THREAD

**Issue by QinAIns** [nutzam/nutz#667]
在平时的项目中，经常会遇到到排序方向问题
 public List<Comment> getByXXXId(long XXXId, int pageNumber, int pageSize, String sortName, String dir) {
        if ("desc".equals(dir)) {
            return query(Cnd.where("targetId", "=", XXXId).and("enabled", "=", true).desc(sortName), new Pager().setPageNumber(pageNumber).setPageSize(pageSize));
        } else {
            return query(Cnd.where("targetId", "=", XXXId).and("enabled", "=", true).asc(sortName), new Pager().setPageNumber(pageNumber).setPageSize(pageSize));
        }
    }
能不能提供一个方法，实现
public List<Comment> getByXXXId(long XXXId, int pageNumber, int pageSize, String sortName, String dir) {
        if (!"desc".equals(dir)) {
            dir = "asc";
        }
        return query(Cnd.where("targetId", "=", XXXId).and("enabled", "=", true).orderBy(sortName,dir), new Pager().setPageNumber(pageNumber).setPageSize(pageSize));
    }

**Comment by wendal** [comment]
早已fix, 不知道哪个版本了
