### ISSUE TITLE
nutz是否可提供根据bean获取数据库插入语句的方法

### ISSUE THREAD

**Issue by zhanghuanle** [nutzam/nutz#684]
基于软件实现备份恢复的时候，希望能把数据库的表记录通过nutz方便的抽取成sql语句 存放于文件中，进而实现软件层面控制的数据备份恢复功能。（目前我们自己通过修改源码笨拙的实现了该功能，但是觉得如果官方能出此功能肯定会更棒）

**Comment by wendal** [comment]
其实就是暴露一下PojoMaker对象
