### ISSUE TITLE
在扫包的时候，如果type空后有空格就会异常，能不能获取会trim下下

### ISSUE THREAD

**Issue by ansn001** [nutzam/nutz#687]
配置在js的bean，如果type 后面的字符串前后有空格就会报错。
比如启动的时候
Wrong type name: ' cn.we.business.sso.config.SsoConfig'
 Wrong type name: 'cn.we.business.sso.config.SsoConfig '

**Comment by wendal** [comment]
恩, 作为FAQ吧
