### ISSUE TITLE
Request 在命令行下执行，更换IP后没起作用

### ISSUE THREAD

**Issue by Wizzercn** [nutzam/nutz#702]
在做一个刷票软件，对方服务器主要验证IP地址（同IP一小时内只能投票一次），代码如下：

            Request reqq = Request.create(page_url, Request.METHOD.GET);
            reqq.getHeader().set("Accept-Encoding", "gzip,deflate,sdch");
            reqq.getHeader().set("Accept-Language", "zh-CN,zh;q=0.8,en;q=0.6");
            reqq.getHeader().set("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8");
            reqq.getHeader().set("User-Agent", "Mozilla/5.0 (iPhone; CPU iPhone OS 7_1 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Mobile/11D167 MicroMessenger/5.3.1");
            Response resp = Sender.create(reqq).setTimeout(20 * 1000).send();

使用这个写法，更换IP后在编译环境(IntelliJ IDEA 13.0)下运行正常(可以刷票)，在命令行(cmd)下执行不正常(不能刷票)。

而换做以下代码后，不管在IDEA还是命令行下执行，都可以正常刷票：

            HttpGet get = new HttpGet(page_url);
            get.setHeader("Accept-Encoding", "gzip,deflate,sdch");
            get.setHeader("Accept-Language", "zh-CN,zh;q=0.8,en;q=0.6");
            get.setHeader("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8");
            get.setHeader("User-Agent", "Mozilla/5.0 (iPhone; CPU iPhone OS 7_1 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Mobile/11D167 MicroMessenger/5.3.1");

            HttpResponse response = httpClient.execute(get);

为了测试效果，每次使用代理工具更换IP，也测试过用手机做热点更换IP，证实确实存在上述问题。
（先是手机做热点发现不能刷票，但手头IP不够，才改用代理更换IP来测试的）

**Comment by wendal** [comment]
无视...
