### ISSUE TITLE
路径参数中String一律变为空值

### ISSUE THREAD

**Issue by enzozhong** [nutzam/nutz#713]
![42g7q 3bfsheokp qpdlb2](https://cloud.githubusercontent.com/assets/993544/4072998/d2a12bd6-2e8e-11e4-8072-a8f274459641.jpg)

以上为情景代码
结果跳转的url为

http://localhost:8080/crm/query/name?name={pet=Pet{petId=305, petName=  , color=   , sex=GG, weight=20.0844201367, height=0.0, born=Mon Nov 24 03:18:43 CST 2008, dead=null, masterId=208, master=null, remark=null, regTime=Wed Aug 27 16:22:12 CST 2014, lastMod=Wed Aug 27 16:22:12 CST 2014, lastRut=Mon Jullong 21 02:06:19 CST 2014, times=2, price=320.5878115971}}

以上petName和color，均应该有值的，但是丢进map中后，输出就成了空了
long和date都不受影响

**Comment by wendal** [comment]
没有找到啊
