### ISSUE TITLE
nutz dao 一次性获取集合里的关联对象

### ISSUE THREAD

**Issue by sphsyv** [nutzam/nutz#739]
我有一个方法，要获得所有用户，并且用户里的权限也是要的。那么我就要这样写
//获得所有用户
public List<User> getUsers(){
    List<User> users = dao.query(User.class, null);
    for (User user : users) {//每次都要写这个循环，麻烦啊
    dao.fetchLinks(user, "roles");//查询用户里所有权限
    }
}
这样在使用的时候才能知道用户里面的所有权限，为啥没有一句话获得所有用户，并且带权限的。。。

官方API这样说：
但是 Nutz.Dao 没有提供一次获取 food 对象以及 pets 对象的方法，因为，你完全可以把上面的两句话写在一行上：
Food food = dao.fetchLinks(dao.fetch(Food.class, "Fish"), "pets");
然后，你可以通过 food.getPets() 得到 Nutz.Dao 为 food.pets 字段设置的值。
但这种方式只适合fetch一个对象，通常情况，我们是要获得一个集合的。

是我的失误，是可以这样获取的。。
List<User> users = dao.fetchLinks(dao.query(User.class, null), "roles");

**Comment by jirongjun** [comment]
但是对于集合的fetchLinks能不能改进一下？
就是目前（1.r.66.）的实现是通过Lang.each来遍历集合每个数据，再执行Links的获取，这样的话，会执行多条select * from table where 主键=?的语句。
能不能把多条语句合并，使用 主键 in ()的方式？
这样执行起来可能会快一点。

**Comment by wendal** [comment]
不一定的, 单主键查询, 数据库查起来很快, in的话, 有可能不走缓存

不过, 这个可以作为个扩展点, 得想想怎么写才可以

**Comment by zozoh** [comment]
而且如果数据比较多的话，有可能更慢 ^_^!
