### ISSUE TITLE
对于很多工具类的入参都是Object的建议

### ISSUE THREAD

**Issue by sd4324530** [nutzam/nutz#744]
比如Lang.isEmpty()、Files.write()等等还有很多
入参中都用Object，原意应该是想告诉使用者，我这个方法可以支持很多很多类型。
代码里大量的使用instanceof来区分用户传入的具体是什么类型。
我的建议是
每一个instanceof其实都可以重载一次这个方法，在入参上区分类型。
我认为的好处:
1.更加优雅的实现；
2.可以让IDE工具更好的为开发者做出提示；
3.更好的防止用户传入错误的类型参数。
我自己的使用体验，每当我用Lang.isEmpty方法时，对于参数的IDE的提示是把所有的变量依次列出来，但是对于这个方法，只适用于几种类型啊- -
比如可以分成如下几个方法:
Lang.isEmpty(Collection<?> collection);
Lang.isEmpty(Map<?, ?> map);
Lang.isEmpty(Object[] array);

**Comment by wendal** [comment]
这种, 只能你发个pull req了
