### ISSUE TITLE
Chain.makeSpecial能否加个方法，实现这种形式Chain.makeSpecial("accountBalance", "+",(BigDecimal.ONE)

### ISSUE THREAD

**Issue by blacklong** [nutzam/nutz#749]
Chain.makeSpecial能否加个方法，实现这种形式
Chain.makeSpecial("accountBalance", "+",(BigDecimal.ONE)

现在是
Chain.makeSpecial("accountBalance", "+1")这种形式，那么就得把增加的值转成字符串的形式。

比如我想传个BigDecimal进去，通常会给转成float，拼到“+1”这里，数字精度会丢失，
而改成3个参数的形式，我就可以直接把BigDecimal传进去，
然后
org.nutz.dao.util.Daos.java的updateBySpecialChain()方法，
里面拼sql时，也使用参数的形式set进去，结果就OK了。
-----------------------------------------------
题外话：
Chain.makeSpecial("accountBalance", "+1")这种形式，我传BigDecimal时，实际用"+" + xx.toString()是没有问题的，
但，感觉还是加个参数好，可以避免大家出错误。
----------------------------------------------------
我测试的代码，供参考
http://www.mytju.com/classcode/news_readNews.asp?newsID=590

**Comment by wendal** [comment]
pass了, 无视了
