### ISSUE TITLE
MaplRebuild的一个BUG

### ISSUE THREAD

**Issue by ha0ck** [nutzam/nutz#750]
在使用MaplRebuild时，进行添加List的操作时，会多添加一个元素
代码：
![image](https://cloud.githubusercontent.com/assets/3716736/4899225/abea5844-6419-11e4-978a-6f0b905cd0c0.png)
结果：
![image](https://cloud.githubusercontent.com/assets/3716736/4899229/b5d02410-6419-11e4-83f6-8ba4d40308b9.png)

**Comment by wendal** [comment]
哦,这个我已经fix了
