### ISSUE TITLE
dao.fetch(Cnd)的问题

### ISSUE THREAD

**Issue by zoeyangfang** [nutzam/nutz#751]
在sql2012中Cnd还要指定order，其实在使用的时候，条件已经做了最大限制，所以不应该在内部采用分页取一条的方式 进行

**Comment by kugooer** [comment]
请问 现在有解决的办法吗？  我也遇到了相同的问题。

**Comment by wendal** [comment]
有, 改 这个文件 org\nutz\dao\jdbc\nutz_jdbc_experts.js

直接改jar或者拷贝出来放在src源文件夹下, org.nutz.dao.impl.jdbc.sqlserver2012.Sqlserver2012JdbcExpert 改成 org.nutz.dao.impl.jdbc.sqlserver2005.Sqlserver2005JdbcExpert

**Comment by wendal** [comment]
done
