### ISSUE TITLE
Nutz手册中Dao-关于主键一章中的描述有误

### ISSUE THREAD

**Issue by ixin** [nutzam/nutz#752]
TIPS：注解 @Id 与注解 @Name 声明的字段不需要另外加上注解 @Column；在注解 @PK 里面声明的对应复合主键的字段不需要另外加上注解 @Column。
------------------------------------------------------------------------------------------------------------

兽说：@PK时也应该在字段加上@Column，事实也是那样的。

**Comment by wendal** [comment]
fix了
