### ISSUE TITLE
nutz有没有像ibatis<isNotNull>&<isNotEmpty>这样的功能，按照参数组装sql

### ISSUE THREAD

**Issue by programmer-monkey** [nutzam/nutz#767]
如题。
因为业务需要，当字段A有值时，用A当做条件传入，当A无值时，则字段A不作为条件，以下为ibatis的sql
```
select * from table t
<dynamic prepend="where ">
    <isNotEmpty prepend="AND" property="A">
	 t.A=#A#
    </isNotEmpty>
</dynamic>
```

**Comment by bugss** [comment]
@zozoh  我也支持 programmer-monkey  的提议，希望后期提供。 这样容易弄一个公用的查询方法，处理大多少的查询业务。不过我建议用表达式引擎弄这个东西，而不是xml。 对于有好多ajax查询的项目来说，这样的公共方法可以省下好多代码。

**Comment by zozoh** [comment]
@bugss 实际上你可以写一个符合自己业务需要的公共查询函数 ...

**Comment by wendal** [comment]
通过一个模板引擎来做比较好

**Comment by wendal** [comment]
通过sqltpl解决 http://github.com/nutzam/nutzmore
