### ISSUE TITLE
提供基于xml的ormapping映射配置

### ISSUE THREAD

**Issue by nychen2000** [nutzam/nutz#770]
本人写了个工作流引擎，fire workflow，以前是用hibernate做ormapping；现在改成了nutz，但是nutz的ormapping暂时只有annotation方式，不利于解耦，希望提供基于xml的ormapping映射配置

**Comment by wendal** [comment]
未完成测试的版本, 供讨论
https://gist.github.com/wendal/14a0a84b4dbf280e6faa

**Comment by wendal** [comment]
在nutremore中提供了
