### ISSUE TITLE
关于Nutz SqlExpressionGroup andLike 模糊检索的问题/需求

### ISSUE THREAD

**Issue by wqmain** [nutzam/nutz#771]
类 org.nutz.dao.util.cri.SqlExpressionGroup 的 andLike 方法中调用的是 org.nutz.dao.util.cri.Exps 的 like 方法，如下：
public SqlExpressionGroup andLike(String name, String value) {
        return and(like(name, value));
    }

public static Like like(String name, String value) {
        return Like.create(name, value, true);
    }

类 Like 的 create 方法中默认了left 和 right 的值为“%”，却没有对外提供方法，如LikeLeft 或 LikeRight，这样所有模糊检索都都是 like “%XXX%” 的形式，而没有 like “XXX%” 或 like “%XXX” 的形式。
我现在是将 create方法中 like.left = null; like.right = null，然后程序中自己加左%或右%

建议：除现有的 andLike 方法外提供 andLikeL 和 andLikeR 方法。

注：Nutz 版本为 1.b.51

**Comment by wendal** [comment]
恩
