### ISSUE TITLE
关于 org.nutz.dao.Chain 中的 make 和 makeSpecial 方法的并发测试（前者存在并发问题）

### ISSUE THREAD

**Issue by wqmain** [nutzam/nutz#772]
测试数据库：mysql 5.5.30     
建表脚本：
CREATE TABLE `sys_seq` (
  `CODE` varchar(50) NOT NULL,
  `VALUE` bigint(16) NOT NULL,
  PRIMARY KEY (`CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

相关Service和测试类如下：
@IocBean(name = "baseService", args = { "refer:dao" })
public class BaseServiceImpl implements IBaseService {

	private final Lock lock = new ReentrantLock();

	public BaseServiceImpl(){
	}
	
	public BaseServiceImpl(Dao dao){
		this.dao = dao;
	}

	public long setNextVal(final String key) {
		lock.lock();
		try {
			if(Strings.isBlank(key)) return -1;
			Record r = dao.fetch("sys_seq", Cnd.where("code", "=", key));
			if(r != null && r.containsKey("value")) {
				final long nextVal = Long.valueOf(r.get("value").toString()) + 1;
				//dao.update("sys_seq", Chain.makeSpecial("value", "+1"), Cnd.where("code", "=", key)); //没有并发问题
				dao.update("sys_seq", Chain.make("value", nextVal), Cnd.where("code", "=", key));	  //存在并发问题
				return nextVal;
			} else {
				dao.insert("sys_seq", Chain.make("code", key).add("value", 1L));
				return 1L;
			}
		} finally {
			lock.unlock();
		}
	}
}

public class BaseUnitTest {
	
	private Ioc ioc = null;

	public BaseUnitTest() {
		try {
			ioc = new NutIoc(new ComboIocLoader(
				"*org.nutz.ioc.loader.json.JsonLoader", "ioc/",
				"*org.nutz.ioc.loader.annotation.AnnotationIocLoader",
				"cn.com.demo"));
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}
	}
	
	public <T> T get(Class<T> type, final String name) {
		return ioc.get(type, name);
	}

	public Ioc getIoc() {
		return ioc;
	}
	
}

public class ConcurrentTest extends BaseUnitTest {
	
	private IBaseService getBaseService() {
		return getIoc().get(IBaseService.class, "baseService");
	}
	
	private long getNextVal() {
		final String key = "220101";
		long value = getBaseService().setNextVal(key);
		System.out.println("value=" + value);
		return value;
	}
	
	private void getNextVal(int count) {
		for(int i=0; i<count; i++) {
			new Thread(new Runnable() {
				public void run() {
					getNextVal();
				}
			}).start();
		}
	}
	
	@Test
	public void setNextValTest() throws Exception {
		//开启1000个线程并发测试
		getNextVal(1000);
		//主线程睡眠，以便线程并发测试
		Thread.sleep(50000);
	}
	
}

预计测试结果：开启1000个线程情况下，sys_seq 表中VALUE字段的值应为1000（每次测试前需清空）
实际测试结果：
BaseServiceImpl 类的 setNextVal 方法中使用下面这句没有并发问题：
dao.update("sys_seq", Chain.makeSpecial("value", "+1"), Cnd.where("code", "=", key)); 
但改成：
dao.update("sys_seq", Chain.make("value", nextVal), Cnd.where("code", "=", key));
存在并发问题

**Comment by wendal** [comment]
那是肯定的, 毫无疑问啦, 不然为何有  N=N+1

**Comment by wqmain** [comment]
你说的N=N+1的意思是？  不明求教

**Comment by wendal** [comment]
刚刚跑了一下你的代码,  由于lock.lock();的存在, 事实上已经变成单线程操作, 最终也是1000

**Comment by wendal** [comment]
但如果不加lock.lock();的话, dao.fetch和dao.update就不会发生在同一个事务中了.
