### ISSUE TITLE
Filter中无法使用@Inject注入？

### ISSUE THREAD

**Issue by FateR2** [nutzam/nutz#777]
public class CheckLogin implements ActionFilter {

	@Inject
	private UserSessionService userSessionService ;
	
	public View match(ActionContext actionContext) {
		// TODO Auto-generated method stub
		//something else
        //这里调用userSessionService会报空指针，其他类中正常，就在Filter中有这个问题.
        //something else
		return view;
	}
	
}

**Comment by TuWei1992** [comment]
确保filter 受ioc 容器管理

**Comment by wendal** [comment]
@Filters({@By(type=CheckLogin, args="ioc:checkLogin")})

**Comment by FateR2** [comment]
谢谢
