### ISSUE TITLE
org.nutz.dao.util.Daos.queryCount(Dao, String) 这个方法在mysql下会报错

### ISSUE THREAD

**Issue by bugss** [nutzam/nutz#781]
Sql sql2 = Sqls.fetchLong("select count(1) FROM ("+sql+")");
mysql 里面的查询必须要加上别名。不然就报错了。

**Comment by wendal** [comment]
fixed in 8cd8504ce0afaa90492a4fe97fa696449e3dc1cc

**Comment by unhappydepig** [comment]
刚准备报就发现新版本中修复了.... 很是失落啊

**Comment by wendal** [comment]
呵呵
