### ISSUE TITLE
一个@id注解的问题

### ISSUE THREAD

**Issue by bugss** [nutzam/nutz#782]
pojo 中一个字段叫fid标记成了@id 。 
用的mysql 数据库 fid 为某个数据表的主键，而且为自增长列。
我们项目中有这么一个需求：
1 如果fid 值为null 则插入数据时用自增长列自动生成的id。
2 如果明确的指定了fid的值，如fid=56721 。那么插入数据库时用这个指定的值

现在nutzdao的问题是：
如果我设置@id(auto=false)  需求2 可以满足 需求1中会报错
如果设置了@id(auto=true) 需求1 可以满足 需求2 又满足不了。 
现在nutzdao的实现是否能在dao.insert 时动态处理一下？

现在我在项目中的做法是这样的：
	@Prev(@SQL(value = "select (case when @fid is null then"
			+ " IFNULL(MAX($field),0)+1 else @fid end)  from $view  "))
能解决问题（神奇的mysql这么写max也没有报错-_-!）。 不过我感觉太麻烦了。。而且这种没锁的max 处理主键问题老觉得不太可靠

**Comment by zozoh** [comment]
1. 这个需求太少数了，不可能位这个专门做优化
2. 没锁，max，即使重了，又怎样？顶多是抛个主键重复的错吧，又不会生成错的数据。而且概率还那么小

**Comment by bugss** [comment]
。。也有道理。我自己处理吧。
