### ISSUE TITLE
Lang.collection2array 类型转换问题

### ISSUE THREAD

**Issue by Jastxx** [nutzam/nutz#784]
不单独指定类型时，列表长度为0， 无法根据泛型创建类型匹配的空对象
        if (coll.size() == 0)
            return (E[]) new Object[0];
这个返回的数组无法被识别类型，造成异常

**Comment by wendal** [comment]
恩

**Comment by wendal** [comment]
我发现fix不了... 因为泛型取不到, 如果调用的方法是临时变量的话.

**Comment by wendal** [comment]
无法fix

**Comment by Jastxx** [comment]
Deprecated
