### ISSUE TITLE
Postgres表名大写问题

### ISSUE THREAD

**Issue by wangcheng0825** [nutzam/nutz#789]
因为pg中表名，列名是区分大小写的，所以POJO中声明如下
@Table("\"TAG\"")
public class Tag {
   @Column("\"ID\"")
    private String identifier;
}
通过dao.create得到的sql语句为
'CREATE TABLE "TAG"(
"ID" VARCHAR(64),
CONSTRAINT "TAG"_pkey PRIMARY KEY ("ID")
)'

CONSTRAINT "TAG"引号出错，应被替换

**Comment by wendal** [comment]
为啥要特意加双引号呢?

**Comment by wangcheng0825** [comment]
postgres如果表名或字段名是大写，需要放到双引号里。

**Comment by wendal** [comment]
... 原来有这么奇葩的规定
