### ISSUE TITLE
同名类beanName冲突问题

### ISSUE THREAD

**Issue by Wizzercn** [nutzam/nutz#791]
使用@IocBean 不设置名称，出现冲突：

 beanName=indexAction, by class cn.wizzer.modules.pub.IndexAction

 beanName=indexAction, by class cn.wizzer.modules.sys.IndexAction

例如java.util.Date和java.sql.Date不算重名，同理项目中不同路径下的同名类也不算重名。

建议Nutz默认生成的beanName名加上包前缀，这样做的好处有：
1、大型项目多类似功能模块，可分工协作，对nutz不太熟悉的人可避免同名造成的错误；
2、同名类不可避免，比如 public 和 private 模块等等；
3、提高开发效率，减少程序员工作量。

ps：issues 会提的，至于改不改就不是我能决定的了~~~

**Comment by Rekoe** [comment]
这个问题 兽兽 好像有做过处理 会提示的

**Comment by unhappydepig** [comment]
这个前一段时间也遇到过，前后端都用IndexAction  后来后端前段改为HomeAction 了事。

**Comment by wendal** [comment]
他是不想写@IocBean(name="xxxx") 里面的name=

**Comment by Wizzercn** [comment]
为什么我说服不了一个同事使用nutz，他有一个理由就是注解使用起来麻烦有时候新手找不到错误原因，我觉得一个框架好就在于容错率高让开发人员不用在明知道会报错的事情上浪费时间，大型多模块分工开发同名类是必然存在的，为何不能改变默认命名规则减少出错概率让开发者解放呢？

**Comment by Rekoe** [comment]
莫强求

**Comment by wendal** [comment]
加个name属性不会死人的
