### ISSUE TITLE
Nutz框架Rest方式传入的参数被截取了部分内容

### ISSUE THREAD

**Issue by zhiyang4cn** [nutzam/nutz#794]
问题的步骤大致如下：

第一步：
后台代码使用如下方式：
@IocBean
@InjectName
public class TestAction {
 
    @At("/test/?")
    public void print(String json) {
        System.out.println("json: " + json);
    }
}

第二步：前端进行访问
http://localhost:9090/zifi/test/{"test":"say@163.com","hello":"zhi"}
or
http://localhost:9090/zifi/test/'{"test":"say@163.com","hello":"zhi"}'

第三步：

两种方式的后台日志均报出同样的错误：
net.nutz.zifi.dao.BasicDao , no config to enable AOP.
[30173802@qtp-20805212-0] DEBUG org.nutz.ioc.impl.ScopeContext - Save object 'basicDao' to [app] 
[30173802@qtp-20805212-0] DEBUG org.nutz.ioc.impl.NutIoc - Get 'dao'<>
json: {"test":"say@163

看到后台的日志中发现测试的字符串被截取了部分(日志最后部分)，这个肯定是某一个拦截处理Rest字符串时出现了问题，我不管是字符串多长都是被截取了163后面的所有字符串？
请问各位大神，遇见过类似问题吗？如果解决啊！谢谢！

我现在使用的是最新的版本：nutz-1.b.51.jar

**Comment by wendal** [comment]
url里面传json?完全醉了

**Comment by zozoh** [comment]
如果传 JSON 用 POST
用 JsonAdaptor :  http://nutzam.com/core/mvc/http_adaptor.html
