### ISSUE TITLE
setCondition(Cnd.wrap(...)) 或setCondition(Cnd.format(...))不会在SQL语句中加where

### ISSUE THREAD

**Issue by majong** [nutzam/nutz#804]
这样的话wrap和format到底起什么作用呢？
例如：
Sql sql = Sqls.create("SELECT name FROM t_pet $condition");
sql.setCondition(Cnd.wrap("id>35“));
最终的SQL变成了：
SELECT name FROM t_pet id>35
这是非法的SQL！

**Comment by Rekoe** [comment]
````
sql.setCondition(Cnd.where("id",">",35));
`````

**Comment by majong** [comment]
这样的话，Cnd.wrap(...)和Cnd.format(...)什么场合使用呢？

**Comment by wendal** [comment]
dao.query 之类的

**Comment by wendal** [comment]
其实你觉得少了where的话, 在wrap里面写上不就可以了
