### ISSUE TITLE
nutz表名是否有长度限制？

### ISSUE THREAD

**Issue by skynetbird** [nutzam/nutz#806]
我期望创建的表名为T_SYS_WFHACTOWNER。但是实际执行planService.dao().create(HActOwner.class, true)；时，发现创建表SQL为
CREATE TABLE h_act_owner，似乎是从后面自动截断了我声明的表名。请问，是否nutz表名长度有限制，限制规则是什么，如果我希望使用我预期的表名，有没有好的解决办法？（直接现在后台数据库先创建好表？）

我的pojo为 HActOwner，代码如下：
@Table("T_SYS_WFHACTOWNER")
public class HActOwner extends IdEntity {
	@Column
	private String runactkey;

	@Column
	private String ctype;

	@Column
	private String ownerctx;

	@Column
	private String cname;

	@Column
	private String complete;
}

**Comment by wendal** [comment]
仔细看log, 有提示

如果没有nutz的@Table注释,才会生成HActOwner --> h_act_owner, 大写字母分割的单词加下划线.

so, 如果你确定加了@Table,那就肯定不是nutz的@Table咯

**Comment by wendal** [comment]
无长度限制一说, nutz根本不会检查这些

**Comment by skynetbird** [comment]
@Table("T_SYS_WFHACTOWNER")
public class HActOwner {...}

很奇怪，我的实体类前面声明了@Table标注了啊？特殊一点的是HActOwner继承了我自己的IdEntity类，里面仅仅是为了少写一个Id字段的声明，也许是IdEntity类的原因，因为它并不会声明@Table，但在Hibernate下这样似乎是没什么问题的，我再试试看看吧。
另外看明白了，如果没声明@Table的话，nutz会自动根据实体类的大小写创建表名，如HActOwner就会定义为h_act_owner。
谢谢wendal，我再琢磨一下nutz哈。

**Comment by zozoh** [comment]
Nutz 支持 你这么写的，最后的子类上面的 `@Table` 决定了表名。
你确定你的 `@Table` 是  `org.nutz.dao.entity.annotation.Table` 这个注解吗？

**Comment by skynetbird** [comment]
呵呵，这个问题已经搞定了，用的是org.nutz.dao.entity.annotation.Table 这个注解，是因为开发环境的问题，
执行时找不到Table这个类，导致错误了。呵呵，不是nutz的问题，也不是程序的问题，是我的开发环境类路径查找有些问题。




在 2015-03-08 11:52:18，"Peter Zhang" <notifications@github.com> 写道：


Nutz 支持 你这么写的，最后的子类上面的 @Table 决定了表名。
你确定你的 @Table 是 org.nutz.dao.entity.annotation.Table 这个注解吗？
