### ISSUE TITLE
Nutz能否如Hibernate那样自动创建表？

### ISSUE THREAD

**Issue by skynetbird** [nutzam/nutz#807]
使用Hibernate，会根据实体与表名映射，系统加载时会自动创建表。
在Nutz里不清楚是否也可以如此，现在很笨的用语句创建表，几十个表就需要预先写下下面这样的调用，虽然繁琐还可以接受，但还是感觉不爽，nutz如果也可以自动建表就爽了。
                planService.dao().create(BAct.class, true);
		planService.dao().create(BActDecision.class, true);
		planService.dao().create(BActField.class, true);
		planService.dao().create(BActOwner.class, true);
		planService.dao().create(BActPos.class, true);
		planService.dao().create(BActTask.class, true);
		planService.dao().create(BFlow.class, true);
		planService.dao().create(BFlowApp.class, true);
		planService.dao().create(BFlowAppManager.class, true);
		planService.dao().create(BFlowClass.class, true);
		planService.dao().create(BFlowOwner.class, true);
		planService.dao().create(BFlowReader.class, true);
		planService.dao().create(BForm.class, true);
		planService.dao().create(BNorAct.class, true);
		planService.dao().create(BPriority.class, true);
		planService.dao().create(BRoute.class, true);
		planService.dao().create(BRoutePos.class, true);
		planService.dao().create(BRouteTask.class, true);
		planService.dao().create(HAct.class, true);
		planService.dao().create(HActAssorter.class, true);
		planService.dao().create(HActHandler.class, true);
		planService.dao().create(HActOwner.class, true);
		planService.dao().create(HActTask.class, true);
		planService.dao().create(HFlow.class, true);
		planService.dao().create(HFlowAuthor.class, true);
		planService.dao().create(HFlowReader.class, true);
		planService.dao().create(HNorAct.class, true);
		planService.dao().create(LEvent.class, true);
		planService.dao().create(LEventAct.class, true);
		planService.dao().create(LEventActReceiver.class, true);
		planService.dao().create(LEventActToAssorter.class, true);
		planService.dao().create(LEventActToAssorterAgenter.class, true);
		planService.dao().create(LEventActToHandler.class, true);
		planService.dao().create(LEventActToHandlerAgenter.class, true);
		planService.dao().create(LEventError.class, true);
		planService.dao().create(LEventFlow.class, true);
		planService.dao().create(LEventRoute.class, true);
		planService.dao().create(LEventRouteReceiver.class, true);
		planService.dao().create(LFlowAssApp.class, true);
		planService.dao().create(LFlowAuthor.class, true);
		planService.dao().create(LFlowReader.class, true);
		planService.dao().create(RAct.class, true);
		planService.dao().create(RActAssorter.class, true);
		planService.dao().create(RActHandler.class, true);
		planService.dao().create(RActOwner.class, true);
		planService.dao().create(RActTask.class, true);
		planService.dao().create(RFlow.class, true);
		planService.dao().create(RFlowAuthor.class, true);
		planService.dao().create(RFlowReader.class, true);
		planService.dao().create(RNorAct.class, true);
		planService.dao().create(WFHWaitWork.class, true);
		planService.dao().create(WFTask.class, true);	
		planService.dao().create(WFWaitWork.class, true);

**Comment by wendal** [comment]
```
Daos.createTablesInPackage(dao, "xxx.xxx.xxx", false);
```

**Comment by skynetbird** [comment]
非常感谢，问题比较初级，费心了。
