### ISSUE TITLE
事务拦截器为什么不回滚呢？

### ISSUE THREAD

**Issue by skynetbird** [nutzam/nutz#808]
我配置了aop,程序中有意抛出RuntimeException，测试回滚，发现无论怎样，都未发生回滚。
ioc.js配置文件声明了事务，函数方法前应当就不再需要设置事务声明了吧？不知道为什么不回滚，急啊。是我的配置文件设置的拦截目标函数不对吗，拦截器压根没其作用？有没有办法跟踪到拦截器是否执行了？

    $aop : 
	{
	    type : 'org.nutz.ioc.aop.config.impl.ComboAopConfigration',
	    fields : 
	    {
	        aopConfigrations  : 
	        [
	            {	
	            	type : 'org.nutz.ioc.aop.config.impl.JsonAopConfigration',
	                fields : 
	                {
	                    itemList : 
	                    [
	                    	[ 'com\\.skynet\\.+\\service\\.+', '.+', 'ioc:txSERIALIZABLE' ],
	                    	[ 'com\\.skynet\\app\\workflow\\.+', '.+', 'ioc:txSERIALIZABLE' ]
	                    ]
	                }
	            },
	            {	type : 'org.nutz.ioc.aop.config.impl.AnnotationAopConfigration' }
	        ]
	    }
	}

**Comment by skynetbird** [comment]
又看了我的ioc.js,发现好像时写错了，js的正则写法不熟悉，再改改吧，换平台就是需要一段时间熟悉，呵呵，Nutz还是很不错的。

**Comment by skynetbird** [comment]
确实是正则写错了，现在好了。
 [ 'com\\.skynet\\.+\\.service\\.+', '.+', 'ioc:txREAD_COMMITTED' ],
 [ 'com\\.skynet\\.app\\.workflow\\.+', '.+', 'ioc:txREAD_COMMITTED' ]

**Comment by wendal** [comment]
那不是js的正则表达式, 那是java的正则表达式, 只是需要转义一下而已
