### ISSUE TITLE
事务拦截器为什么不回滚呢？新问题。

### ISSUE THREAD

**Issue by skynetbird** [nutzam/nutz#809]
现在事务确实回滚了，但仍然有严重问题，不清楚nutz是否可以进行事务传递？

是这样，我在
planService
{ 
   public void insert() throws Exception
    {
          do some database op ; // 进行业务数据操作;
          workFlowEngine.getFlowManager.create(); // 调用流程引擎创建流程实例
    ｝
}
我在workFlowEngine.getFlowManager.create()方法中有意抛出RuntimeException。
现在是workFlowEngine.getFlowManager.create()方法内的数据库操作回滚了，但是planService.insert()方法中的数据库操作未回滚。
难道是我的正则仍然写的有问题，planService的方法没能被正确拦截，workFlowEngine的方法被拦截了？

**Comment by skynetbird** [comment]
<code>
    $aop : 
	{
	    type : 'org.nutz.ioc.aop.config.impl.ComboAopConfigration',
	    fields : 
	    {
	        aopConfigrations  : 
	        [
	            {	
	            	type : 'org.nutz.ioc.aop.config.impl.JsonAopConfigration',
	                fields : 
	                {
	                    itemList : 
	                    [
	                    	[ 'com\\.skynet\\.+\\.service\\.+', '.+', 'ioc:txREAD_COMMITTED' ],
	                    	[ 'com\\.skynet\\.app\\.workflow\\.+', '.+', 'ioc:txREAD_COMMITTED' ]
	                    ]
	                }
	            },
	            {	type : 'org.nutz.ioc.aop.config.impl.AnnotationAopConfigration' }
	        ]
	    }
	}
</code>

**Comment by wendal** [comment]
看堆栈, 如果是被aop拦截的方法, 会看到 $$NUTZ_AOP之类的类名

**Comment by skynetbird** [comment]
搞定了，正则写法是对的，异常信息提示“.....类找不到”。是EClipse工作区的类路径设置之类的问题，将代码挪出来，好了。开发环境有时候怪异的问题折腾人够呛。
