### ISSUE TITLE
现在很多IDE都支持直接编辑json文本以.json结尾，可不可以改变NutConf中硬编码.js

### ISSUE THREAD

**Issue by beihaifeiwu** [nutzam/nutz#810]
"""
             if (path.endsWith(".js")) {
                File f = Files.findFile(path);
                resources = new ArrayList<NutResource>();
                resources.add(new FileResource(f));
            } else {
                resources = Scans.me().scan(path, "\\.js$");
            }
        """

**Comment by wendal** [comment]
哦
