### ISSUE TITLE
<input name="borrowDetailsStr" type="text" />  这个输入框里面输入含逗号的信息，nutz自动解析为多个字符串数组

### ISSUE THREAD

**Issue by cuker919** [nutzam/nutz#816]
<input name="borrowDetailsStr" type="text" />  这个输入框里面输入含逗号的信息，nutz自动解析为多个字符串数组。
而且，页面上会有多个<input name="borrowDetailsStr" type="text" />  。

**Comment by cuker919** [comment]
页面上会有多个<input name="borrowDetailsStr" type="text" />标签。

**Comment by zozoh** [comment]
把你页面上的代码，以及入口函数的代码贴一下

**Comment by cuker919** [comment]
jsp页面：
<td align="center">
		<input name="borrowDetailsStr" type="text" size="35"  class="validate[required]"/>
</td>

java代码：
	@At
	@Ok("jsp:/template/expenses/borrow/Borrow_Apply_Submit.jsp")
	@Fail("jsp:/template/include/_error.jsp")
	@AdaptBy(type = UploadAdaptor.class, args = { "ioc:myUpload" })
	public Map<String,Object> add(@Param("..")final BorrowApply obj,
								  @Param("borrowDetailsStr")final String[] borrowDetailsStr,
								  @Param("subjectCode")final String[] subjectCode,
								  @Param("subjectName")final String[] subjectName,
								  @Param("detailAmount")final String[] detailAmount,
								  @Param("writeOffAmountTotal")final String writeOffAmountTotal,
								  @Param("applyFile") TempFile applyFile,
								  @Param("flag")String flag
								  ) throws Throwable{

**Comment by cuker919** [comment]
发现含有标签的github会过滤掉：
jsp页面：
input name="borrowDetailsStr" type="text" size="35"  class="validate[required]"

**Comment by zozoh** [comment]
@cuker919  你要用 markdown 的语法去写

**Comment by zozoh** [comment]
你的适配函数

```java
...
@Param("borrowDetailsStr")final String[] borrowDetailsStr,
...
```

不就是需要一个字符串数组吗？ 所以 Nutz 就试图把你的字符串按照半角逗号分隔成字符串数组。
如果你不想分隔，你要声明成

```java
...
@Param("borrowDetailsStr")final String borrowDetailsStr,
...
```

**Comment by cuker919** [comment]
@zozoh   页面上会有多个input name="borrowDetailsStr" type="text" size="35" class="validate[required]"标签输入值，如果改成@Param("borrowDetailsStr")final String borrowDetailsStr接收，那么再按逗号分割也是有问题的。
nutz可不可以在接收的时候按多少个name就多少个字符串数组呢？

**Comment by cuker919** [comment]
@zozoh  请问还有什么其他办法解决，接收这种多个一样的name包含半角逗号的方法不？或者等你们升级版本解决？  
       谢谢！

**Comment by wendal** [comment]
看来得fix一下, 或者走json

**Comment by zozoh** [comment]
在 `org.nutz.mvc.adaptor.injector.ArrayInjector` 的逻辑是:

```java
if (values.length == 1) {
        // 如果只有一个值，那么试图直接转换
       return convertMe(values[0]);
}
return Lang.array2array(values, klass.getComponentType());
```

看来需要增加另外一个开关，强制不要拆分字符串才行

**Comment by zozoh** [comment]
增加了测试用例
```
org.nutz.mvc.adaptor.injector.ArrayInjectorTest

 - test_array_no_split
 - test_array_auto_split
 - test_array_no_split2
```

**Comment by zozoh** [comment]
针对楼上这种情况，

```java
...
@Param(value="borrowDetailsStr", array_auto_split=false)final String[] borrowDetailsStr,
...
```

即可满足要求

**Comment by wendal** [comment]
哦, 多了个属性

**Comment by cuker919** [comment]
谢谢两位， 等1.b.53新版本出来再升级，我现在用的是1.b.51，想升级但领导说怕会影响现网。
  o(∩_∩)o...呵呵！！！

**Comment by zozoh** [comment]
@cuker919  试试就知道会不会影响咯，没啥大改动
