### ISSUE TITLE
表视图不起用

### ISSUE THREAD

**Issue by smilelhh888** [nutzam/nutz#817]
设置了@readonly字段对了视图里新增的字段。也设置了@view
但是，在dao.query()查询时，却发现不会从视图中取值。

**Comment by zozoh** [comment]
你建立视图了吗？
Nutz 输出的 SQL 语句是啥？

**Comment by smilelhh888** [comment]
这个肯定是建立 了的，我特意打开了SQL输出，也看到了确实是调用了视图。但是那@readonly字段就是没有赋值！

**Comment by wendal** [comment]
Nutz 输出的 SQL 语句是啥？

**Comment by smilelhh888** [comment]
select * from v_wategate_r

**Comment by smilelhh888** [comment]
一 我创建的视图是
create table v_wategate_r stcd,stnm=(select stnm from st_info_b where stcd=a.stcd),
flux from st_wategate_r a
二创建的POJO类是
@Data
@Table("irr_wategate_b")
public class Wategate {
  @Column 
 private String stcd;

@readonly
private String stnm;
}
三调用的方法
List<Water> rtn = dao.query(Water.class)
四输出的sql
DEBUG org.nutz.dao.impl.sql.run.NutDaoExecutor - SELECT * FROM v_wategate_r
五但时得到的结果却是，
Wategate(stcd=88888888, stnm=null, flux=134.0)
其中stnm是空。但是我在数据库中执行SELECT * FROM v_wategate_r是看得到stnm不为空的

**Comment by zozoh** [comment]
用 `create table` 建立视图？ 没用 `create view` ??

**Comment by wendal** [comment]
已经结了, 因为没写```@Column```

**Comment by zozoh** [comment]
喔
