### ISSUE TITLE
Scans.scan重复加载资源问题

### ISSUE THREAD

**Issue by talentyao** [nutzam/nutz#820]
Eclipse下执行没有问题，通过Maven打包发布后执行出现大量资源和类文件报重复加载的问题，具体日志见：http://nutz.cn/LG   该问题已在Nutz&XBlink群和 兽 求助过

**Comment by Rekoe** [comment]
好像在linux下会出现这个问提
windows 下没问题

**Comment by talentyao** [comment]
我是在windows下，一样出现！

**Comment by wendal** [comment]
这个问题是因为当前路径即为classpath路径,导致重复了

**Comment by wendal** [comment]
在QQ群喊我一下吧, 远程看看去

**Comment by wendal** [comment]
我查出来了, 是因为 webapps所在的目录处于一个软连接(ln -s)的目录下

例如 

/home/wendal/tomcat --> /opt/tomcat

从而导致 nutz分别在/home/wendal/tomcat 和/opt/tomcat 进行扫描
