### ISSUE TITLE
关于JSON操作没有filed的序列化问题

### ISSUE THREAD

**Issue by monlyu** [nutzam/nutz#822]
我在代码的过程中有这这的操作。

class User{
     
     @JsonFiled(ignore=ture)
      public int userType;
      
      public String getUserTypeVal(){
           if(userType==0)  return "AA";
          else return "BB";
    }
}

现在的Json.toJSON 会导致我下面的方法无法获取到值。
必须要另外弄一个UserTypeVal的Field 很多时候这个是没得用的。

我看了源代码 基础都是以set为返回参数判断。

当初设计这个的原因是什么呐？

**Comment by wendal** [comment]
没看懂的有没有

你这不是声明了ignore=ture了吗? 那这个userType属性都被忽略了啊, 不知道你想干啥

**Comment by monlyu** [comment]
对不起。我描述可能有点模糊。

有些字段  本身数据库里面是没有映射的。
USER表现有一个字段叫：userType ，值可能为1，2，3，4等但是我不想响应到web端。我忽略掉

但是我组装另外一个字段 userTypeVal 这个字段表中无对应字段。但是我想让他响应的前端。

现在的做法是加入

private String userTypeVal;

public String getUserTypeVal(){
    if(userType==0)  return "AA";
      else return "BB";
}

public void serUserTypeVal(String usertype){
     this. userTypeVal = usertype;
}

这个时候我发现 申明的字段并没有实际用途，set方法我也没有任何用。我只使用了 getUserTypeVal 这个方法。

现在对象到JSON的转换需要用到set方法。

当初考虑这个的原因是为什么？

谢谢

**Comment by wendal** [comment]
@JsonField 强制声明.

**Comment by zozoh** [comment]
我也没看懂 ...
