### ISSUE TITLE
关于前缀表单方式

### ISSUE THREAD

**Issue by CXW0504** [nutzam/nutz#823]
public String someFunc( @Param("::user.") User user,
                        @Param("::dep.") Department dept){
    ...
}
/*************
@param("::xxx.")这样接收不到。去掉user后面那个点就可以了。 @Param("::user") User user
 ==============================================
随便改下文档 (๑¯ิε ¯ิ๑)

**Comment by pangwu86** [comment]
应该是文档写错了, 不过记得之前的文档里确实是 ::xxx

**Comment by pangwu86** [comment]
额....这个刚刚下一下文档, me记错了 一直是有这个点的.   等查查代码再确认下

**Comment by CXW0504** [comment]
好的

**Comment by wendal** [comment]
文档问题

**Comment by zozoh** [comment]
按照我当初的习惯，我通常是认为：

* 前缀是 `user.`
* 前缀名是 `user`

如果不是这么实现的，可能是我晕了 ...  现在只好改文档咯

**Comment by pangwu86** [comment]
这文档me查了下, 11年好像就这样写的, 不过me印象中当年(09-10)好像是没有点的

**Comment by CXW0504** [comment]
web.xml写/*，没问题。但是web.xml写/test/* 会有问题。
/=============================================
如文档：http://www.nutzam.com/core/mvc/url_mapping.html
-------》这部分：Nutz 中的目录匹配 - /abc/*
如果请求为：
http://localhost:8080/testweb/abc/getlist.nut
对于 Nutz.Mvc 我们需要匹配的部分为：
/getlist
//==================================
At里面要写上前缀
filter的前缀，不支持

**Comment by zozoh** [comment]
@wendal  在 306655a 增加了 `ObjectNavlPairInjector` 来处理 `@Param("::")`
看了眼源代码，好像没啥问题，

做了一个测试

```java
 @At("/pair")
@Ok("json")
@Fail("json")
public Object pair(@Param("::a.") Pet pet) {
    return pet;
}
```

发送请求:

```
http://localhost:8080/pair?a.name=xiaobai&a.age=10
```

服务返回 JSON 数据:

```json
{
    id: 0,
    name: "xiaobai",
    age: 10,
    masterId: 0,
    price: 0
}
```

看起来依然是没问题

**Comment by wendal** [comment]
带数组的那种

user[0].name=wendal
user[0].age=30

**Comment by zozoh** [comment]
他说了要带数组那种了？

**Comment by wendal** [comment]
issue没说清楚, 其实是问带数组索引那种

**Comment by wendal** [comment]
忘记是啥东西了
