### ISSUE TITLE
NutFilter配置为目录映射/rs/*，那At只匹配*那部分出问题

### ISSUE THREAD

**Issue by CXW0504** [nutzam/nutz#824]
NutFilter配置为目录映射/rs/*，那At（）里，只匹配星号*那部分，这种方式不可以
//********************邪恶分割线*******************************

**Comment by zozoh** [comment]
为毛不行？ 说详细点

**Comment by CXW0504** [comment]
web.xml写/*，没问题。但是web.xml写/rs/* 会有问题。
/=============================================
如文档：http://www.nutzam.com/core/mvc/url_mapping.html
-------》这部分：Nutz 中的目录匹配 - /abc/*
如果请求为：
http://localhost:8080/testweb/abc/getlist.nut
对于 Nutz.Mvc 我们需要匹配的部分为：
/getlist
//==================================
At里面要写上前缀
挂载点的filter，不支持前缀

**Comment by zozoh** [comment]
@CXW0504  你安装下面的格式描述一下你的问题:

1. 你的 web.xml 怎么写的? 按你的说法你写的应该是：

```xml
<filter-mapping>
    <filter-name>nutz</filter-name>
    <url-pattern>/rs/*</url-pattern>
</filter-mapping>
```

2. 你的入口函数怎么声明的？

```
@At("/*")
public ??? 
```

3. 你发送的是什么请求? 比如:

```
http://localhost:8080/test/abc...
```

4. 你期望得到什么结果?

5. 实际上你得到了什么结果？

6. 你认为有什么不合理的地方？

**Comment by CXW0504** [comment]
哦。. 
你的 web.xml 怎么写的? 按你的说法你写的应该是：

<filter-mapping>
    <filter-name>nutz</filter-name>
    <url-pattern>/rs/*</url-pattern>
</filter-mapping>
*. 你的入口函数怎么声明的？

. 你的 web.xml 怎么写的? 按你的说法你写的应该是：

<filter-mapping>
    <filter-name>nutz</filter-name>
    <url-pattern>/rs/*</url-pattern>
</filter-mapping>
*. 你的入口函数怎么声明的？

必须在方法上@At("/rs/list")不可以只写成@At("/list")
public ??? 
<!下文引用>
*. 你期望得到什么结果?
希望在 web.xml 来决定 URL 前面那部分，所以后面一部分就交给 Nutz.Mvc 来匹配。否则，修改了 web.xml 的时候，还需要修改 Nutz.Mvc 的配置，这与显然我们设计的初衷不符，Nutz.Mvc 设计的基本要求就是：如果用户修改了 web.xml 或者 server.xml，不需要用户重新修改 Nutz.Mvc 相关的配置（来自http://www.nutzam.com/core/mvc/url_mapping.html中Nutz 中的目录匹配 - /abc/*）

**Comment by wendal** [comment]
en, Filter下的确有问题

**Comment by wendal** [comment]
org.nutz.mvc.impl.UrlMappingImpl.get(ActionContext ac) 这个地方

**Comment by wendal** [comment]
是不是应该在1.r.58里面把它解决掉呢?

**Comment by Wizzercn** [comment]
仔细测试.别改出问题.

**Comment by wendal** [comment]
刚刚想了想,其实没啥用,除非全部都API,没有页面没有forward

**Comment by wendal** [comment]
不然, forward的路径怎么算, 页面的base怎么算?
