### ISSUE TITLE
缓存的相关文档在哪里

### ISSUE THREAD

**Issue by zhangsm** [nutzam/nutz#825]
亲，在官网上找不到介绍缓存机制的相关文档哦.......
我想这样的，在应用层使用缓存，而且能够设置过期时间。nutz中关于缓存的资料在哪里？

**Comment by pangwu86** [comment]
nutz有实现缓存吗?

**Comment by wendal** [comment]
在应用层, 弄好ehcache之类的就可以咯. 不需要什么文档吧

**Comment by wendal** [comment]
https://github.com/nutzam/nutzmore/tree/master/nutz-plugins-daocache
