### ISSUE TITLE
支持更多Http方法

### ISSUE THREAD

**Issue by xbl** [nutzam/nutz#828]
之前想把上传独立出去作为一个单独的项目，在action里resp.setHeader("Access-Control-Allow-Origin", "*");， 使用nutz发现好像不能设置OPTIONS请求方法，好像nutz现在只支持PUT、GET、POST、DELETE

**Comment by wendal** [comment]
不加@GET/@POST/@PUT/@DELETE注解的时候任意Http Method都能映射到入口方法啦

**Comment by wendal** [comment]
不过, 加个注解也可考虑

**Comment by ywjno** [comment]
貌似还有 HEAD TRACE CONNECT 这三个方法要不这次一起都加了得了

**Comment by wendal** [comment]
其实加在@At里面更好... 当初为啥就选了注解呢

**Comment by zozoh** [comment]
@wendal 主要为了总体字会更少一点

**Comment by wendal** [comment]
为@At添加一个method，类型String[],内容为用户自定义的http method。从而避免为webdav新增一堆注解，并删除这个issue所新增的注解
