### ISSUE TITLE
增加@RequestBody 注解

### ISSUE THREAD

**Issue by Wizzercn** [nutzam/nutz#830]
因为获取body数据太常用了，希望增加类似spring mvc里面的 @RequestBody注解，直接获取数据，如果指定类型，可以自动转换。

**Comment by zozoh** [comment]
对于 `@RequestBody` 实际上 Nutz 提供了 `@AdaptBy`
你可以增加任意的 `HttpAdaptor` 去按照你想要的方式处理数据

同时也提供了两种常用的 `HttpAdaptor`

* 对于比较常用的请求，比如，Json 数据，内置了 `@AdapBy(type=JsonAdaptor.class)`
* 如果就是处理输入流，你可以直接入口函数写一个

```java
@At
public void myFunc(InputStream ins) {
       // 这个 ins 就是 Request 的 body
}
```

**Comment by Wizzercn** [comment]
@PUT

         Map<String, Object> map = new HashMap<String, Object>();
            String body = urlUtil.readStreamParameter(req.getInputStream());
            String[] str = StringUtils.split(body, "&");
            for (int i = 0; i < str.length; i++) {
                String[] temp = StringUtils.split(str[i], "=");
                map.put(temp[0], URLDecoder.decode(temp[1], "utf-8"));
            }

自己读字节流，然后转换为map太过繁琐，，能否提供一个类似 @Param("..")NutMap map 的方法，直接转换好。。。

**Comment by Rekoe** [comment]
@Wizzercn 
你可以自己写个过滤器 用来处理put请求 然后返回那个map

**Comment by zozoh** [comment]
如果你的 body 就是普通的 HTML  form 提交的话，用 `@Param("..")NutMap map` 不能自动转换？

**Comment by Wizzercn** [comment]
@PUT  提交的

**Comment by zozoh** [comment]
咦，是有这个问题，先把重现的代码贴一下

客户端代码:

```java
public static void main(String[] args) throws Exception {
    Request req = Request.create("http://localhost:8080/test/put", 
                                 Request.METHOD.PUT);
    req.setData("name=xiaobai&age=20");

    Sender sender = Sender.create(req);
    Response resp = sender.send();

    System.out.println(resp.getContent());
}
```

入口函数:

```java
@At("/put")
@Ok("raw")
public String on_put_pet(HttpServletRequest req) {
    return HttpDumper.dumpData(req);
}
```

输出的是:

```
...
[Host]:localhost:8080
[Connection]:keep-alive
[Content-Length]:19
</HEADERS>
<DATA>
</DATA>
```

如果改成 `POST`

```
... 
[Host]:localhost:8080
[Connection]:keep-alive
[Content-Length]:19
</HEADERS>
<DATA>
age=20
name=xiaobai
</DATA>
```

**Comment by zozoh** [comment]
自己写个 `@AdaptBy` 咯

**Comment by wendal** [comment]
没人做,哈哈
