### ISSUE TITLE
@Readonly在update 时候的问题。

### ISSUE THREAD

**Issue by bugss** [nutzam/nutz#833]
int org.nutz.dao.Dao.update(Class<?> arg0, Chain arg1, Condition arg2) 这个接口。
nutzdao 1.51 版本
表配置
@Table("xd_other")
public class OtherInfo ｛

字段配置
@Readonly
@Column
private String fzh;
其中fzh 不在表xd_other 中 。更新数据依然报
Unknown column 'fzh' in 'field list'

刚刚又试了下，去掉@Column update 依然报错
而且 去掉了@Column  dao.query 带不回fzh的值。 
其实直接执行sql fzh 是有值的，而且加上@Column 后  dao.query   fzh也有值。

帮忙看下。
怀疑 int org.nutz.dao.Dao.update(Class<?> arg0, Chain arg1, Condition arg2) 这个接口
没有对@Readonly 的情况做判断。 最近在客户这边赶项目，没时间调具体原因的，请帮忙看下。我再想办法绕过去。。。。

**Comment by wendal** [comment]
用FieldFilter过滤这个字段

```
Daos.ext(dao, FieldFilter.lock(OtherInfo.class, "fsz")).update(................);
```

话说, 如果Chain和Condition 都不出现fzh的话, sql里面没理由出现fzh的吧

**Comment by bugss** [comment]
Chain 里面是有fzh的，但是既然@Readonly了字段  nutzdao 应该就已经知道了这个字段不用更新，然后任何情况都不应该更新这个字段。

**Comment by bugss** [comment]
现实中组装 Chain  一个字段一个字段的组的情况应该不多吧。  要么是直接读一个Map 自动组装，要么通过pojo 自动组装 ，毕竟前台 的值很容易 在controller 层转换成这两种对象，而不是Chain。 有时候会指定一个updateFields  要表示哪些字段 需要更新。    这就有个问题，不论是map的key ，pojo 的字段名 updateFields  ，传入参数的人很可能不知道这个值是不是数据库中存在的，如果nutzdao 不做这个过滤 很容易就会报我那个错。 
看到了你的回复我突然想到了我现在代码的问题了，加了

				MappingField column = entity.getColumn(f);
				if (column != null && !column.isReadonly()) {
					updateFields.add(f);
				}
就解决了。 
不过还是觉得nutzdao 内部处理好。 我那个错估计稍微 做些通用封装的人 都很可能会出现的。

**Comment by zozoh** [comment]
@bugs 采用 Chain 的方式 update，表示调用者想精确控制具体的字段。
甚至 POJO 没有的字段都可以加入， `@ReadOnly` 注解会被无视的
