### ISSUE TITLE
实体类对象@Id生成策略问题

### ISSUE THREAD

**Issue by pghholl** [nutzam/nutz#839]
目前情况：
1.当实体类主键配置@Id时，不管对象里id是否有值，都走的数据库ID生成策略(例：INSERT INTO test (name) VALUES('test');)，可以通过@Id(auto = false)来配置，走的是自已设定的主键值，但这样非常的不灵活、维护实体类困难，因为同一个实体类使用的场景不一样。
改进建议：
1、当实体类主键配置@Id时，可以根据对象里id是否有值动态判断主键生成策略，这样非常灵活减少维护成本。

**Comment by wendal** [comment]
1. 基本数据类型无法判断有没有值, 因为不能为空
2. 场景不一样,换不同的类操作或者走自定义SQL.

**Comment by zozoh** [comment]
维护实体类困难在哪里了？

**Comment by pghholl** [comment]
1、我觉得用自定义sql和换不同的类操作，这不是解决这个问题，只是换了一种实现方式。
2、维护实体类的困难在于，比如：A应用的user实体类同步数据到B应用，在A应用中user类已经持久化(已经入库有id值了)，那么在A用应通过类的序列化方式传到B应用时，在B应用就不需要在自增id值了，因为拿到的对象已经有id值。此时B应用中user类需要设定@Id(auto = false)才能入库，而A应用的user是@Id。我要维护两个版本的相同的实体类。

**Comment by pghholl** [comment]
实际情况B应用有很多，A的数据同时同步到B、C、D、E应用，实体类又很多......那么维护起来比较麻烦。。。

**Comment by pghholl** [comment]
1、基本数据类型无法判断有没有值, 因为不能为空
@Id时id值是必须要为空的，因为代表着用数据库的主键生成策略。
@Id(auto = false)时id要有值，因为表示程序指定了id值。

我觉得既然支持两种注解方式，那为什么不能动态判断一下呢？或者是增加另外一种注解，更灵活的。。

**Comment by zozoh** [comment]
两个版本相同的实体？ 这种情况，我通常都是做一个基类的
子类只有一个字段， @Id  ， 一个 true 一个 false

**Comment by pghholl** [comment]
我现在新的类是继承了个基类，但是之前开发时没有意识这问题，所以不是所有的类都继承了基类。。。。我觉得用基类这种方式减少了维护，但还是不够灵活。。。。

**Comment by pangwu86** [comment]
感觉多个系统共通一套ID的话,  自己维护比较好

**Comment by pghholl** [comment]
@pangwu86，怎么自已维护呢？请赐教，是两边都自已维护吗？

**Comment by zozoh** [comment]
嗯，不过 @pghholl  的要求我暂时想想也觉得有合理性。
鉴于这个需求比较少，这个问题先放放。
得空了，我再想想怎么改

**Comment by xwqiang** [comment]
关注一下这个问题

**Comment by hzl7652** [comment]
这种场景蛮多的

**Comment by wendal** [comment]
如果要配置,怎么传递这个配置呢... 只能扩展Dao接口吧

**Comment by wendal** [comment]
还需要加文档

**Comment by wendal** [comment]
问题来, 文档应该写到哪了去?

**Comment by hzl7652** [comment]
专门建立一个章节吧，关于主键的

**Comment by bugss** [comment]
1.r.54 发行注记 没有提这个问题 . 具体应该怎么用? 是否已经加了文档了(大致找了下,没有发现相关的说明,看提交的代码好像加了新注解了)

**Comment by wendal2** [comment]
通过FieldMatcher的属性来实现的
