### ISSUE TITLE
扩展Sql类，实现mybatis功能中自定义SQL功能

### ISSUE THREAD

**Issue by Wizzercn** [nutzam/nutz#852]
Sql sql= Sqls.create("user.selectA");
   
     user.json :: {"selectA":[{"select  ..."},{"select ..."}],"selectB":{"select .."} }

通过文件名和参数名，可以执行一条或多条SQL。当然也要支持占位符。

**Comment by wendal** [comment]
有人提过了, 没人肯做, 除非有人发个pull req

**Comment by wendal** [comment]
跟 #852 重复了
