### ISSUE TITLE
Nutz怎么同时使用两个数据库

### ISSUE THREAD

**Issue by newStudent-ls** [nutzam/nutz#858]
求正确的操作方法

**Comment by TuWei1992** [comment]
配置两个datasource

**Comment by newStudent-ls** [comment]
配置好后 如何使用？

**Comment by newStudent-ls** [comment]
我是用JSON 配置文件

**Comment by pangwu86** [comment]
如果你是在ioc里配置的话, 那就通过ioc获取不同的Dao咯

比如配置文件里这样写

<pre>
var ioc = {
	// 数据源1
	dataSource1 : {
		// 省略.....
	},
	// Dao1
	dao1 : {
		type : "org.nutz.dao.impl.NutDao",
		args : [ {
			refer : "dataSource1"
		} ]
	},
    // 数据源2
	dataSource2 : {
		// 省略.....
	},
	// Dao2
	dao2 : {
		type : "org.nutz.dao.impl.NutDao",
		args : [ {
			refer : "dataSource2"
		} ]
	}
};
</pre>

然后代码里

<pre>
    Dao dao1 = ioc.get(Dao.class, "dao1");
    Dao dao2 = ioc.get(Dao.class, "dao2");
</pre>

或者注入

<pre>
    @Inject("dao1")
    private Dao dao1;

    @Inject("dao2")
    private Dao dao2;

</pre>

**Comment by wendal** [comment]
http://wendal.net/356.html
