### ISSUE TITLE
数据表生成，缺少注释！

### ISSUE THREAD

**Issue by ohohco** [nutzam/nutz#862]
···
@Table("product")
public class Product{
        @Column
	@Description("产品名称")
	private String name;
	@Column
	@Description("计量单位")
	private String unit;
}

@Table("my_product")
public class MyProduct extends Product{
        @Column
	@Description("数量")
	private String num;
}
···
生成的表my_product中继承自父类的字段的注释消失了!

**Comment by wendal** [comment]
哦

**Comment by wendal** [comment]
不对啊, Description不是nutz的注解啊
