### ISSUE TITLE
删除关联失效！！！

### ISSUE THREAD

**Issue by ohohco** [nutzam/nutz#871]
这是我实体关联关系 及 业务删除的部分代码：http://nutz.cn/VM

运行结果：http://nutz.cn/VN
`co.ohoh.service.OrganService$2.run(OrganService.java:60) DEBUG - 52` 这里明显debug出来有
单紧接着就说无`alue of LinkField(@ONE-->Contact.addressId) is null`

关联关系的未执行删除！

**Comment by zozoh** [comment]
什么情况？ 咋关了？

**Comment by ohohco** [comment]
一直没人理就关了

**Comment by wendal** [comment]
... 想看看短链接,但已经失效了...
