### ISSUE TITLE
dao.create() 兼容问题

### ISSUE THREAD

**Issue by Wizzercn** [nutzam/nutz#872]
mysql ，创建的表名、表字段都是小写字母；
oracle，创建的表名、表字段都是大写字母。

由于大小写的问题，当我使用自定义查询取map的时候Sqls.callback.maps()，代码就不能兼容两个数据库了.....

如果不想修复这个issue的话，可以在哪个明显位置让开发者注意使用Record 别用map。

**Comment by wendal** [comment]
从代码看, 没有主动将其大写呢
