### ISSUE TITLE
DaoHelper -- 非Mvc,Ioc环境下的使用Dao的工厂类

### ISSUE THREAD

**Issue by wendal** [nutzam/nutz#878]
与其不断告知如何正确使用/建立一个辅助类,还不如直接提供一个官方方案

**Comment by wendal** [comment]
文档工作: 以DaoHelper为基础,写一个10分钟Dao快速入门.

**Comment by wendal** [comment]
测试工作: DaoHelperTest

**Comment by ywjno** [comment]
需要给 pom.xml 里面添加 druid 的 jar 包么？

**Comment by wendal** [comment]
不需要

**Comment by wendal** [comment]
晚上想了想, 对应的TestCase就是最好的文档, 或者说把对应的TestCase的注释写全写好,也就变成了文档

**Comment by wendal** [comment]
已经改名为DaoUp
