### ISSUE TITLE
关于/**的使用出现丢弃/的情况

### ISSUE THREAD

**Issue by pangwu86** [nutzam/nutz#882]
@At("/test/**")
public void test(String str) {
   ..........
}

    理论上 str 会等于 **, 但是如果 ** 以/开头 就会被丢掉, 有几个丢几个

/test/xxx/yyy                 ->      xxx/yyy
/test//xxx/yyy                ->      xxx/yyy
/test///xxx/yyy               ->      xxx/yyy
/test/////////////xxx/yyy     ->      xxx/yyy

**Comment by wendal** [comment]
是不是容器的问题哦?

**Comment by wendal** [comment]
不是容器的问题,但感觉不应该fix啦
