### ISSUE TITLE
>>重定向不支持中文

### ISSUE THREAD

**Issue by enzozhong** [nutzam/nutz#883]
src= /i/2015/6/测试-888x666.jpg
@Ok ( ">>:${obj.pic.src}" )
浏览器url成  /i/2015/6/??-888x666.jpg

若改成
@Ok ( "->:${obj.pic.src}" )
报错页面,能识别为
/i/2015/6/测试-888x666.jpg

环境tomcat 已经加上了URIEncoding="UTF=8"

**Comment by enzozhong** [comment]
解决办法
String path = pic.src.trim ();
path = new String ( path.getBytes ( "UTF-8" ) , "ISO8859_1" );

response.sendRedirect ( path );

**Comment by wendal** [comment]
添加了一个urlencode, 需要转换的字符串, 用

```java
@Ok(">>:xxxx.xxx/xx/xxx/${urlencode(obj.pic.src)}")
```

**Comment by juqkai** [comment]
建议redirect那里改一下文档
