### ISSUE TITLE
自定义sql设置数组参数的问题

### ISSUE THREAD

**Issue by JaynLeaew** [nutzam/nutz#885]
问题描述如下：
select * from t_table where filedname IN (@fieldname)
调用 sql.params().set("fieldname", "value1,value2".split(","));
结果是 fieldname IN ('value1,value2')
而不是 fieldname IN ('value1', 'value2')

**Comment by wendal** [comment]
这个我看看能不能搞定, 纠结很久的问题

**Comment by wendal** [comment]
f3db0cf8f32bd1e70f9249ee75751576e8cc4c79 实现了,但还没覆盖原NutSql实现

**Comment by wendal** [comment]
新的NutSql2实现已经通过全部testcase

**Comment by wendal** [comment]
已经替换为新的实现
