### ISSUE TITLE
oracle自定义sql，按索引查询，被当做注释过滤掉了。

### ISSUE THREAD

**Issue by txc1234** [nutzam/nutz#887]
请教 自定义sql，按索引查询
SELECT /*+ INDEX(A, IDX_T_PERF_PF2H_DI_II_CT)*/ IN_SPEED,
/* */被当做注释过滤掉了， 我查看api没有找到转义符。。。。

**Comment by wendal** [comment]
是java代码还是sql文件?? 完整点

**Comment by txc1234** [comment]
sql文件。

**Comment by txc1234** [comment]
数据库是ORACLE
![1](https://cloud.githubusercontent.com/assets/13115956/8427973/e1462db6-1f4d-11e5-96b1-abc64490d22c.png)

**Comment by txc1234** [comment]
执行sql日志输出：
![1](https://cloud.githubusercontent.com/assets/13115956/8428017/2b7891e4-1f4e-11e5-942f-0060d8fdc5e1.png)

**Comment by wendal** [comment]
恩,收到,检查中

**Comment by wendal** [comment]
添加一个SqlManager实现SimpleSqlManager, 考虑替换现有的FileSqlManager

c202aa91159e6eea14468819a1aec1825ef41dc9

**Comment by wendal** [comment]
SimpleSqlManager基于行解析, 规则与现有的FileSqlManager接近,但更严格

**Comment by wendal** [comment]
剩下文档的更新了,哈啊哈
