### ISSUE TITLE
mvc传参必须@Param？

### ISSUE THREAD

**Issue by csg0328** [nutzam/nutz#891]
开发环境：
Eclipse3.7
 Nutz 1.b.52
jdk1.7

以下是文档上的描述：
-----------------------------------------------------------------------------------------
连@Param都不写(1.b.43+)

public String someFunc(	int pid,
                        String petName){
    ...
那么,这等同于

public String someFunc(	@Param("petId") int petId,
                        @Param("petName") String petName){
    ...
------------------------------------------------------------------------------------------
实际情况：
public Object userReg(String ref, String userName, String password, @Param("mobile") String mobile, @Param("mobileCode") String mobileCode) {
//这样写 mobile mobileCode 可以获取到参数
}

----------------------------------------------------------------------------------------

public Object userReg(String ref, String userName, String password, 
String mobile, 
String mobileCode) {
//这样写 mobile mobileCode 总是null
}

**Comment by wendal** [comment]
netbean吧? 我把描述干掉... 坑

**Comment by fangdong1** [comment]
这里为什么不搞成可以忽略@Param，当然在请求参数名与module中的参数名相同的情况下！

**Comment by wendal** [comment]
@fangdong1 不是不想,是因为必须用ecj编译(eclipse的编译器)才能做到, 大部分用户搞不定

不过JDK8已经有相关API了, 但默认不开,也是够蛋疼的
