### ISSUE TITLE
@One、@Many、@ManyMany字段名易搞混

### ISSUE THREAD

**Issue by linjanin** [nutzam/nutz#896]
@One和@Many的field使用java对象的属性名，实际运行过程中会自动替换成@Column中的字段名，而@ManyMany的from/to使用的直接就是表的字段名，如果已经定义了关联表的POJO对象，并且对字段进行@Column别名，在编码过程中很容易搞混该使用属性名还是字段名。能否统一只使用一种，或者对有单独定义关联POJO的情况提供另一种@ManyMany注解？

像下面4个表，Account和LoginHistory为一对多关系，Account通过Account_Role与Role建立了多对多关系，Account的@Many和@ManyMany中的字段名就显得很混乱。因为有Account_Role对象在，在写@ManyMany时，习惯性的就将from写成了from="accountId:id"。

Account:
    @Many(target = LoginHistory.class, field = "accountId")
    private List<LoginHistory> loginHistories;

    @ManyMany(target = Role.class,
            relation = "r_account__role",
            from = "account_id:id",
            to = "role_id:id")
    private List<Role> roles;

LoginHistory:
    @Column("account_id")
    private int accountId;

    @One(target = Account.class, field = "accountId")
    private Account account;

Role:
    @ManyMany(target = Account.class,
            relation = "r_account__role",
            from = "role_id:id",
            to = "account_id:id"
    )
    private List<Account> accounts;

Account_Role:
    @Column("account_id")
    private int accountId;

    @Column("role_id")
    private int roleId;

**Comment by wendal** [comment]
@ManyMany里面的from和to都是可以写属性名称的,默认也是

**Comment by linjanin** [comment]
我使用的是1.b.52版，在Setup时使用扫描方式创建数据表：

    Daos.createTablesInPackage(dao, POJO_PACKAGE, false);

当Account先于Account_Role创建时，会同时自动创建关联表语句：

    @ManyMany(target = Role.class,
            relation = "r_account__role",
            from = "accountId:id",
            to = "roleId:id")
    private List<Role> roles;

    CREATE TABLE r_account__role(accountId NUMERIC(8),roleId NUMERIC(8))

这里sql会直接使用@ManyMany描述的字段名，所以才改成如下描述：

    @ManyMany(target = Role.class,
            relation = "r_account__role",
            from = "account_id:id",
            to = "role_id:id")
    private List<Role> roles;

    CREATE TABLE r_account__role(account_id NUMERIC(8),role_id NUMERIC(8))

当然，如果能保证Account_Role先于Account创建就不会有问题，项目小时还好说，当项目变大、人员变多时就不好保证了。

不知@ManyMany的relation是否支持Class<?>类型的参数？如果能像如下这样来描述映射关系，该使用何种名称就比较清晰了。

    @ManyMany(target = Role.class,
            relation = Account_Role.class,
            from = "accountId:id",
            to = "roleId:id")
    private List<Role> roles;

**Comment by wendal** [comment]
还是不解决了, 遇到的时候注意一下顺序就好了
