### ISSUE TITLE
Sqls.create().params().set() 等用法的支持

### ISSUE THREAD

**Issue by Wizzercn** [nutzam/nutz#903]
经常在写自定义SQL的时候，准备如题这样赋值，发现不行，往往要另起两行：
Sql sql = Sqls.create();
sql.params().set();
然后再执行，，
这样看似不复杂，但日积月累在无形中增加了开发时间，每用到此处都觉得理应更灵活方便些。

**Comment by wendal** [comment]
应该是  sql.setParam(......).setParam(......).setParam(......).setParam(......).setParam(......)

**Comment by wendal** [comment]
可以一行写到底了

```java
List<User> list = dao.execute(Sqls.create("select * from user where age > @age").setParam("age", 18)).getList(User.class);
```
