### ISSUE TITLE
使用53版本的jar上传图片压缩后显示不全

### ISSUE THREAD

**Issue by liouhongde** [nutzam/nutz#904]
我使用53版本的jar上传附件并生成缩略图，缩略图显示不完整。
代码如下
			//缩略图处理
			try {
				File file_max = new File(filepath+filename_qi+"_"+Properties.getImageShrink()+"x"+Properties.getImageShrink()+type);
				Images.zoomScale(file, file_max, Properties.getImageShrink(), Properties.getImageShrink(), Color.WHITE);
				s_file_max = filename_qi+"_"+Properties.getImageShrink()+"x"+Properties.getImageShrink()+type;
			} catch (Throwable e) {
				log.info(e);
			}

大家帮看看是如何问题
原图地址：http://liouhongde.xicp.net:9999/a.jpg

**Comment by wendal** [comment]
恩,晚上看看

**Comment by wendal** [comment]
能不能把参数写清楚...

**Comment by liouhongde** [comment]
try {
File file_max = new File(filepath+filename_qi+"250x250"+type);
Images.zoomScale(file, file_max, 250, 250, Color.WHITE);
} catch (Throwable e) {
log.info(e);
}

**Comment by wendal** [comment]
我试了一下, 发现没问题呢

这个图原本不是正方形的, 然后缩放为250*250, 肯定有无白边/黑边啊

**Comment by wendal** [comment]
我猜你要的是 Images.clipScale 这是缩放到指定大小,然后去掉多余的部分

**Comment by liouhongde** [comment]
http://liouhongde.xicp.net:9999/b.jpg
这是我处理的图片！

**Comment by wendal** [comment]
打不开

**Comment by wendal** [comment]
是不是你上传的时候有问题啊

我本地执行了一次, 输出正常呢

```
    @Test
    public void test_issue_904() throws IOException {
        InputStream ins = getClass().getResourceAsStream("full_max.jpg");
        File file_max = new File("250x250.jpg");
        Images.zoomScale(ins, file_max, 250, 250, Color.WHITE);
    }
```
