### ISSUE TITLE
关于多对多关联插入！

### ISSUE THREAD

**Issue by ohohco** [nutzam/nutz#905]
先上涉及的对象代码：
```
class Project{
    @ManyMany(from="project_id", relation="project_user_xxx", target=Role.class, to="user_id")
    private List<User> xxxUsers;
    
     @ManyMany(from="project_id", relation="project_user_yyy", target=Role.class, to="user_id")
    private List<User> yyyUsers;
}
```
上述代码简单描述了某个项目工程中，参与xxx,yyy业务的用户，用户表不可变。由于关联用户`关系`随时可变，代码业务实现中需要先`删`中间表，然后再`插入`新的关联关系，dao是否可一个只插入关联关系的方法

**Comment by ohohco** [comment]
这里是我犯糊涂了，`target=Role.class` 这里应该是`User.class`.
兽哥帮忙解决了，让我报个issue，让这里的日志提醒清晰。提示也是有的，`...Fail to invoke...` copy代码有时候就这样 忘了改。
另外贴出出错的日志：http://nutz.cn/dv

**Comment by wendal** [comment]
不是有insertLinks吗?
