### ISSUE TITLE
指定json视图返回的content type 为application/json

### ISSUE THREAD

**Issue by TuWei1992** [nutzam/nutz#907]
RT, 目前返回的是text, 这样使用浏览器调试不是很方便, 还有就是一些app开发的框架 严格验证content type, 比如ios 的 afnetworking

**Comment by zozoh** [comment]
嗯，你先仿照自定义视图做个自己的 json 视图顶个先吧。
我们下一版就加上

**Comment by wendal** [comment]
做成配置项?

**Comment by wendal** [comment]
我还想做个jsonp呢, 貌似可以一直搞

**Comment by zozoh** [comment]
起码默认的应该是 `application/json` 现在是 `text/plain`

**Comment by wendal** [comment]
81af1eeee50f7b837fa09d24c663e49f84369a1e

**Comment by zozoh** [comment]
* `@Ok("json")` 将让 ContentType 变成 *application/json*
* `@Ok("jsonp")` 将让 ContentType 变成 *application/javascript*

是这样吧

**Comment by wendal** [comment]
对
