### ISSUE TITLE
cnd自动添加单引号引起查询出错

### ISSUE THREAD

**Issue by enzozhong** [nutzam/nutz#912]
Cnd cnd1 = Cnd.where ( "gpId" , "=" , gp.gpId )
			.and ( "y" , "=" , time.tell2Int ( Attr.YEAR ) )
			.and ( "m" , "=" , time.tell2Int ( Attr.MONTH ) )
			.and ( "d" , "=" , time.tell2Int ( Attr.DAY ) )
			.and ( "k.c" , ">=" , "k.o" );

生成的SQL为
WHERE gpId=2 AND y=2009 AND m=12 AND d=29 AND k.c >= 'k.o'

问题就在于生成了
k.c >= 'k.o'

期待生成的是
k.c >= k.o

着算是bug吗?

**Comment by wendal** [comment]
and(new Static("k.c > k.c"))
