### ISSUE TITLE
 MainModule 使用了#At 注解, 方法#At 重复 merge 问题

### ISSUE THREAD

**Issue by TuWei1992** [nutzam/nutz#913]
当MainModule 使用了 `@At` 注解, MainModule里面的 `@At` 方法 的Url 会重复merge 一遍Mainmodule的url

![1](https://cloud.githubusercontent.com/assets/4727141/8974053/cfac5a44-369f-11e5-894e-59a76882e536.jpg)

![2](https://cloud.githubusercontent.com/assets/4727141/8974055/d42340a6-369f-11e5-885e-6cb41c14b7bc.jpg)

**Comment by zozoh** [comment]
当然，就是这么设计的，你可以不在 MainModule 上加 `@At`
