### ISSUE TITLE
关于注解@View 和@@Readonly的问题

### ISSUE THREAD

**Issue by ohohco** [nutzam/nutz#918]
* `@View`
在实体上声明`@View`后，在使用`Daos.createTablesInPackage(dao, "....", true);`创建表的时候，如果视图不存在,会抛找不到视图的异常http://nutz.cn/fp
* `@Readonly`
 字段只声明了`@Readonly`是不起作用的，需要声明`@Column`.但是声明`@Column` 后，在使用`Daos.createTablesInPackage(dao, "....", true);`建表时，该被声明的字段还是会创建

**Comment by wendal** [comment]
第一个已经单独开issue #917

**Comment by wendal** [comment]
解决方法: 依然要求加@Column(如果其他属性加了@Column的话), 但建表时忽略

**Comment by ohohco** [comment]
我现在的情况是建表时候没有忽略。
```
public abstract class AbstractXxx{
	@Readonly
	@Column
	private int level;
        ...
}
```
```
@Table("...")
public class Xxx extends AbstractXxx{
...
}
```

**Comment by wendal** [comment]
最新的代码？整个类贴一下吧

**Comment by ohohco** [comment]
父类 http://nutz.cn/g6  
子类 http://nutz.cn/g7
这个level是@Readonly的，`Daos.createTablesInPackage(dao, "....", true);`会将level建到数据库

**Comment by wendal** [comment]
我试了最新的代码,没问题呢

```
2015-08-11 14:37:02,795 org.nutz.dao.impl.sql.run.NutDaoExecutor._runStatement(NutDaoExecutor.java:313) DEBUG - CREATE TABLE regions(
id SERIAL,
name VARCHAR(50),
code VARCHAR(50),
zip_code VARCHAR(50),
p_id NUMERIC(16),
lft NUMERIC(16),
rgt NUMERIC(16),
status NUMERIC(8) DEFAULT '1',
CONSTRAINT regions_pkey PRIMARY KEY (id)
)
```

**Comment by ohohco** [comment]
嗯 最新的是解决了！好了 现在可以用快照版了
