### ISSUE TITLE
需求：直接执行sql文件的需求！

### ISSUE THREAD

**Issue by ohohco** [nutzam/nutz#920]
既然dao都这么强大了，发现却没有直接执行sql文件的方法！

**Comment by ywjno** [comment]
来看看文档吧，http://nutzam.com/core/dao/customized_sql.html

**Comment by ohohco** [comment]
楼上不是你想的那样，我问的是直接执行sql文件，是文件。

**Comment by ywjno** [comment]
你看到了『Nutz.Dao SQL 文件的格式』这段了么？

**Comment by ohohco** [comment]
我竟无言以对

**Comment by ohohco** [comment]
这么说吧！按照你说的，你直接用工具比如navicat保存表及记录为sql文件，请问你用『Nutz.Dao SQL 文件的格式』这个怎么去执行！

**Comment by wendal** [comment]
我想过了,这种东西, Runtime.getRuntime().exec 执行本地程序导入才靠谱

**Comment by ohohco** [comment]
还有这么好的东西啊！

**Comment by Rekoe** [comment]
这个方法就是干这用的
