### ISSUE TITLE
关于ioc的一点问题

### ISSUE THREAD

**Issue by limzlovecwh** [nutzam/nutz#924]
您好，今天我学习nutz试了一下ioc的功能，代码及使用json格式配置文件均来自网站上的实例。但是运行过程中有点小问题。
以下是使用的json格式的配置文件：
var ioc = {
    /*
     * 默认的，你仅仅需要直接声明每个字段的值即可，Nutz.Ioc 会为你转型
     */
    xiaobai : {
        name : 'XiaoBai',
        birthday : '2009-10-25 15:23:40'
    },
    /*
     * 你当然也可以做更细致的设置
     */
    xiaohei : {
        type : 'com.xiu8.nutz.ioc.Pet', // 类型
        singleton : false, // 是否为单件
        args : [ 'XiaoHei' ], // 构造函数参数
        fields : {
            birthday : '2009-11-3 08:02:14',
            friend : {refer : 'xiaobai'}	// 指向容器里另外一个对象
        }
    }
}
json格式的配置文件中惟一与网站示例不同的是type：我指定的自己的类全路径。同时在测试的main方法里我的jsonLoader使用的获取配置文件路径的地方也同样是com/xiu8/nutz/ioc/pets.js

我测试的结果是当你在main方法中获取xiaobai对象没问题，但是获取xiaohei对象时分两种情况：
1.如果获取xiaohei对象之前已经使用容器.get方法获取了xiaobai对象，那么获取xiaohei对象没有问题，
2.如果获取xiaohei对象之前没有调用容器.get方法获取xiaobai对象，那么直接获取xiaohei时会报出Exception in thread "main" org.nutz.ioc.IocException: NULL TYPE object 'xiaobai'异常。
不知道这样的问题算不算小bug，个人分析是因为在获取xiaohei时引用了容器中的另一个对象，而容器没能在获取某个对象时先获取该对象内引用类的实例，所以导致了这个问题。

**Comment by wendal** [comment]
第一种方式(无type)不推荐小白使用.

**Comment by limzlovecwh** [comment]
我在第一个xiaobai对象那里加了type:'com.xiu8.nutz.ioc.Pet'，运行结果依然是NULL TYPE object 'xiaobai'

**Comment by wendal** [comment]
你不能直接加, 要加type要整个改成第二种的格式, 就是原有的属性转为fields下
