### ISSUE TITLE
建议把 nutz 启动时 扫描的 Class 保存 下来

### ISSUE THREAD

**Issue by TuWei1992** [nutzam/nutz#926]
RT,MVC 的应用情境下, 在写一些插件的时候, 很可能会用到 所有的 Module, 这时候就需要自己扫描一遍所有的Class, 建议扫描后保存在NutConfig, 这样就不用自己扫描了

**Comment by zozoh** [comment]
你如果想看映射关系，可以:

```java
AtMap am = Mvcs.getAtMap();
```

是 URL 到方法的映射关系表

**Comment by TuWei1992** [comment]
AtMap 我看了, 好像只有url 和 方法的映射.
我现在有这样一个需求, 就是做一个基于注解拦截方法的权限校验框架.
在Module 的上有一个注解, 用来给module 内的方法(Resource) 简单分组.
如果只得到所有方法(Resource)的话, 处理起来会比较麻烦.

**Comment by wendal** [comment]
https://github.com/nutzam/nutzmore/blob/master/nutz-integration-shiro/src/main/java/org/nutz/integration/shiro/NutShiroAopConfigure.java

**Comment by wendal** [comment]
走AOP就是了

**Comment by TuWei1992** [comment]
我还是吧AtMap中的method过滤了一边, 关了吧...
