### ISSUE TITLE
关于 Daos.safeClose(stmt, rs);

### ISSUE THREAD

**Issue by yudatou123** [nutzam/nutz#930]
public static void safeClose(Statement stat, ResultSet rs) {
        safeClose(rs);
        safeClose(stat);
    }
这个方法可以废弃掉吧

官方文档介绍关闭Statement 时候可以自动把ResultSet  关闭
* <P>
     * <B>Note:</B>When a <code>Statement</code> object is
     * closed, its current <code>ResultSet</code> object, if one exists, is
     * also closed.

**Comment by wendal** [comment]
这个问题不大吧,无所谓啦
