### ISSUE TITLE
List<TaskHistory> ls = dao.query(TaskHistory.class, null, null);这样的语句在TaskHistory继承基类的情况下出现类型转换异常

### ISSUE THREAD

**Issue by fangdong1** [nutzam/nutz#937]
http://nutzbook.wendal.net/
做上面链接中的例子时发现的。

基类和上面连接中wendal提供的例子一样，类的定义和全部属性：
```
public class BasePojo {
	@Column("create_time")
    private Date createTime;
	
	@Column("update_time")
    private Date updateTime;
```
完全按照http://nutzbook.wendal.net/里面的说明开发，但是@Table("t_task_history")
public class TaskHistory implements Serializable这样定义TaskHistory时下面的查询能正常执行，返回全部结果：
```
List<TaskHistory> ls = dao.query(TaskHistory.class, null, null);
```

但是当TaskHistory继承自BasePojo类之后dao.query(TaskHistory.class, null, null)这句代码会导致下面的异常（dao.query(TaskHistory.class, null)一样）：
```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.util.List
	at org.nutz.dao.impl.sql.NutStatement.getList(NutStatement.java:110)
	at org.nutz.dao.impl.NutDao.query(NutDao.java:437)
```
另外：实体类继承BasePojo之后，BasePojo中的属性对应的字段的值，有时候能从DB中读出、有时候不能读出！

希望nutz能越来越好、真正让大家放心地在各种规模的项目中使用！

**Comment by wendal** [comment]
请把2个类都贴全

**Comment by wendal** [comment]
另外，是不是用了缓存？

**Comment by wendal** [comment]
再然后, 看 query的三参数版本

```
    public <T> List<T> query(Class<T> classOfT, Condition cnd) {
        return query(classOfT, cnd, Pojos.Items.pager(cnd));
    }
```

其中 Pojos.Items.pager(cnd)

```
		public static Pager pager(Condition cnd) {
			if (null == cnd) {
				return null;
			}
			// 高级条件
			else if (cnd instanceof Criteria) {
				return ((Criteria) cnd).getPager();
			}
			// 普通条件
			else {
				return null;
			}
		}
```

所以, query(XXX.class, null) 完全就是 query(XXX.class, null, null)

**Comment by fangdong1** [comment]
用了ehcache的缓存

**Comment by fangdong1** [comment]
@Table("t_task_history")
public class TaskHistory implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 4145658375659376589L;

	@Id
    protected int id;
	
	/**
	 * 任务的代号，由clientCode_创建人帐号构成，非唯一
	 */
	@Column("task_code")
	private String taskCode;
	
	@Column("task_url")
	@ColDefine(width=2048)
	private String taskUrl;
	
	/**
	 * 任务执行后从jenkins的rest服务获取的response的Location头的值
	 */
	@Column
	@ColDefine(width=1024)
	private String location;
	
	/**
	 * jenkins的rest服务的响应的状态码，200-300之间的可视为操作成功
	 */
	@Column
	private int status;
	
	/**
	 * 任务是否执行成功，服务端返回状态在200-300之间并且Location不为空才为成功。
	 * 可选数值包括成功、失败两个。
	 */
	@Column
	private String result;
	
	/**
	 * 操作人帐号
	 */
	@Column
	private String oper;
	
	@Column("create_time")
    private Date createTime;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTaskCode() {
		return taskCode;
	}

	public void setTaskCode(String taskCode) {
		this.taskCode = taskCode;
	}

	public String getTaskUrl() {
		return taskUrl;
	}

	public void setTaskUrl(String taskUrl) {
		this.taskUrl = taskUrl;
	}

	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getResult() {
		return result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public String getOper() {
		return oper;
	}

	public void setOper(String oper) {
		this.oper = oper;
	}
	
	public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    public String toString() {
        return String.format("/*%s*/%s", super.toString(), Json.toJson(this, JsonFormat.compact()));
    }
    
}

public class BasePojo {
	@Column("create_time")
    private Date createTime;
	
	@Column("update_time")
    private Date updateTime;
	
	public String toString() {
        return String.format("/*%s*/%s", super.toString(), Json.toJson(this, JsonFormat.compact()));
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}

这类贴不贴感觉没啥区别呀

**Comment by wendal** [comment]
去掉缓存,再测试, 看来是缓存的问题了

**Comment by wendal** [comment]
什么数据库什么版本？

**Comment by fangdong1** [comment]
数据库是mysql 5.6

**Comment by fangdong1** [comment]
为wendal点赞，经测试的确是缓存的问题！

用缓存时dao.query(Role.class, Cnd.where("1", "=", "1"), null);正常！

不用缓存查询慢，另外MyBatis支持对任意查询sql的缓存，而不仅仅是对表设置，希望nutz在对缓存的支持上也能不断增强！

**Comment by wendal** [comment]
其实支持任意的，只是临时限制着

感觉是某个sql的指纹刚好与这个查询的指纹一致，而那个查询的结果是个int，所以导致这个问题

**Comment by wendal** [comment]
看来要再设计一下缓存的key

**Comment by fangdong1** [comment]
我跟进到nutz dao层的代码调试过，看起来生成的sql没问题，但就是执行结果出问题

nutz是个能够打动人的框架，我很看好这个，祝愿这个框架能发展的越来越好！

**Comment by fangdong1** [comment]
另外：实体类继承BasePojo之后，BasePojo中的属性对应的字段的值，有时候能从DB中读出、有时候不能读出！

这个问题希望也能关注下！

**Comment by ywjno** [comment]
什么时候不能读出详细写一下啊

**Comment by fangdong1** [comment]
不知道，反复刷新能看到有时候不能读出来，频率蛮高的

**Comment by wendal** [comment]
找规律

**Comment by fangdong1** [comment]
还有个问题：
Sql sql = Sqls.fetchEntity("select u.*, r.id as roleId from t_user u, t_user_role ur, t_role r where u.id=@id and u.id=ur.u_id and ur.role_id=r.id");
	    sql.params().set("id", id);
	    Entity<User> entity = dao.getEntity(User.class);
	    sql.setEntity(entity);
	    dao.execute(sql);
	    User us = sql.getObject(User.class);

User、Role都是http://nutzbook.wendal.net/中的对象，我在User中添加了roleId属性，但上面的代码执行时，死活都不能把sql语句查出来的结果放到对象中！

**Comment by wendal** [comment]
先查出为Record，然后Record类有根据不同前缀生成对象的方法
