### ISSUE TITLE
@ManyMany 问题

### ISSUE THREAD

**Issue by TuWei1992** [nutzam/nutz#938]
现在有一个需求, 就是想中间表某字段存非主键, 因为其中的一个映射表内容是每次启动程序都更新的, 所以表字段里面有增加了一个唯一Id(varchar), 但是内容太长, mysql 不能作为主键, 因为manymany只能使用主键, 所以处理起来很麻烦, 可不可以让manymany 可以指定映射的字段?

**Comment by TuWei1992** [comment]
使用@Name 解决

**Comment by ywjno** [comment]
不是主键的话能保证唯一么

**Comment by TuWei1992** [comment]
可以保证唯一, 存的是方法的唯一编码

**Comment by wendal** [comment]
manymany没说要主键吧？from to都可以这样 a表字段:中间表字段a
