### ISSUE TITLE
Report a possible race issue

### ISSUE THREAD

**Issue by baigd** [nutzam/nutz#943]
Hi, Developers of nutzam/nutz,

I am writing to report a race issue on use of ConcurrentHashMap. The issue is reported by our tool in an automatic way. Although manually confirmed, it would be a false positive, given we do not know the specification of the program. We would very appreciate if you could check below for details and confirm with us whether it is a real problem. For more information, please refer to our website: http://sav.sutd.edu.sg/?page_id=2845

File: nutzam/nutz/src/org/nutz/dao/impl/EntityHolder.java
Location: Line (63/66, 48/42/78)
Description: 
The synchronized block on "map" from line 62 to line 68 contains a get-then-put operation on "map". If the intention of the synchronized block is to guarantee the atomicity of the get-then-put operation, then the write operations in line 42, 48 and 78 may break this atomicity. Relying on the ConcurrentHashMap to ensure exclusive access is dangerous since ConcurrentHashMap has no guarantee of exclusive access.

**Comment by zozoh** [comment]
@baigd robot ?
