### ISSUE TITLE
bug: NutDaoExecutor Can't identify SQL type

### ISSUE THREAD

**Issue by limingwei** [nutzam/nutz#945]
org.nutz.dao.impl.sql.run.NutDaoExecutor Can't identify SQL type :   ( SELECT * FROM t_thread WHERE forum_id=1 ORDER BY id DESC LIMIT 5 )  UNION  ( SELECT * FROM t_thread WHERE forum_id=2 ORDER BY id DESC LIMIT 5 )  UNION  ( SELECT * FROM t_thread WHERE forum_id=3 ORDER BY id DESC LIMIT 5 )

**Comment by zozoh** [comment]
因为 Nutz 的 SQL 执行器需要判断 SQL 的类型，你給它再套个 SELECT 试试

```sql
SELECT * FROM
 ( SELECT * FROM t_thread WHERE forum_id=1 ORDER BY id DESC LIMIT 5 ) UNION ( SELECT * FROM t_thread WHERE forum_id=2 ORDER BY id DESC LIMIT 5 ) UNION ( SELECT * FROM t_thread WHERE forum_id=3 ORDER BY id DESC LIMIT 5 )
```

**Comment by limingwei** [comment]
套个 SELECT 相信是可以的
现在弄了个 ((NutStatement) sql).setSqlType(SqlType.SELECT)

**Comment by wendal** [comment]
不需要的 调用一下 sql.forceQuery() 就好了
