### ISSUE TITLE
nutz struts2整合

### ISSUE THREAD

**Issue by chenTest2013** [nutzam/nutz#947]
用hibernate是在是太重，然后想用轻量级 简洁高效的类似框架，同事推荐nutz，发现真的好用而且还小，由于种种原因，想让nutz只完成hibernate的工作，视图控制交给struts2，于是想到整合，不知可行，或者说如何整合，我看到nutz在web.xml中配置了过滤器，struts2也需要配置过滤器，貌似。。。。请问陈老师，可否提供下思路或建议？

**Comment by enzozhong** [comment]
先弄个全局IOC,然后从IOC中获取DAO就OK了~

**Comment by chenTest2013** [comment]
谢谢!嗯，我也是这样想的，刚接触nutz，nutz的IOC的创建过程不知是怎样的？

**Comment by wendal** [comment]
实现一个ObjectFactory就可以了

https://struts.apache.org/docs/objectfactory.html

**Comment by wendal** [comment]
另外, 全局Ioc可以走 org.nutz.mvc.NutMvcListener

**Comment by wendal** [comment]
供参考 

https://github.com/nutzam/nutzmore/blob/master/nutz-integration-struts2/src/main/java/org/nutz/integration/struts2/NutObjectFactory.java

**Comment by chenTest2013** [comment]
@wendal 刚看到谢谢，来研究研究
