### ISSUE TITLE
文件池使用IOC管理时，使用pool.removeFile(long paramLong, String paramString)无法删除文件

### ISSUE THREAD

**Issue by jiyuefeng** [nutzam/nutz#950]
ioc配置：
pool: {
        type: 'org.nutz.filepool.NutFilePool',
        args: ["~/nutz/upload/tmps", 1000]
    },

使用：
@Inject
FilePool pool;
pool.removeFile(3, “.png”);

**Comment by jiyuefeng** [comment]
在Service下注入FilePool删除无效，但是在Action上可以正常操作

**Comment by zozoh** [comment]
那为啥关了？
