### ISSUE TITLE
希望完善nutz mvc获取请求参数的方式

### ISSUE THREAD

**Issue by fangdong1** [nutzam/nutz#956]
http://www.angularjs.cn/A0jl

请相关开发人员详细看上面的链接，nutz当前的最新版本存在同样的问题！推测造成该问题的原因也是一样的！

这个问题发生在把angularjs和nutz集成时，具体情况：
var params = {
				"product" : 'product1',
				"reqtype" :6,
				"time" : '2015-07-23-14-31-00'
			};
对于上面的请求参数，下面这个angularjs的请求总能成功发送到nutz的module，但是死活都无法获得请求参数的值（下面同样的js代码，spring的controller可以成功获取请求的各个参数值）：
$http.post('/dapm/crash/stat', params).success(
						function(data) {
							alert(data.list);
						});
而jquery下面的方式可以成功，但显然jquery的代码量更大：
$.ajax({
				url : "url",
				type : "POST",
				data : params,
				error : function(request) {
					alert("Connection error");
				},
				dataType : "json",
				success : function(data) {
					if (data && data.ok) {
						$scope.chartData=data;
					} else {
						alert("error:"+data);
					}
				}
			});
nutz的module：
public Object getProductStat(@Param("product")String product, @Param("reqtype")int reqtype,@Param("time")String time)

解决办法：
把上面angularjs的post请求那块代码替换成下面这样：
var transform = function(data){
			    return $.param(data);
			};
$http.post('/dapm/crash/stat', params,{
        headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'},
				    transformRequest: transform
}).success(function(data) {
	alert(data.list);
});

但这个问题也可以从nutz的mvc部分解决，就是请求参数解析那块代码，希望nutz能象spring那样，对这部分进行完善！

**Comment by wendal** [comment]
```
@AdaptBy(type=JsonAdaptor.class)
```

加上完事.

**Comment by fangdong1** [comment]
为wendal、为nutz点赞，经验证，添加了@AdaptBy(type=JsonAdaptor.class)之后的确可以！
