### ISSUE TITLE
建议增加对hbase访问的支持

### ISSUE THREAD

**Issue by fangdong1** [nutzam/nutz#963]
因为hbase的应用越来越广泛，在很多领域hbase是替换数据库的良好选择，强烈建议增加对hbase操作的支持！谢谢

**Comment by fangdong1** [comment]
支持的功能可以包括：连接、数据操作、查询等，希望能很快看到可用的nutz的hbase操作工具！

**Comment by wendal** [comment]
语法跟mysql差不多吗? 貌似不支持limit呢?

谷歌了一下, 分页比较难搞

**Comment by wendal** [comment]
哦, 我还以为是走jdbc呢

**Comment by ywjno** [comment]
不支持 jdbc 的就先算了

**Comment by wendal** [comment]
没人提交pull req, 这事就是空谈
