### ISSUE TITLE
希望完善nutz mvc获取请求参数的方式 #956重发

### ISSUE THREAD

**Issue by fangdong1** [nutzam/nutz#975]
对于普通的请求，在module的方法上添加@AdaptBy(type=JsonAdaptor.class)的确管用！

但是对于登录请求，集成shiro之后，无法添加@AdaptBy(type=JsonAdaptor.class)，这种情况下还是要用到issue #956中提到的方法才行！

不知道wendal怎么看？

**Comment by wendal** [comment]
最新的shiro插件能识别吧, 里面有判断是不是json格式的请求

```
        HttpServletRequest req = (HttpServletRequest)request;
        if (req.getHeader("Content-Type") != null &&req.getHeader("Content-Type").contains("json")) {
            NutMap jsonParams = Json.fromJson(NutMap.class, req.getReader());
            req.setAttribute(JsonParams_KEY, jsonParams);
        }
```

**Comment by fangdong1** [comment]
shiro-all-1.2.3.jar这个不行

最新的是哪个版本？shiro-all-1.2.3.jar是我上个月刚刚下载的

**Comment by fangdong1** [comment]
最新版本支持就好，以后这块就方便了一些，谢谢wendal！

**Comment by Rekoe** [comment]
@fangdong1 你下的是shiro的jar
兽说的是nutz的shiro插件

**Comment by fengme** [comment]
shiro的这个插件的代码真哪里？
不是真last那个jar包中吗？

**Comment by wendal** [comment]
https://github.com/nutzam/nutzmore/tree/master/nutz-integration-shiro
