### ISSUE TITLE
org.nutz.dao.Chain与org.nutz.mvc.annotation.Chain重名了

### ISSUE THREAD

**Issue by enzozhong** [nutzam/nutz#976]
项目中用了org.nutz.mvc.annotation.Chain,但是文件中经常使用org.nutz.dao.Chain小颗粒的update,导致整个文件一堆包来包去的,建议org.nutz.dao.Chain下public DefaultChain

**Comment by wendal** [comment]
木有办法的... 得兼容老版本

**Comment by enzozhong** [comment]
不用改名,就是把private DefautlChain改为public,私有也只有Chain会调用了,接口什么的都没有变化

**Comment by wendal** [comment]
哦, 考虑一下
