### ISSUE TITLE
建议增加 ResultSetLooping 游标增加对记录数做限制

### ISSUE THREAD

**Issue by ashangpeng** [nutzam/nutz#985]
今天在做压力测试的时候，发现对数据条数没有限制，导致内存溢出；

1、建议在做表里数据转对象的方式，建议增加条数限制，以及告警；
ResultSetLooping
if(index>3000) log.info(XXXXXXXXXXX);
if(index>30000) throw exception;
配置留给用户配置
2、对慢sql建议增加日志，代码抛出异常，比查mysql 的slow_sql 更容易知道场景。，
如增加超时机制，等

**Comment by wendal** [comment]
1. 哪有限制这个的
2. 数据库连接池druid就带这种功能,我们线上就是用它, 不需要dao来做

**Comment by wendal** [comment]
话说, 只有sqlserver2000才是游标分页哦, 这么老的数据库,别要求什么性能了吧

**Comment by ashangpeng** [comment]
因为我们现在查询的数据是mysql 数据量近百万，如果那个sql查询没带条件或者1=1会内存溢出，我说的是应用；

2015-11-30 5:01 GMT+01:00 Wendal Chen <notifications@github.com>:

**Comment by ashangpeng** [comment]
因为我们现在查询的数据是mysql 数据量近百万，如果那个sql查询没带条件或者1=1会内存溢出，我说的是应用；

**Comment by ashangpeng** [comment]
![image](https://cloud.githubusercontent.com/assets/4099542/11482686/7c67f076-97a4-11e5-9789-6fbe2acc47d5.png)

**Comment by ashangpeng** [comment]
![image](https://cloud.githubusercontent.com/assets/4099542/11482735/c84d81fe-97a4-11e5-8aa3-617a4f04b789.png)
返回list记录过多，就会出现内存溢出。

**Comment by wendal** [comment]
恩,加个日志吧
