### ISSUE TITLE
@Ok（）配置视图中获取session中的值

### ISSUE THREAD

**Issue by enzozhong** [nutzam/nutz#987]
现在@Ok(xxx:${ obj.xxx } )可以通过这种方法取值，是否能够也通过这种语法获取到session的值呢？
或者区分下@Ok( xxx: %{ ses.xxx } ) 来获取session中的值？

**Comment by wendal** [comment]
https://nutz.cn/yvr/t/uh58ubved4hl6oukt9lkltpfpn
