### ISSUE TITLE
官网的文档是不是写错了，Json.fromJson 应该是Json.toJson

### ISSUE THREAD

**Issue by CXW0504** [nutzam/nutz#990]
compact -- 是否为紧凑模式,默认为false. 若为true,indent和indentBy将无效.

Json.fromJson(pet, JsonFormat.full().setCompact(true)); // 不作任何换行和缩进
quoteName -- key是否用双引号包起来,默认为true,同时也是json标准格式的要求. 若设置为false,则新版的jquery将解析出错.

Json.fromJson(pet, JsonFormat.full().setQuoteName(false)); // 输出类似 {name:"wendal"}
ignoreNull -- 是否忽略控制,默认为false

Json.fromJson(pet, JsonFormat.full().setIgnoreNull(true)); // null值的key-value将不会输出,但空List还是会的.
actived -- 仅输出哪些的key,默认为null,即允许所有key. 注意,这是正则表达式!

Json.fromJson(pet, JsonFormat.full().setActived("^(name|id|location)$"); // 仅输出name/id/location,其他key都不输出
locked -- 与actived刚好相反, 不输出哪些的key,默认为null,即允许所有key. 注意,这是正则表达式!

Json.fromJson(pet, JsonFormat.full().setLocked("^(location)$"); // 不输出location,其他key正常输出

**Comment by wendal** [comment]
是的, thx
